import { deepMergeCopy, getLocale } from "./locale";
import { advancedSurfaceCopyZh } from "./advanced-surface-copy.zh";

export const advancedSurfaceCopyEn = {
  accessibility: {
    workspaceViews: "Workspace views",
    inspectorNavigation: "Inspector navigation",
    inspectorSections: "Inspector sections",
    inspectorTools: "tools",
    nextRunCapabilities: "Next-run task mode and effective Agent capabilities",
    nextRunMode: "Next-run task mode",
    currentRunReadiness: "Current run readiness",
    conversation: "Conversation",
    manageSandbox: "Manage Sandbox setup.",
    readOnly: "Read only",
    useAgentDefault: "Use Agent default",
    reviewAgentSettings: "Review Agent settings",
    useDefault: "Use default",
    agentSettings: "Agent settings",
  },
  conversationFollow: {
    newActivity: "New activity",
    resume: "Back to latest",
  },
  navigation: {
    task: "Task",
    inspect: "Inspect",
    studio: "Studio",
    browser: "Browser",
  },
  smallLabels: {
    previewSet: "Preview set",
    browserUse: "Browser Use",
    packages: "packages",
    revision: "revision",
    lockfile: "lockfile",
    turn: "Turn",
    lossless: "lossless",
    tokenAbbreviation: "tok",
    comparisonSeparator: "vs",
    sampleSize: "n",
  },
  promptPackage: {
    eyebrow: "PROMPT PACKAGE",
    title: "Compiled context layers",
    empty: "No compiled Prompt package has been recorded for this Thread.",
    promptBytes: "Prompt bytes",
    estimatedTokens: "Est. tokens",
    tools: "Tools",
    segments: "Segments",
    adapter: "Adapter",
    core: "Core",
    partition: "Partition",
    receipt: "Receipt",
    layers: {
      invariant_core: "Invariant Core",
      effective_capabilities: "Effective Capabilities",
      task_skill_overlay: "Task / Skill Overlay",
      workspace_context: "Workspace Context",
      model_adapter: "Model Adapter",
    },
  },
  qualification: {
    trials: "Independent trials",
    trialCount: "Qualification trial count",
    trialHelp:
      "Sequential runs; each trial creates and bills a fresh evaluator Run.",
    qualify: "Qualify evaluator",
    runTrialsPrefix: "Run",
    runTrialsSuffix: "trials",
    trialProgress: "Trial",
    of: "of",
    latestBatch: "Latest batch",
    completed: "completed",
    passed: "passed",
    meanAgreement: "mean agreement",
  },
  controlled: {
    track: "CONTROLLED HARNESS TRACK",
    title: "Competitor evidence gate",
    ready: "ready",
    notProven: "not proven",
    body: "Import the sanitized, hash-verified bundle generated from same-model, equivalent-Prompt, isolated comparison Trials. Narrow wins remain blocked until their fixed sample thresholds are met.",
    verifying: "Verifying evidence…",
    import: "Import evidence bundle",
    bundleLabel: "Controlled Harness evidence bundle",
    sizeError: "Controlled Harness evidence exceeds 512 KiB",
    passed: "passed",
    decisive: "decisive",
    minimum: "minimum",
    trials: "decisive Trials",
    coverage: "decisive coverage",
    advantage: "Quantified advantage",
    proven: "proven",
    empty: "No controlled comparison evidence recorded.",
    footer:
      "This covers competitor comparisons only; the Default Product, safety, cross-platform, and supply-chain gates remain independent.",
    domains: {
      search: "Search vs OMP",
      browser_omp: "Browser vs OMP",
      coding: "Coding vs OMP",
      browser_autonomy: "Browser autonomy vs Browser Use",
    },
    verdicts: {
      napier_not_worse: "Napier is not worse",
      napier_below_baseline: "Napier is below baseline",
      not_proven: "Not proven",
    },
    metrics: {
      recovery: "recovery",
      evidence: "evidence",
      understandability: "understandability",
    },
    units: {
      successful_recovery_rate: "successful recovery rate",
      verifiable_final_evidence_rate: "verifiable final evidence rate",
      task_state_comprehension_rate: "task state comprehension rate",
    },
    blockers: {
      controlled_evidence_missing: "Controlled evidence is missing",
      sample_not_proven: "Sample threshold is not proven",
      below_baseline: "Napier is below the baseline",
      secret_leak: "Secret leakage was detected",
      unconfirmed_side_effect: "An unconfirmed side effect was detected",
      quantified_advantage_not_proven: "Quantified advantage is not proven",
    },
  },
  defaultTrial: {
    templateUnavailable: "Release Product Casebook template is unavailable.",
    casesMissing: "Release Product Casebook is missing required M4 cases.",
    summary: "Record default product trial",
    body: "Bind this real terminal Run to one of the six M4 core product cases.",
    coreCase: "Core case",
    coreCaseLabel: "Default product core case",
    prepareLabel: "Prepare default product trial record",
    preparing: "Preparing…",
    prepare: "Prepare product trial record",
    loading: "Loading product trial contract…",
  },
  casebookTemplate: {
    creating: "Creating release template…",
    useTemplate: "Use release template",
    track: "FIXED PRODUCT COVERAGE",
    slot: "Coverage slot for the reviewed evaluation",
    slotLabel: "Product Casebook coverage slot",
    replace: "Replace",
    open: "Open",
    useInComposer: "Use in composer",
    incomplete:
      "Qualification unlocks after every fixed coverage slot has reviewed evidence.",
    complete:
      "Fixed Product Casebook coverage is complete and ready for qualification trials.",
  },
  releaseTrial: {
    track: "DEFAULT PRODUCT TRACK",
    title: "Versioned Run evidence",
    versions: "versions",
    body: "Record a real terminal Run. The gate requires every fixed Case, at least 90% success, and every critical Case passing.",
    productVersion: "Product version",
    productVersionLabel: "Release product version",
    terminalRun: "Terminal Run",
    terminalRunLabel: "Release product Run",
    noTerminalRun: "No terminal Run",
    outcome: "Outcome",
    outcomeLabel: "Release product outcome",
    passed: "Passed",
    failed: "Failed",
    inconclusive: "Inconclusive",
    incomplete: "Incomplete",
    failureClass: "Failure class",
    failureReasonLabel: "Release product failure reason",
    configurationInterventions: "Configuration interventions",
    humanInterventions: "Human interventions",
    recoveryEvents: "Recovery events",
    uxScore: "UX score",
    uxScoreLabel: "Release product UX score",
    recording: "Recording Run…",
    record: "Record product trial",
    duplicatePrefix: "This Run is already recorded for",
    completedOnly: "Only a completed Run can be recorded as passed.",
    footer:
      "This gate covers the Default Product Track only; cross-platform, supply-chain, safety, and competitor gates remain independent.",
    cases: "Cases",
    success: "success",
    trials: "Trials",
    human: "human",
    configuration: "config",
    recovery: "recovery",
    criticalPending: "Critical pending",
    failureReasons: {
      task_result: "Task result",
      tool_failure: "Tool failure",
      configuration: "Configuration",
      manual_intervention: "Manual intervention",
      recovery_failure: "Recovery failure",
      ux_blocker: "UX blocker",
    },
  },
};

export const advancedSurfaceCopy = deepMergeCopy(
  advancedSurfaceCopyEn,
  getLocale() === "zh" ? advancedSurfaceCopyZh : {},
);
