import type { LocaleOverride } from "./locale";
import type { advancedSurfaceCopyEn } from "./advanced-surface-copy";

export const advancedSurfaceCopyZh: LocaleOverride<
  typeof advancedSurfaceCopyEn
> = {
  accessibility: {
    workspaceViews: "工作区视图",
    inspectorNavigation: "检查器导航",
    inspectorSections: "检查器分区",
    inspectorTools: "工具",
    nextRunCapabilities: "下一次运行的任务模式与有效智能体能力",
    nextRunMode: "下一次运行的任务模式",
    currentRunReadiness: "当前运行准备状态",
    conversation: "对话",
    manageSandbox: "管理 Sandbox 设置。",
    readOnly: "只读",
    useAgentDefault: "使用智能体默认设置",
    reviewAgentSettings: "查看智能体设置",
    useDefault: "使用默认设置",
    agentSettings: "智能体设置",
  },
  conversationFollow: {
    newActivity: "新活动",
    resume: "回到最新",
  },
  navigation: {
    task: "任务",
    inspect: "检查",
    studio: "工作室",
    browser: "浏览器",
  },
  smallLabels: {
    previewSet: "预览集",
    browserUse: "浏览器使用",
    packages: "个包",
    revision: "修订",
    lockfile: "锁文件",
    turn: "轮次",
    lossless: "无损",
    tokenAbbreviation: "Token",
    comparisonSeparator: "对比",
    sampleSize: "样本",
  },
  promptPackage: {
    eyebrow: "PROMPT 包",
    title: "已编译上下文层",
    empty: "此会话尚未记录已编译的 Prompt 包。",
    promptBytes: "Prompt 字节数",
    estimatedTokens: "预计 Token",
    tools: "工具",
    segments: "分段",
    adapter: "适配器",
    core: "核心",
    partition: "分区",
    receipt: "回执",
    layers: {
      invariant_core: "不变核心",
      effective_capabilities: "有效能力",
      task_skill_overlay: "任务 / Skill 覆盖层",
      workspace_context: "工作区上下文",
      model_adapter: "模型适配器",
    },
  },
  qualification: {
    trials: "独立试验",
    trialCount: "资格试验次数",
    trialHelp: "按顺序运行；每次试验都会创建一个新的评估运行并单独计费。",
    qualify: "验证评估器",
    runTrialsPrefix: "运行",
    runTrialsSuffix: "次试验",
    trialProgress: "试验",
    of: "/",
    latestBatch: "最新批次",
    completed: "已完成",
    passed: "通过",
    meanAgreement: "平均一致率",
  },
  controlled: {
    track: "受控 HARNESS 轨道",
    title: "竞品证据门禁",
    ready: "就绪",
    notProven: "尚未证明",
    body: "导入同模型、等价 Prompt、隔离环境对照试验生成的脱敏且经过哈希校验的证据包。达到固定样本阈值前，不会宣称局部优势。",
    verifying: "正在校验证据……",
    import: "导入证据包",
    bundleLabel: "受控 Harness 证据包",
    sizeError: "受控 Harness 证据超过 512 KiB",
    passed: "通过",
    decisive: "有效",
    minimum: "最低",
    trials: "次有效试验",
    coverage: "有效覆盖率",
    advantage: "量化优势",
    proven: "已证明",
    empty: "尚未记录受控对照证据。",
    footer: "这里只覆盖竞品对照；默认产品、安全、跨平台和供应链门禁保持独立。",
    domains: {
      search: "搜索：Napier 对比 OMP",
      browser_omp: "浏览器：Napier 对比 OMP",
      coding: "编码：Napier 对比 OMP",
      browser_autonomy: "浏览器自主性：Napier 对比 Browser Use",
    },
    verdicts: {
      napier_not_worse: "Napier 不劣于基线",
      napier_below_baseline: "Napier 低于基线",
      not_proven: "尚未证明",
    },
    metrics: {
      recovery: "恢复",
      evidence: "证据",
      understandability: "可理解性",
    },
    units: {
      successful_recovery_rate: "成功恢复率",
      verifiable_final_evidence_rate: "可验证最终证据率",
      task_state_comprehension_rate: "任务状态理解率",
    },
    blockers: {
      controlled_evidence_missing: "缺少受控证据",
      sample_not_proven: "尚未达到可证明的样本阈值",
      below_baseline: "Napier 低于基线",
      secret_leak: "检测到密钥泄漏",
      unconfirmed_side_effect: "检测到未经确认的副作用",
      quantified_advantage_not_proven: "尚未证明量化优势",
    },
  },
  defaultTrial: {
    templateUnavailable: "发布产品 Casebook 模板不可用。",
    casesMissing: "发布产品 Casebook 缺少必需的 M4 场景。",
    summary: "记录默认产品试验",
    body: "将这个真实的终态运行绑定到六个 M4 核心产品场景之一。",
    coreCase: "核心场景",
    coreCaseLabel: "默认产品核心场景",
    prepareLabel: "准备默认产品试验记录",
    preparing: "正在准备……",
    prepare: "准备产品试验记录",
    loading: "正在加载产品试验合同……",
  },
  casebookTemplate: {
    creating: "正在创建发布模板……",
    useTemplate: "使用发布模板",
    track: "固定产品覆盖",
    slot: "为已评审的评估选择覆盖槽位",
    slotLabel: "产品 Casebook 覆盖槽位",
    replace: "替换",
    open: "空缺",
    useInComposer: "用于输入框",
    incomplete: "每个固定覆盖槽位都有已评审证据后，才会开放资格试验。",
    complete: "固定产品 Casebook 覆盖已完成，可以开始资格试验。",
  },
  releaseTrial: {
    track: "默认产品轨道",
    title: "版本化运行证据",
    versions: "个版本",
    body: "记录真实的终态运行。门禁要求覆盖全部固定场景、成功率至少 90%，且所有关键场景均通过。",
    productVersion: "产品版本",
    productVersionLabel: "发布产品版本",
    terminalRun: "终态运行",
    terminalRunLabel: "发布产品运行",
    noTerminalRun: "没有终态运行",
    outcome: "结果",
    outcomeLabel: "发布产品结果",
    passed: "通过",
    failed: "失败",
    inconclusive: "无结论",
    incomplete: "未完成",
    failureClass: "失败分类",
    failureReasonLabel: "发布产品失败原因",
    configurationInterventions: "配置干预次数",
    humanInterventions: "人工干预次数",
    recoveryEvents: "恢复事件数",
    uxScore: "UX 评分",
    uxScoreLabel: "发布产品 UX 评分",
    recording: "正在记录运行……",
    record: "记录产品试验",
    duplicatePrefix: "此运行已记录到版本",
    completedOnly: "只有已完成的运行才能记为通过。",
    footer:
      "此门禁只覆盖默认产品轨道；跨平台、供应链、安全和竞品门禁保持独立。",
    cases: "场景",
    success: "成功率",
    trials: "试验",
    human: "人工",
    configuration: "配置",
    recovery: "恢复",
    criticalPending: "待处理关键场景",
    failureReasons: {
      task_result: "任务结果",
      tool_failure: "工具失败",
      configuration: "配置",
      manual_intervention: "人工干预",
      recovery_failure: "恢复失败",
      ux_blocker: "UX 阻塞",
    },
  },
};
