export const automationCopy = {
  eyebrow: "BACKGROUND OPERATIONS",
  title: "Automations",
  loading: "Opening automation register...",
  recovery: "Recovery ledger",
  recoveryEyebrow: "PROVABLE CONTINUITY",
  recoveryQualified: "Qualified",
  recoveryBlocked: "Blocked",
  recoveryCompleted: "Completed",
  recoveryAttempt: "Attempt",
  recoveryEvents: "Events",
  recoveryTools: "Tool calls",
  recoverySource: "Source Run",
  noRecoveries:
    "No interrupted Run has reached an automatic recovery decision.",
  recoveryQualifiedBody:
    "The source evidence proved a read-only continuation boundary.",
  recoverySafety:
    "Every decision binds the interrupted configuration and event stream. Unknown outcomes, writes, imported history, demo models, and exhausted attempt chains stop automatically.",
  recoveryStatuses: {
    skipped: "Blocked",
    claimed: "Claimed",
    running: "Recovering",
    completed: "Recovered",
    failed: "Failed",
    cancelled: "Cancelled",
    interrupted: "Interrupted",
    abandoned: "Abandoned",
  },
  recoveryReasons: {
    configuration_missing: "Run configuration evidence is missing.",
    legacy_configuration: "Legacy schema has no bound recovery policy.",
    policy_manual: "The frozen Agent policy requires manual Resume.",
    run_not_interrupted: "The source Run is not interrupted.",
    demo_model: "The demo model cannot verify current state.",
    event_limit_exceeded: "The evidence range exceeds the safety limit.",
    unresolved_tool_call: "A tool start has no unique terminal outcome.",
    unsafe_tool_effect: "A write or delegated side effect was observed.",
    unknown_tool_effect: "A tool effect is not proven read-only.",
    attempt_limit_reached: "The frozen attempt limit is exhausted.",
    untrusted_recovery_chain:
      "The recovery chain or import provenance is untrusted.",
  },
  schedules: "Scheduled runs",
  scheduleEyebrow: "DURABLE TRIGGERS",
  scheduleName: "Schedule name",
  scheduleNamePlaceholder: "Morning evidence review",
  prompt: "Run prompt",
  promptPlaceholder: "Review the active ledger and settle open loops.",
  triggerType: "Trigger",
  interval: "Interval",
  cron: "UTC cron",
  intervalMinutes: "Every (minutes)",
  cronExpression: "Cron expression",
  cronPlaceholder: "0 9 * * 1-5",
  createSchedule: "Create schedule",
  creating: "Creating...",
  noSchedules: "No scheduled runs target this ledger.",
  nextRun: "Next",
  lastRun: "Last run",
  never: "Never",
  pause: "Pause",
  resume: "Resume",
  active: "Active",
  paused: "Paused",
  claim: "Claimed",
  revision: "REV",
  scheduleSafety:
    "Every occurrence receives a deterministic trigger ID and a renewable run lease. Overlaps are skipped and recorded.",
  channels: "Inbound webhooks",
  channelEyebrow: "AUTHENTICATED INBOX",
  channelName: "Channel name",
  channelNamePlaceholder: "CI notifications",
  channelAdapter: "Adapter",
  idempotencySource: "Idempotency",
  policyTemplate: "Policy template",
  policyTemplateLabels: {
    legacy_bearer: "Legacy bearer",
    signed_standard: "Signed standard",
    signed_strict: "Signed strict",
    custom: "Custom",
  },
  maxAttempts: "Maximum attempts",
  retryBaseSeconds: "Base delay (seconds)",
  requireSignature: "Require HMAC body signature",
  signaturePolicy: "Signature policy",
  signatureRequired: "HMAC required",
  signatureOptional: "Bearer token only",
  createChannel: "Create webhook",
  noChannels: "No webhook channels target this ledger.",
  endpoint: "Endpoint",
  fingerprint: "Token fingerprint",
  disable: "Disable",
  enable: "Enable",
  rotateToken: "Rotate token",
  rotateTitle: "Replace the current token?",
  rotateBody:
    "The existing token stops working immediately after its replacement is issued.",
  rotateNow: "Rotate now",
  rotating: "Rotating...",
  cancel: "Cancel",
  deliveries: "Deliveries",
  loadDeliveries: "View deliveries",
  noDeliveries: "No deliveries have been received.",
  attempt: "Attempt",
  nextAttempt: "Next attempt",
  retryDelivery: "Retry",
  qualifyDelivery: "Qualify",
  qualifying: "Checking...",
  deliveryQualification: "Evidence",
  qualificationReceipt: "receipt",
  bodyHash: "body",
  catalogHash: "catalog",
  currentCatalogHash: "current",
  hashMissing: "missing",
  qualificationStatuses: {
    qualified: "Qualified",
    evidence_missing: "Evidence missing",
    adapter_catalog_drift: "Catalog drift",
  },
  retryTitle: "Run another delivery attempt?",
  retryBody:
    "Verify the previous attempt and any possible side effects first. A retry creates a new, separately evidenced Agent run.",
  retryNow: "Retry now",
  retryingAction: "Queuing...",
  retryExhausted: "Retry limit reached",
  retryPolicy: "Retry policy",
  policyAttempts: "attempts",
  policyBase: "base delay",
  editPolicy: "Retry policy",
  editSignaturePolicy: "Signature policy",
  previewAdapter: "Preview adapter",
  previewTitle: "No-store adapter preview",
  previewBody:
    "Validate how this adapter maps sample headers and body into an Agent delivery before accepting real work.",
  previewHeaders: "Headers JSON",
  previewPayload: "Body",
  previewNow: "Preview",
  previewing: "Previewing...",
  previewHeadersInvalid: "Preview headers must be a JSON object of strings.",
  previewReceipt: "Adapter preview",
  previewReceiptHash: "Receipt",
  previewMessageHash: "Message",
  policyTitle: "Revise retry policy",
  policyBody:
    "New deliveries snapshot this policy. Existing deliveries keep the attempt and backoff limits they were accepted with.",
  signaturePolicyTitle: "Revise signature policy",
  signaturePolicyBody:
    "New inbound requests use this policy immediately. Existing accepted deliveries keep their original evidence.",
  signatureToleranceSeconds: "Timestamp tolerance (seconds)",
  savePolicy: "Save policy",
  savingPolicy: "Saving...",
  exportDeadLetters: "Export failures",
  exporting: "Exporting...",
  exported: "Exported failures",
  verifyDeadLetterExport: "Verify export",
  verifyingDeadLetterExport: "Verifying...",
  deadLetterArtifactTooLarge: "Dead-letter export JSON is too large.",
  deadLetterVerificationValid: "Verified export",
  deadLetterVerificationInvalid: "Invalid export",
  deadLetterRetryPreview: "Retry preview",
  deadLetterRetryPreviewMissing:
    "Upload and verify a dead-letter export first.",
  deadLetterRetryConfirmBody:
    "Apply this exact preview hash and requeue the retryable failed deliveries. Review possible side effects before continuing.",
  applyDeadLetterRetry: "Apply retry preview",
  applyDeadLetterRetryNow: "Apply now",
  applyingDeadLetterRetry: "Applying...",
  deadLetterRetryApplied: "Applied retries",
  deadLetterRetryHistory: "Retry history",
  deadLetterRetryHistoryEvents: "Events",
  deadLetterRetryHistorySet: "Event set",
  deadLetterRetryHistoryLatest: "Latest",
  deadLetterRetryHistoryApply: "Apply",
  downloadDeadLetterRetryHistory: "Download history",
  downloadingDeadLetterRetryHistory: "Downloading...",
  verifyDeadLetterRetryHistory: "Verify history",
  verifyDeadLetterRetryHistoryFile: "Verify history JSON",
  verifyingDeadLetterRetryHistory: "Verifying...",
  deadLetterRetryHistoryArtifactTooLarge:
    "Dead-letter retry history JSON is too large.",
  deadLetterRetryHistoryVerificationValid: "Verified history",
  deadLetterRetryHistoryVerificationInvalid: "Invalid history",
  deadLetterRetryHistoryEmpty: "No retry apply events yet.",
  retryableShort: "Retryable",
  blockedShort: "Blocked",
  deadLetterRetryCandidateStatuses: {
    retryable: "Retryable",
    artifact_invalid: "Artifact invalid",
    not_found: "Not found",
    not_failed: "Not failed",
    retry_exhausted: "Retry exhausted",
    state_changed: "State changed",
  },
  qualifiedShort: "Q",
  missingShort: "Missing",
  driftShort: "Drift",
  tokenTitle: "Token shown once",
  bearerToken: "Bearer token",
  tokenBody:
    "Store this token now. Napier persists only its SHA-256 digest. Signed channels use it as the HMAC key and cannot display it again.",
  dismiss: "I stored it",
  copied: "Copied",
  copyToken: "Copy token",
  webhook: "Webhook",
  channelSafety:
    "Webhook bodies are bounded. Tokens and idempotency keys are hashed. Adapter parsing normalizes external payloads before delivery acceptance.",
  statuses: {
    accepted: "Accepted",
    running: "Running",
    retrying: "Retrying",
    completed: "Completed",
    failed: "Failed",
  },
} as const;
