import type { LocaleOverride } from "./locale";
import type { automationCopyEn } from "./automation-copy";

export const automationCopyZh: LocaleOverride<typeof automationCopyEn> = {
  eyebrow: "后台运行",
  title: "自动化",
  loading: "正在打开自动化注册表……",
  recovery: "恢复记录",
  recoveryEyebrow: "可证明的连续性",
  recoveryQualified: "符合条件",
  recoveryBlocked: "已阻止",
  recoveryCompleted: "已完成",
  recoveryAttempt: "尝试",
  recoveryEvents: "事件",
  recoveryTools: "工具调用",
  recoverySource: "来源运行",
  noRecoveries: "尚无中断运行进入自动恢复决策。",
  recoveryQualifiedBody: "来源证据证明了只读继续边界。",
  recoverySafety:
    "每个决策都绑定中断时的配置与事件流。结果未知、发生写入、导入历史、演示模型或尝试次数耗尽时都会自动停止。",
  recoveryStatuses: {
    skipped: "已阻止",
    claimed: "已认领",
    running: "正在恢复",
    completed: "已恢复",
    failed: "失败",
    cancelled: "已取消",
    interrupted: "已中断",
    abandoned: "已放弃",
  },
  recoveryReasons: {
    configuration_missing: "缺少运行配置证据。",
    legacy_configuration: "旧版结构未绑定恢复策略。",
    policy_manual: "冻结的智能体策略要求手动继续。",
    run_not_interrupted: "来源运行并未中断。",
    workflow_managed: "该来源运行只能由其类型化工作流计划继续。",
    demo_model: "演示模型无法验证当前状态。",
    event_limit_exceeded: "证据范围超过安全上限。",
    unresolved_tool_call: "某个工具调用没有唯一的终态结果。",
    unsafe_tool_effect: "检测到写入或委派副作用。",
    unknown_tool_effect: "无法证明工具效果为只读。",
    attempt_limit_reached: "冻结的尝试次数已用尽。",
    untrusted_recovery_chain: "恢复链或导入来源不可信。",
  },
  schedules: "定时运行",
  scheduleEyebrow: "持久触发器",
  scheduleName: "计划名称",
  scheduleNamePlaceholder: "晨间证据检查",
  prompt: "运行提示词",
  promptPlaceholder: "检查当前记录并处理未完成事项。",
  triggerType: "触发方式",
  interval: "间隔",
  cron: "UTC Cron",
  intervalMinutes: "每隔（分钟）",
  cronExpression: "Cron 表达式",
  cronPlaceholder: "0 9 * * 1-5",
  createSchedule: "创建计划",
  creating: "正在创建……",
  noSchedules: "没有定时运行指向此记录。",
  nextRun: "下次运行",
  lastRun: "上次运行",
  never: "从未",
  pause: "暂停",
  resume: "恢复",
  active: "已启用",
  paused: "已暂停",
  claim: "已认领",
  revision: "修订",
  scheduleSafety:
    "每次触发都会获得确定性的触发 ID 和可续期运行租约。重叠执行会被跳过并记录。",
  channels: "入站 Webhook",
  channelEyebrow: "认证收件箱",
  channelName: "通道名称",
  channelNamePlaceholder: "CI 通知",
  channelAdapter: "适配器",
  idempotencySource: "幂等来源",
  policyTemplate: "策略模板",
  policyTemplateLabels: {
    legacy_bearer: "旧版 Bearer",
    signed_standard: "标准签名",
    signed_strict: "严格签名",
    custom: "自定义",
  },
  maxAttempts: "最大尝试次数",
  retryBaseSeconds: "基础延迟（秒）",
  requireSignature: "要求 HMAC 正文签名",
  signaturePolicy: "签名策略",
  signatureRequired: "必须使用 HMAC",
  signatureOptional: "仅使用 Bearer Token",
  createChannel: "创建 Webhook",
  noChannels: "没有 Webhook 通道指向此记录。",
  endpoint: "端点",
  fingerprint: "Token 指纹",
  disable: "停用",
  enable: "启用",
  rotateToken: "轮换 Token",
  rotateTitle: "替换当前 Token？",
  rotateBody: "签发替代 Token 后，现有 Token 会立即失效。",
  rotateNow: "立即轮换",
  rotating: "正在轮换……",
  cancel: "取消",
  deliveries: "投递",
  loadDeliveries: "查看投递",
  noDeliveries: "尚未收到投递。",
  attempt: "尝试",
  nextAttempt: "下次尝试",
  retryDelivery: "重试",
  qualifyDelivery: "校验证据",
  qualifying: "正在检查……",
  deliveryQualification: "证据",
  qualificationReceipt: "回执",
  bodyHash: "正文",
  catalogHash: "目录",
  currentCatalogHash: "当前",
  hashMissing: "缺失",
  qualificationStatuses: {
    qualified: "符合条件",
    evidence_missing: "缺少证据",
    adapter_catalog_drift: "目录漂移",
  },
  retryTitle: "再次尝试投递？",
  retryBody:
    "请先核验上次尝试及其可能产生的副作用。重试会创建一个单独留存证据的新智能体运行。",
  retryNow: "立即重试",
  retryingAction: "正在排队……",
  retryExhausted: "已达到重试上限",
  retryPolicy: "重试策略",
  policyAttempts: "次尝试",
  policyBase: "基础延迟",
  editPolicy: "重试策略",
  editSignaturePolicy: "签名策略",
  previewAdapter: "预览适配器",
  previewTitle: "不落库的适配器预览",
  previewBody:
    "在接收真实工作前，验证此适配器如何将样例请求头与正文映射为智能体投递。",
  previewHeaders: "请求头 JSON",
  previewPayload: "正文",
  previewNow: "预览",
  previewing: "正在预览……",
  previewHeadersInvalid: "预览请求头必须是字符串键值组成的 JSON 对象。",
  previewReceipt: "适配器预览",
  previewReceiptHash: "回执",
  previewMessageHash: "消息",
  policyTitle: "修改重试策略",
  policyBody: "新投递会快照此策略；已有投递保留接收时的尝试次数和退避上限。",
  signaturePolicyTitle: "修改签名策略",
  signaturePolicyBody: "新的入站请求会立即使用此策略；已接收投递保留原始证据。",
  signatureToleranceSeconds: "时间戳容差（秒）",
  savePolicy: "保存策略",
  savingPolicy: "正在保存……",
  exportDeadLetters: "导出失败项",
  exporting: "正在导出……",
  exported: "已导出失败项",
  verifyDeadLetterExport: "验证导出文件",
  verifyingDeadLetterExport: "正在验证……",
  deadLetterArtifactTooLarge: "死信导出 JSON 过大。",
  deadLetterVerificationValid: "导出文件有效",
  deadLetterVerificationInvalid: "导出文件无效",
  deadLetterRetryPreview: "重试预览",
  deadLetterRetryPreviewMissing: "请先上传并验证死信导出文件。",
  deadLetterRetryConfirmBody:
    "应用这一准确的预览哈希，并重新排队可重试的失败投递。继续前请检查可能的副作用。",
  applyDeadLetterRetry: "应用重试预览",
  applyDeadLetterRetryNow: "立即应用",
  applyingDeadLetterRetry: "正在应用……",
  deadLetterRetryApplied: "已应用重试",
  deadLetterRetryHistory: "重试历史",
  deadLetterRetryHistoryEvents: "事件",
  deadLetterRetryHistorySet: "事件集",
  deadLetterRetryHistoryLatest: "最新",
  deadLetterRetryHistoryApply: "应用",
  downloadDeadLetterRetryHistory: "下载历史",
  downloadingDeadLetterRetryHistory: "正在下载……",
  verifyDeadLetterRetryHistory: "验证历史",
  verifyDeadLetterRetryHistoryFile: "验证历史 JSON",
  verifyingDeadLetterRetryHistory: "正在验证……",
  deadLetterRetryHistoryArtifactTooLarge: "死信重试历史 JSON 过大。",
  deadLetterRetryHistoryVerificationValid: "历史有效",
  deadLetterRetryHistoryVerificationInvalid: "历史无效",
  deadLetterRetryHistoryEmpty: "尚无重试应用事件。",
  historyHash: "历史",
  previewHash: "预览",
  retriedHash: "已重试",
  verificationHash: "验证",
  observedHash: "观测值",
  candidateSetHash: "集合",
  previewSetHash: "预览集",
  resultHash: "结果",
  retryableShort: "可重试",
  blockedShort: "已阻止",
  deadLetterRetryCandidateStatuses: {
    retryable: "可重试",
    artifact_invalid: "Artifact 无效",
    not_found: "未找到",
    not_failed: "并非失败状态",
    retry_exhausted: "重试次数已用尽",
    state_changed: "状态已变化",
  },
  qualifiedShort: "合格",
  missingShort: "缺失",
  driftShort: "漂移",
  tokenTitle: "Token 仅显示一次",
  bearerToken: "Bearer Token",
  tokenBody:
    "请立即保存此 Token。Napier 只持久化其 SHA-256 摘要；签名通道将它作为 HMAC 密钥，之后无法再次显示。",
  dismiss: "我已保存",
  copied: "已复制",
  copyToken: "复制 Token",
  webhook: "Webhook",
  channelSafety:
    "Webhook 正文有大小限制；Token 与幂等键会被哈希；适配器解析会在接受投递前规范化外部载荷。",
  statuses: {
    accepted: "已接收",
    running: "运行中",
    retrying: "正在重试",
    completed: "已完成",
    failed: "失败",
  },
};
