import type { LocaleOverride } from "./locale";
import type { browserLiveCopyEn } from "./browser-live-copy";

export const browserLiveCopyZh: LocaleOverride<typeof browserLiveCopyEn> = {
  inspector: {
    eyebrow: "实时会话",
    title: "浏览器",
    active: "浏览器实时视图已启用",
    inactive: "没有活跃的浏览器视图",
    activeDescription:
      "暂停、交还、接管和视觉证据都保留在主工作区的当前任务中。",
    inactiveDescription:
      "当活跃运行打开浏览器会话后，主工作区会显示浏览器实时视图。",
    open: "在任务中打开",
  },
  live: {
    label: "浏览器实时视图",
    running: "运行中",
    paused: "已暂停",
    resumeTitle: "允许执行下一个浏览器动作",
    pauseTitle: "在当前浏览器动作结束后暂停",
    working: "处理中",
    resume: "交还",
    pause: "暂停",
    takeover: "接管",
    refresh: "刷新",
    humanVerification: "需要人工验证",
    loginRequired: "需要登录",
    diagnosisDescription:
      "请在这个隔离的浏览器配置中私下继续。Napier 不会破解 CAPTCHA，也不会导入现有 Chrome 登录状态。",
    viewportAlt: "活跃隔离浏览器会话的实时视口",
    openingControls: "正在打开人工控制……",
    operation: "操作",
    tab: "个标签页",
    origin: "来源",
    controlRetry: "需要重试控制操作",
  },
  confirmation: {
    eyebrow: "浏览器动作",
    confirm: "确认",
    description:
      "此动作在执行前已暂停。批准只绑定到这一次经过校验的参数，不能重复使用。",
    labels: {
      action: "动作",
      effect: "影响",
      arguments: "参数",
      target: "目标",
      text: "文本",
      values: "值数量",
      workspacePath: "工作区路径",
      file: "文件",
      pageState: "页面状态",
      sourceImage: "源图像",
      expires: "过期时间",
      crossOrigin: "跨来源",
      bytes: "字节",
    },
    authorized: "已授权",
    unauthorized: "否",
    reject: "拒绝",
    approve: "仅批准一次",
    actions: {
      click: "点击",
      type: "输入",
      select: "选择",
      upload: "上传",
      download: "下载",
      save_screenshot: "保存截图",
    },
    effects: {
      interaction: "与页面交互",
      data_entry: "输入数据",
      selection_change: "更改选择",
      file_upload: "上传文件",
      file_download: "下载文件",
      screenshot_save: "保存截图",
      form_submit: "提交表单",
      communication: "发送通信内容",
      publication: "发布内容",
      purchase: "购买或付款",
      deletion: "删除或移除",
      permission_change: "更改权限",
    },
  },
  takeover: {
    label: "浏览器接管",
    eyebrow: "操作者控制 · 绑定暂停状态",
    title: "接管这个隔离的浏览器会话",
    freshRefs: "刷新引用",
    tabs: "浏览器标签页",
    closeTab: "关闭",
    verifiedViewport: "点击已校验的浏览器视口",
    verifiedViewportAlt: "用于视觉点击的已校验浏览器视口",
    ariaSnapshot: "不可信的浏览器 ARIA 快照",
    emptySnapshot: "（空页面快照）",
    readingTab: "正在读取已暂停的标签页……",
    refreshForRefs: "请刷新以获取最新引用。",
    newPublicUrl: "新的公开网址",
    newTab: "新建标签页",
    action: "动作",
    modes: { click: "点击", type: "输入", select: "选择" },
    freshRef: "最新引用",
    text: "文本",
    values: "值（每行一个）",
    allowCrossOrigin: "允许一次跨来源导航",
    executeOnce: "仅执行一次",
    navigationKey: "导航按键",
    pressKey: "按键",
    scrollUp: "向上滚动",
    scrollDown: "向下滚动",
    back: "后退",
    forward: "前进",
    wait: "等待 1 秒",
    snapshot: "快照",
    noSnapshot: "没有最新快照",
    returnToAgent: "交还智能体",
    output: {
      path: "新的工作区输出",
      saveScreenshot: "保存截图",
      downloadRef: "下载引用目标",
      constraints: "仅限新文件 · 父目录必须存在 · PNG 8 MiB / 下载 32 MiB",
      screenshotSaved: "截图已保存",
      downloadSaved: "下载已保存",
      bytes: "字节",
    },
  },
};
