import { deepMergeCopy, getLocale } from "./locale";
import { browserLiveCopyZh } from "./browser-live-copy.zh";

export const browserLiveCopyEn = {
  inspector: {
    eyebrow: "LIVE SESSION",
    title: "Browser",
    active: "Browser Live is active",
    inactive: "No active Browser view",
    activeDescription:
      "Pause, Resume, Take control, and visual evidence stay with the task in the main workspace.",
    inactiveDescription:
      "Browser Live appears in the main workspace when the active Run has an open Browser Session.",
    open: "Open in task",
  },
  live: {
    label: "Browser Live",
    running: "Running",
    paused: "Paused",
    resumeTitle: "Allow the next Browser action",
    pauseTitle: "Pause after the current Browser action",
    working: "Working",
    resume: "Resume",
    pause: "Pause",
    takeover: "Take control",
    refresh: "Refresh",
    humanVerification: "Human verification required",
    loginRequired: "Login required",
    diagnosisDescription:
      "Continue privately in this isolated Browser profile. Napier does not solve CAPTCHAs or import existing Chrome login state.",
    viewportAlt: "Live viewport from the active isolated Browser Session",
    openingControls: "Opening operator controls…",
    operation: "op",
    tab: "tab",
    origin: "origin",
    controlRetry: "control retry required",
  },
  confirmation: {
    eyebrow: "BROWSER ACTION",
    confirm: "Confirm",
    description:
      "This one action is paused before execution. Approval is bound to the exact validated arguments and cannot be reused.",
    labels: {
      action: "Action",
      effect: "Effect",
      arguments: "Arguments",
      target: "Target",
      text: "Text",
      values: "Values",
      workspacePath: "Workspace path",
      file: "File",
      pageState: "Page state",
      sourceImage: "Source image",
      expires: "Expires",
      crossOrigin: "Cross-origin",
      bytes: "bytes",
    },
    authorized: "authorized",
    unauthorized: "no",
    reject: "Reject",
    approve: "Approve once",
    actions: {
      click: "click",
      type: "type",
      select: "select",
      upload: "upload",
      download: "download",
      save_screenshot: "save screenshot",
    },
    effects: {
      interaction: "Interact with page",
      data_entry: "Enter data",
      selection_change: "Change selection",
      file_upload: "Upload file",
      file_download: "Download file",
      screenshot_save: "Save screenshot",
      form_submit: "Submit form",
      communication: "Send communication",
      publication: "Publish content",
      purchase: "Purchase or pay",
      deletion: "Delete or remove",
      permission_change: "Change permissions",
    },
  },
  takeover: {
    label: "Browser takeover",
    eyebrow: "OPERATOR CONTROL · PAUSE BOUND",
    title: "Take control of this isolated Browser Session",
    freshRefs: "Fresh refs",
    tabs: "Browser tabs",
    closeTab: "Close",
    verifiedViewport: "Click the verified Browser viewport",
    verifiedViewportAlt: "Verified Browser viewport for visual click",
    ariaSnapshot: "Untrusted Browser ARIA snapshot",
    emptySnapshot: "(empty page snapshot)",
    readingTab: "Reading the paused tab…",
    refreshForRefs: "Refresh to obtain fresh refs.",
    newPublicUrl: "New public URL",
    newTab: "New tab",
    action: "Action",
    modes: { click: "click", type: "type", select: "select" },
    freshRef: "Fresh ref",
    text: "Text",
    values: "Values · one per line",
    allowCrossOrigin: "Allow one cross-origin navigation",
    executeOnce: "Execute once",
    navigationKey: "Navigation key",
    pressKey: "Press key",
    scrollUp: "Scroll up",
    scrollDown: "Scroll down",
    back: "Back",
    forward: "Forward",
    wait: "Wait 1s",
    snapshot: "snapshot",
    noSnapshot: "no fresh snapshot",
    returnToAgent: "Return to Agent",
    output: {
      path: "New workspace output",
      saveScreenshot: "Save screenshot",
      downloadRef: "Download ref",
      constraints:
        "New file only · existing parent · PNG 8 MiB / download 32 MiB",
      screenshotSaved: "Screenshot saved",
      downloadSaved: "Download saved",
      bytes: "bytes",
    },
  },
};

export const browserLiveCopy = deepMergeCopy(
  browserLiveCopyEn,
  getLocale() === "zh" ? browserLiveCopyZh : {},
);
