import type { LocaleOverride } from "./locale";
import type { browserTaskCopyEn } from "./browser-task-copy";

export const browserTaskCopyZh: LocaleOverride<typeof browserTaskCopyEn> = {
  panel: {
    title: "自主浏览器任务",
    description:
      "按需启用 Browser Use 本地或云端执行。导航受域名约束，页面交互仅限公开只读；智能体仍默认使用原生 Playwright。",
  },
  form: {
    backend: "执行后端",
    backends: {
      browser_use_local: "Browser Use 本地",
      browser_use_cloud: "Browser Use 云端",
    },
    retry: "重试同一任务",
    startLocal: "启动本地任务",
    startCloud: "启动云端任务",
    restoredHistory: "已恢复历史记录",
    reconnected: "已重新连接",
    checking: "正在检查活跃的浏览器任务……",
    nativeDefault: "智能体仍默认使用原生 Playwright。",
    actions: {
      pause: "暂停",
      resume: "交还智能体",
      takeover: "接管",
      stopping: "正在停止……",
      stop: "停止",
    },
    statuses: {
      idle: "就绪",
      restoring: "正在恢复",
      starting: "正在启动",
      running: "运行中",
      paused: "已暂停",
      takeover: "已接管",
      stopping: "正在停止",
      terminal: "已结束",
    },
    scope: {
      task: "任务",
      taskPlaceholder: "总结此站点的最新版本说明",
      startUrl: "起始网址",
      allowedDomains: "允许的域名",
      allowedDomainsPlaceholder: "默认从起始网址推导，也可用英文逗号分隔",
    },
    model: {
      provider: "模型提供方",
      id: "模型 ID",
      credential: "凭证",
      activeCredential: "已启用凭证",
      secretServerSide: "密钥仅保留在服务端。",
      noActiveCredential: "没有可用的提供方凭证引用。",
      addCredential: "请在“上下文 → 凭证”中添加，或使用环境变量覆盖。",
      environmentOverride: "环境变量覆盖",
      variableName: "变量名",
      maximumSteps: "最大步骤数",
      maximumCost: "最高费用（USD）",
      availability: {
        unknown: "尚未检查",
        available: "可用",
        missing: "缺失",
        error: "需要修复",
      },
    },
    localDisclosure: {
      title: "可见的本地浏览器与人工接管",
      privacy:
        "此后端会使用全新的本地配置启动独立的可见浏览器。除所选模型提供方外，页面数据不会离开本机。下载、上传、输入敏感信息、购买、发布、删除以及绕过验证挑战均保持禁用。",
      controls:
        "暂停只会冻结智能体进程；接管后浏览器仍可由你操作；交还智能体后，它会重新观察当前页面。检测到 CAPTCHA 时会自动进入接管。停止会关闭任务浏览器及其进程组。",
    },
    cloudDisclosure: {
      title: "云端数据与计费边界",
      data: "Browser Use 会接收任务、起始网址、允许域名、页面数据和截图。Napier 不会发送工作区文件或模型密钥；请求仅使用 Browser Use API 密钥认证。只读策略禁止下载。Napier 会关闭录制，也不会请求配置文件、代理、工作区、技能或密钥转发。数据保留遵循提供方套餐，不能假定为零保留。",
      cost: "USD 上限依据提供方上报的费用轮询执行，因此两次轮询之间的用量可能超过上限。",
      stop: "停止会销毁一次性任务和会话。Browser Use Cloud v2 不支持暂停和接管。",
      consent: "我了解此任务会将页面数据发送到 Browser Use 云端。",
      consentRequired: "必须确认云端数据流转边界",
    },
  },
  evidence: {
    cloudActive: "云端运行中",
    credentialConfigured: "凭证已配置",
    workspaceAccessNone: "无工作区访问",
    recordingDisabled: "录制已关闭",
    retentionProviderPlan: "保留策略遵循提供方套餐",
    pollStopCeiling: "轮询停止上限",
    localVisible: "本地可见",
    agent: "智能体",
    controls: "暂停/接管",
    ready: "可用",
    unavailable: "不可用",
    captcha: "CAPTCHA",
    automaticTakeover: "自动接管",
    handoff: "人工交接",
    latestStepAlt: "浏览器任务的最新步骤",
    step: "步骤",
    steps: "浏览器任务步骤",
    observe: "观察页面",
    agentStates: {
      running: "运行中",
      paused: "已暂停",
      takeover: "已接管",
      stopped: "已停止",
      failed: "失败",
      completed: "已完成",
      cancelled: "已取消",
      handoff_required: "需要人工交接",
    },
  },
  terminal: {
    diagnostic: "诊断",
    cost: "费用",
    unknown: "未知",
    artifacts: "产物",
    steps: "步",
    retentionProviderPlan: "保留策略遵循提供方套餐",
    statuses: {
      completed: "已完成",
      failed: "失败",
      cancelled: "已取消",
      handoff_required: "需要人工交接",
    },
  },
};
