export const contextCopy = {
  eyebrow: "RUNTIME ASSEMBLY",
  title: "Agent context",
  revision: "REV",
  nextRun: "NEXT RUN",
  runModel: "Runtime model",
  chooseModel: "Model for the next run",
  runModelHint:
    "This choice applies immediately to the next run. Save the profile below to make it the Agent default.",
  modelUnavailableHint:
    "Configure this provider before using it for runs or saving it as the Agent default.",
  unavailable: "unavailable",
  profileEyebrow: "PERSISTENT PROFILE",
  profile: "Agent configuration",
  name: "Agent name",
  description: "Description",
  systemPrompt: "System prompt",
  systemPromptHint:
    "Stored as profile configuration. Prompt content is never copied into audit-event payloads.",
  promptVariables: "Prompt variables",
  promptVariablesTitle: "Frozen run variables",
  promptVariablesKicker: "SINGLE PASS · HASH-BOUND",
  promptVariablesBody:
    "Declared tokens resolve once when a Run starts. Values never recurse, and the Ledger stores only value hashes, counts, and the rendered System Prompt SHA-256.",
  promptVariablesEmpty:
    "No declarations. Unknown {{tokens}} remain unchanged and are still counted in the frozen Run receipt.",
  promptVariablesInvalid:
    "Resolve duplicate or invalid names and literal capacity limits before saving.",
  promptVariableAdd: "Add variable",
  promptVariableIndex: "VAR",
  promptVariableInsert: "Insert token into System Prompt",
  promptVariableRemove: "Remove variable",
  promptVariableName: "Token name",
  promptVariableNamePlaceholder: "project_context",
  promptVariableFallbackName: "variable",
  promptVariableType: "Source",
  promptVariableTypes: {
    literal: "Literal value",
    current_date: "Current date",
    skill_catalog: "Skill catalog",
  },
  promptVariableValue: "Frozen value",
  promptVariableLiteralDefault: "value",
  promptVariableDateFormat: "Date format",
  promptVariableDateFormats: {
    "readable-date": "YYYY-MM-DD, weekday",
    "iso-date": "YYYY-MM-DD",
    "local-date-time": "Local date, time, and zone",
  },
  promptVariableSkillCatalogBody:
    "Injects the exact Pi-compatible catalog loaded for this Run. The catalog is not appended a second time.",
  thinking: "Thinking level",
  thinkingLevels: {
    off: "Off",
    minimal: "Minimal",
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  policy: "Tool policy",
  policies: {
    observe: "Observe only",
    workspace: "Workspace actions",
    unrestricted: "Unrestricted policy",
  },
  policyHint:
    "Authorization is checked immediately before every call. Edits require a fresh SHA-256 and can use read_file line anchors; verification runs read-only, offline, and without a shell.",
  recoveryPolicy: "Interruption policy",
  recoveryTitle: "Safe automatic recovery",
  recoveryKicker: "SNAPSHOT-BOUND · FAIL CLOSED",
  recoveryMode: "Recovery mode",
  recoveryModes: {
    manual: "Manual resume only",
    safe_read_only: "Automatic · safe read-only",
  },
  recoveryAttempts: "Maximum attempts",
  recoveryBackoff: "Base delay (sec)",
  recoverySafeBody:
    "Only a schema-2 interrupted Run with no unresolved tools, writes, unknown effects, or imported provenance can continue. The child Run uses the frozen Agent revision and exposes only local read tools.",
  recoveryManualBody:
    "Interrupted Runs wait for an operator. Manual Resume remains available and always warns that prior tool outcomes may be unknown.",
  modelAdvisor: "Model Advisor",
  modelAdvisorMode: "Advisor mode",
  modelAdvisorModes: {
    observe: "Observe and record",
    enforce: "Fail closed on blockers",
    off: "Off",
  },
  modelAdvisorRules: "Advisor rules",
  modelAdvisorRuleLabels: {
    unverified_verification_claim: "Unverified checks",
    destructive_command_reference: "Dangerous command",
  },
  modelAdvisorCorrectionAttempts: "Correction attempts",
  modelAdvisorReviewModel: "Independent review model",
  modelAdvisorReviewModelDisabled: "Deterministic rules only",
  modelAdvisorReviewModelPrimary: "primary model",
  modelAdvisorReviewModelUnavailableHint:
    "Choose a configured live model that is different from the primary runtime model.",
  modelAdvisorBody:
    "Candidate output is linted and can be reviewed by a distinct zero-tool model before it becomes visible. Enforced blockers share up to three tool-free rewrites; candidate text and reviewer guidance remain hash-only in receipts.",
  toolLoopGuard: "Tool loop guard",
  toolLoopGuardTitle: "Durable repetition breaker",
  toolLoopGuardKicker: "LEDGER-DERIVED · PRE-SIDE-EFFECT",
  toolLoopGuardEnabled: "Guard enabled",
  toolLoopGuardDisabled: "Guard disabled",
  toolLoopGuardThreshold: "Identical results",
  toolLoopGuardExemptTools: "Exempt tools",
  toolLoopGuardExemptPlaceholder: "web_search, status_check",
  toolLoopGuardBody:
    "After the same single-tool call returns the same result for the configured count, Napier injects a hash-only redirect. Repeating it again is blocked before execution; comma-separated exemptions remain revision-bound.",
  toolLoopGuardInvalid:
    "Use distinct comma-separated tool names containing only letters, digits, underscore, dot, colon, or hyphen.",
  recoveryShort: "Recovery",
  tools: "Workspace tools",
  toolLabels: {
    list_files: "List files",
    read_file: "Read file",
    search_files: "Search files",
    apply_patch: "Atomic patch",
    verify_workspace: "Sandbox verify",
  },
  skills: "Available skills",
  bundledSkill: "bundled skill",
  subagents: "Delegation roles",
  subagentLabels: {
    researcher: "Researcher",
    reviewer: "Reviewer",
    general: "Generalist",
  },
  runBudget: "Run budget",
  runMaxTurns: "Model turns",
  runMaxTokens: "Total tokens",
  runMaxCost: "Max cost (USD)",
  runTimeout: "Wall time (sec)",
  delegationBudget: "Delegation budget",
  maxConcurrent: "Concurrent",
  maxTotal: "Total / run",
  maxTurns: "Turns / task",
  timeout: "Timeout (sec)",
  saveProfile: "Save Agent profile",
  saving: "Saving profile...",
  profileSafety:
    "Changes are revisioned and recorded in the Work Ledger by field name only.",
  historyEyebrow: "CONFIGURATION LEDGER",
  history: "Revision history",
  historyBody:
    "Every semantic profile change is retained as a hash-bound snapshot. Rollback creates a new revision and never rewrites history.",
  historyLoading: "Loading configuration history...",
  currentRevision: "Current",
  reviewRollback: "Review rollback",
  rollbackTitle: "Restore historical configuration",
  rollbackBody:
    "Review the affected fields before restoring. The current revision remains immutable and the restored profile becomes a new revision.",
  rollbackTarget: "Target snapshot",
  rollbackResult: "New revision",
  rollbackChanges: "Fields to restore",
  rollbackMatches: "This snapshot already matches the current configuration.",
  confirmRollback: "Restore as new revision",
  rollingBack: "Restoring revision...",
  cancelRollback: "Cancel",
  profileDigest: "Profile SHA-256",
  promptDigest: "Prompt SHA-256",
  restoredFrom: "Restored from",
  legacyBaseline: "Legacy baseline",
  revisionSources: {
    created: "Created",
    updated: "Updated",
    rollback: "Rollback",
    imported: "Imported",
    migrated: "Migrated",
  },
  profileFields: {
    name: "Name",
    description: "Description",
    systemPrompt: "System prompt",
    model: "Model",
    thinkingLevel: "Thinking level",
    toolPolicy: "Tool policy",
    enabledTools: "Workspace tools",
    enabledSkills: "Skills",
    enabledSubagents: "Delegation roles",
    subagentLimits: "Delegation budget",
    runLimits: "Run budget",
    automaticRecovery: "Interruption policy",
    modelAdvisor: "Model Advisor",
    promptVariables: "Prompt variables",
    toolLoopGuard: "Tool loop guard",
  },
  promptPackageEyebrow: "SIGNED PROMPT BASELINE",
  promptPackage: "Prompt package",
  promptPackageBody:
    "Sign the current Agent revision as hash-only prompt provenance. The JSON envelope carries the System Prompt SHA-256, never the prompt text.",
  promptPackagePublisher: "Publisher",
  promptPackageDefaultPublisher: "Napier Prompt Registry",
  promptPackageSigner: "Local signer",
  promptPackageNoSigner: "No local signer",
  promptPackageSignerHint:
    "Register an Extension publisher with an environment-backed Ed25519 signer before signing Prompt packages.",
  promptSign: "Sign & download",
  promptVerify: "Verify JSON",
  promptQualify: "Qualify current Agent",
  promptPackageWorking: "Checking package...",
  promptPackageSigned:
    "Prompt package signed and downloaded. The envelope contains hashes and revision metadata only.",
  promptPackageTooLarge: "Prompt package JSON is too large.",
  promptPackageReceiptActions: {
    signed: "Signed",
    verified: "Verified",
    qualified: "Qualified",
  },
  promptPackageStatuses: {
    signed: "Signed",
    trusted: "Trusted",
    revoked: "Revoked",
    unknown_key: "Unknown key",
    expired: "Expired",
    invalid: "Invalid",
    qualified: "Qualified",
    prompt_drift: "Prompt drift",
    agent_missing: "Agent missing",
  },
  promptPackageManifestHash: "Manifest SHA-256",
  promptPackageEnvelopeHash: "Envelope SHA-256",
  promptPackageObservedPromptHash: "Observed prompt SHA-256",
  promptPackageKey: "Key SHA-256",
  promptPackageAgentRevision: "Signed revision",
  promptPackageObservedRevision: "Observed revision",
  skillPackageEyebrow: "SIGNED SKILL BASELINE",
  skillPackage: "Skill package",
  skillPackageBody:
    "Sign the selected Agent Skills as hash-only catalog provenance. Install records only a reviewed baseline; it never copies SKILL.md instructions.",
  skillPackageActive: "Active baseline",
  skillPackagePublisher: "Publisher",
  skillPackageDefaultPublisher: "Napier Skill Registry",
  skillPackageSigner: "Local signer",
  skillPackageNoSigner: "No local signer",
  skillPackageSignerHint:
    "Register an Extension publisher with an environment-backed Ed25519 signer before signing Skill packages.",
  skillSign: "Sign & download",
  skillVerify: "Verify JSON",
  skillQualify: "Qualify workspace",
  skillInstall: "Install baseline",
  skillPackageWorking: "Checking package...",
  skillPackageSigned:
    "Skill package signed and downloaded. The envelope contains hashes and Skill metadata only.",
  skillPackageInstalled:
    "Skill package baseline installed after local qualification.",
  skillPackageMatched:
    "This Skill package is already the active reviewed baseline.",
  skillPackageTooLarge: "Skill package JSON is too large.",
  skillPackageReplacementRequired:
    "Confirm replacement before installing a different Skill package baseline.",
  skillPackagePublisherChangeRequired:
    "Confirm publisher or key change before replacing the active Skill package baseline.",
  skillPackageSkillSetChangeRequired:
    "Confirm Skill set change before replacing the active Skill package baseline.",
  skillPackageReplaceConfirm:
    "Replace the active Skill package baseline if this package qualifies.",
  skillPackagePublisherChangeConfirm:
    "Allow a publisher or signing-key change for the replacement baseline.",
  skillPackageSkillSetChangeConfirm:
    "Allow the replacement baseline to change the loaded Skill set.",
  skillPackageReceiptActions: {
    signed: "Signed",
    verified: "Verified",
    qualified: "Qualified",
    installed: "Installed",
  },
  skillPackageStatuses: {
    signed: "Signed",
    trusted: "Trusted",
    revoked: "Revoked",
    unknown_key: "Unknown key",
    expired: "Expired",
    invalid: "Invalid",
    qualified: "Qualified",
    catalog_drift: "Catalog drift",
    missing_skill: "Missing Skill",
    installed: "Installed",
    matched: "Already active",
  },
  skillPackageManifestHash: "Manifest SHA-256",
  skillPackageEnvelopeHash: "Envelope SHA-256",
  skillPackageCatalogHash: "Catalog SHA-256",
  skillPackageObservedCatalogHash: "Observed catalog SHA-256",
  skillPackageKey: "Key SHA-256",
  skillPackageCount: "Skill count",
  skillPackageInstallation: "Installation",
  skillPackageReplaced: "Replaced",
  skillContentEyebrow: "REVIEWED SKILL CONTENT",
  skillContent: "Skill content install",
  skillContentBody:
    "Review a candidate SKILL.md body before writing it into skills/<name>/SKILL.md. The Work Ledger records hashes and path metadata only.",
  skillContentText: "Candidate SKILL.md",
  skillContentPlaceholder:
    "---\nname: research-brief\n---\n\n# Research Brief\n\nDescribe when this Skill should be used.",
  skillContentFile: "Load SKILL.md",
  skillContentPreview: "Preview hash",
  skillContentApply: "Apply reviewed write",
  skillContentWorking: "Reviewing Skill...",
  skillContentTooLarge: "Skill content must be 128 KiB or smaller.",
  skillContentNoReview: "Preview the candidate Skill content before applying.",
  skillContentInstallConfirmRequired:
    "Confirm installation before writing a new Skill file.",
  skillContentReplacementConfirmRequired:
    "Confirm replacement before overwriting the existing Skill file.",
  skillContentConfirmInstall:
    "Install this reviewed Skill content into the workspace.",
  skillContentConfirmReplacement:
    "Replace the existing Skill file with this reviewed content.",
  skillContentReviewReady:
    "Review hash is stable for the current candidate. Apply requires the same hash to be echoed back.",
  skillContentInstalled:
    "Skill content was written through the hash-preconditioned workspace writer.",
  skillContentReplaced:
    "Existing Skill content was replaced through the hash-preconditioned workspace writer.",
  skillContentNoop:
    "The candidate already matches the workspace file. No write is required.",
  skillContentActions: {
    install: "Install",
    replace: "Replace",
    noop: "No-op",
  },
  skillContentReceiptActions: {
    previewed: "Previewed",
    applied: "Applied",
  },
  skillContentSkill: "Skill",
  skillContentPath: "Target path",
  skillContentBytes: "Bytes",
  skillContentLines: "Lines",
  skillContentCurrentFootprint: "Current",
  skillContentCandidateFootprint: "Candidate",
  skillContentDelta: "Delta",
  skillContentNewFile: "new file",
  skillContentAppliedState: "Applied",
  skillContentAppliedYes: "yes",
  skillContentAppliedNo: "no",
  skillContentReviewHash: "Review SHA-256",
  skillContentCandidateHash: "Candidate SHA-256",
  skillContentFrontmatterHash: "Frontmatter SHA-256",
  skillContentBodyHash: "Body SHA-256",
  skillContentCurrentHash: "Current SHA-256",
  skillContentByteDelta: "Byte delta",
  skillContentLineDelta: "Line delta",
  credentialsEyebrow: "SECRET-FREE REFERENCES",
  credentials: "Provider credentials",
  provider: "Provider",
  source: "Reference source",
  environment: "Environment variable",
  keychain: "macOS Keychain",
  referenceLabel: "Reference label",
  referenceLabelPlaceholder: "Team OpenAI key",
  environmentVariable: "Environment variable name",
  environmentVariablePlaceholder: "OPENAI_API_KEY",
  keychainService: "Keychain service",
  keychainServicePlaceholder: "napier.openai",
  keychainAccount: "Keychain account",
  keychainAccountPlaceholder: "workspace",
  keychainSecret: "Write secret to Keychain",
  keychainSecretPlaceholder: "Leave blank to register an existing item",
  keychainReplace: "Replace existing Keychain item",
  addReference: "Register reference",
  noCredentials: "No credential references are registered.",
  credentialSafety:
    "Napier stores only the locator. Optional Keychain writes pass the secret to macOS once, then keep only service/account metadata.",
  credentialStatuses: {
    active: "Active",
    disabled: "Disabled",
  },
  credentialAvailability: {
    unknown: "Not checked",
    available: "Available",
    missing: "Unavailable",
    error: "Lookup error",
  },
  checkReference: "Check",
  enableReference: "Enable",
  disableReference: "Disable",
  workspace: "Workspace boundary",
  priceTable: "Usage price tables",
  priceTableEyebrow: "BUDGET CALIBRATION",
  priceTables: "tables",
  priceTableBody:
    "Provider cost estimates are bound to refreshable price-table hashes before they influence Run budget checks.",
  providers: "Providers",
  catalogHash: "Catalog",
  priceTableSafety:
    "Catalog verification rejects tampered table hashes, duplicate providers, and missing required providers before use.",
  checkpoint: "Evidence checkpoint",
  checkpointEyebrow: "COMPACTED CONTINUITY",
  calibration: "Checkpoint calibration",
  calibrationHash: "Calibration",
  coverage: "Coverage",
  coverageRate: "Coverage rate",
  compression: "Compression",
  fallbacks: "Failed / omitted",
  sourceHash: "Source",
  summaryHash: "Summary",
  decisions: "Decisions",
  openLoops: "Open loops",
  artifacts: "Artifacts",
  checkpointSafety:
    "The original ledger remains intact. This summary is treated as untrusted data and verified against its source-event hash before reuse.",
  calibrationSafety:
    "The calibration report is regenerated from ledger events and bound to a content hash.",
} as const;
