import type { LocaleOverride } from "./locale";
import type { contextCopyEn } from "./context-copy";

export const contextZh: LocaleOverride<typeof contextCopyEn> = {
  eyebrow: "运行时装配",
  title: "智能体上下文",
  revision: "修订版",
  nextRun: "下次运行",
  runModel: "运行模型",
  chooseModel: "为下次运行选择模型",
  runModelHint:
    "此选择会立即用于下次运行。保存下方配置后，它将成为智能体的默认模型。",
  modelUnavailableHint: "请先配置此提供商，再用于运行或保存为智能体默认模型。",
  unavailable: "不可用",
  profileEyebrow: "持久配置",
  profile: "智能体配置",
  name: "智能体名称",
  description: "说明",
  systemPrompt: "系统提示词",
  systemPromptHint: "作为配置保存；提示词正文不会复制到审计事件载荷中。",
  promptVariables: "提示词变量",
  promptVariablesTitle: "冻结的运行变量",
  promptVariablesKicker: "单次解析 · 哈希绑定",
  promptVariablesBody:
    "声明的标记在运行开始时只解析一次，值不会递归展开；账本仅保存值哈希、数量与渲染后系统提示词的 SHA-256。",
  promptVariablesEmpty:
    "尚未声明变量。未知的 {{tokens}} 会保持原样，并计入冻结的运行回执。",
  promptVariablesInvalid: "保存前请解决重复或无效名称，以及字面量容量限制。",
  promptVariableAdd: "添加变量",
  promptVariableIndex: "变量",
  promptVariableInsert: "插入到系统提示词",
  promptVariableRemove: "移除变量",
  promptVariableName: "标记名称",
  promptVariableNamePlaceholder: "project_context",
  promptVariableFallbackName: "变量",
  promptVariableType: "来源",
  promptVariableTypes: {
    literal: "字面值",
    current_date: "当前日期",
    skill_catalog: "技能目录",
  },
  promptVariableValue: "冻结值",
  promptVariableLiteralDefault: "值",
  promptVariableDateFormat: "日期格式",
  promptVariableDateFormats: {
    "readable-date": "YYYY-MM-DD，星期",
    "iso-date": "YYYY-MM-DD",
    "local-date-time": "本地日期、时间与时区",
  },
  promptVariableSkillCatalogBody:
    "注入本次运行实际加载且兼容 Pi 的精确目录；该目录不会被重复追加。",
  thinking: "思考级别",
  thinkingLevels: {
    off: "关闭",
    minimal: "最少",
    low: "低",
    medium: "中",
    high: "高",
  },
  policy: "工具策略",
  policies: {
    observe: "仅观察",
    workspace: "工作区操作",
    unrestricted: "不受限策略",
  },
  policyHint:
    "每次调用前都会即时检查授权。编辑需要最新 SHA-256，并可使用 read_file 行锚点；验证以只读、离线且无 Shell 的方式运行。",
  capabilityPreset: "能力预设",
  capabilityPresetKicker: "面向用户的名称 · 复用现有策略",
  capabilityPresetSelect: "任务模式",
  capabilityPresetCustom: "自定义配置",
  capabilityPresetBody:
    "预设只会填写现有策略、工具、技能与委派字段。保存智能体配置会创建常规修订版；除非策略明确允许，否则浏览器交互仍不可用。",
  capabilityContract: "默认能力契约",
  capabilityContractLoading: "正在加载有效能力契约……",
  capabilityContractUnavailable: "能力契约不可用。",
  capabilityContractBody:
    "此投影来自已保存的智能体修订版与运行时实际暴露的工具。安全升级会保留显式覆盖字段；完整恢复仅用于未托管或损坏的配置。每次变更都绑定下方显示的精确修订版与差异哈希。",
  capabilityConfigured: "已配置工具",
  capabilityExposed: "运行时已暴露",
  capabilityReadinessIssues: "就绪说明",
  capabilityExplicitOverrides: "显式覆盖字段",
  capabilityUpgradeDiff: "安全契约升级差异",
  capabilityRestoreDiff: "建议恢复差异",
  capabilityChanges: "项变更",
  capabilityNoChanges: "受管字段已经符合建议。",
  capabilityDiffHash: "精确差异 SHA-256",
  capabilityReadiness: "有效就绪状态",
  capabilityUpgradeConfirm:
    "我已核对此次精确升级；保留我的显式覆盖字段并创建新的智能体修订版。",
  capabilityRestoreConfirm:
    "我已核对此次完整恢复，并希望创建新的智能体修订版。",
  capabilityUpgrade: "保留覆盖并升级",
  capabilityUpgrading: "正在升级精确契约……",
  capabilityRestore: "恢复建议能力",
  capabilityRestoring: "正在恢复精确建议……",
  capabilityConflictRefreshed:
    "预览已变化。权威投影已加载；请核对新修订版和差异后再次确认。",
  capabilityConflictRefreshFailed:
    "预览已变化且自动刷新失败。请重新打开上下文页面后重试。",
  capabilityTools: "工具",
  capabilityBrowserRead: "浏览器读取",
  capabilityBrowserInteract: "浏览器交互",
  capabilityYes: "是",
  capabilityNo: "否",
  recoveryPolicy: "中断策略",
  recoveryTitle: "安全自动恢复",
  recoveryKicker: "快照绑定 · 失败即关闭",
  recoveryMode: "恢复模式",
  recoveryModes: {
    manual: "仅手动恢复",
    safe_read_only: "自动 · 安全只读",
  },
  recoveryAttempts: "最大尝试次数",
  recoveryBackoff: "基础延迟（秒）",
  recoverySafeBody:
    "仅当 schema-2 中断运行不存在未解决工具、写入、未知副作用或导入来源时才可继续。子运行使用冻结的智能体修订版，且只暴露本地读取工具。",
  recoveryManualBody:
    "中断的运行会等待操作者处理。始终可以手动恢复，并明确警告先前工具结果可能未知。",
  modelAdvisor: "模型顾问",
  modelAdvisorMode: "顾问模式",
  modelAdvisorModes: {
    observe: "观察并记录",
    enforce: "遇阻断项即关闭",
    off: "关闭",
  },
  modelAdvisorRules: "顾问规则",
  modelAdvisorRuleLabels: {
    unverified_verification_claim: "未经验证的检查",
    destructive_command_reference: "危险命令",
  },
  modelAdvisorCorrectionAttempts: "纠正次数",
  modelAdvisorReviewModel: "独立审查模型",
  modelAdvisorReviewModelDisabled: "仅确定性规则",
  modelAdvisorReviewModelPrimary: "主模型",
  modelAdvisorReviewModelUnavailableHint:
    "请选择已配置且不同于主运行模型的在线模型。",
  modelAdvisorBody:
    "候选输出在展示前会经过检查，也可由独立的零工具模型审查。强制阻断项共享最多三次无工具重写；候选文本与审查指导仅以哈希形式保留在回执中。",
  toolLoopGuard: "工具循环防护",
  toolLoopGuardTitle: "持久化重复中断器",
  toolLoopGuardKicker: "账本推导 · 副作用前执行",
  toolLoopGuardEnabled: "已启用防护",
  toolLoopGuardDisabled: "已停用防护",
  toolLoopGuardThreshold: "相同结果次数",
  toolLoopGuardExemptTools: "豁免工具",
  toolLoopGuardExemptPlaceholder: "web_search, status_check",
  toolLoopGuardBody:
    "同一个单工具调用连续达到配置次数且结果相同时，Napier 会注入仅含哈希的改道提示；再次重复会在执行前被阻止。逗号分隔的豁免项与修订版绑定。",
  toolLoopGuardInvalid:
    "请使用互不重复、以逗号分隔的工具名；仅允许字母、数字、下划线、点、冒号或连字符。",
  recoveryShort: "恢复",
  tools: "智能体工具",
  toolLabels: {
    list_files: "列出文件",
    read_file: "读取文件",
    search_files: "搜索文件",
    list_symbols: "列出符号",
    inspect_data: "检查数据",
    data_frame: "数据表",
    sqlite_query: "SQLite 查询",
    git_inspect: "检查 Git",
    git_stage_preview: "预览 Git 暂存",
    git_stage_apply: "应用 Git 暂存",
    git_commit_preview: "预览 Git 提交",
    git_commit_apply: "应用 Git 提交",
    git_branch_create_preview: "预览创建 Git 分支",
    git_branch_create_apply: "创建 Git 分支",
    git_branch_switch_preview: "预览切换 Git 分支",
    git_branch_switch_apply: "切换 Git 分支",
    git_review_preview: "预览 Git 审查",
    git_review_apply: "推进 Git 审查",
    inspect_code: "检查代码",
    read_symbol: "读取符号",
    ast_query: "AST 查询",
    ast_edit_preview: "AST 编辑预览",
    lsp_diagnostics: "LSP 诊断",
    lsp_symbols: "LSP 语义符号",
    lsp_definition: "LSP 定义",
    lsp_references: "LSP 引用",
    lsp_rename: "LSP 重命名预览",
    lsp_rename_apply: "应用 LSP 重命名",
    lsp_code_actions: "LSP 快速修复",
    lsp_code_action_apply: "应用 LSP 快速修复",
    apply_patch: "原子补丁",
    workspace_file_preview: "文件生命周期预览",
    workspace_file_apply: "应用文件生命周期",
    run_command: "沙箱命令",
    javascript_kernel: "JavaScript 内核",
    python_kernel: "Python 内核",
    node_debugger: "Node 调试器",
    workspace_process: "后台进程",
    web_search: "网页搜索",
    web_fetch: "网页获取",
    web_fetch_save: "保存网页获取结果",
    browser: "浏览器会话",
    research_source: "研究来源",
    skill_load: "加载项目技能",
    capability: "能力目录",
    verify_workspace: "沙箱验证",
  },
  skills: "可用技能",
  bundledSkill: "内置技能",
  skillSources: {
    bundled: "内置",
    workspace: "工作区",
    user: "用户",
  },
  subagents: "委派角色",
  subagentLabels: {
    researcher: "研究员",
    reviewer: "审查员",
    general: "通用智能体",
    coder: "开发者",
  },
  runBudget: "运行预算",
  runMaxTurns: "模型轮次",
  runMaxTokens: "总 Token",
  runMaxCost: "最高成本（美元）",
  runTimeout: "总时限（秒）",
  delegationBudget: "委派预算",
  maxConcurrent: "并发数",
  maxTotal: "每次运行总数",
  maxTurns: "每项任务轮次",
  timeout: "超时（秒）",
  saveProfile: "保存智能体配置",
  saving: "正在保存配置……",
  profileSafety: "变更按修订版保存，工作账本仅记录字段名称。",
  historyEyebrow: "配置账本",
  history: "修订历史",
  historyBody:
    "每次语义配置变更都保留为哈希绑定快照。回滚会创建新修订版，绝不改写历史。",
  historyLoading: "正在加载配置历史……",
  currentRevision: "当前版本",
  reviewRollback: "核对回滚",
  rollbackTitle: "恢复历史配置",
  rollbackBody:
    "恢复前请核对受影响字段。当前修订版保持不可变，恢复后的配置会成为新修订版。",
  rollbackTarget: "目标快照",
  rollbackResult: "新修订版",
  rollbackChanges: "待恢复字段",
  rollbackMatches: "此快照已与当前配置一致。",
  confirmRollback: "恢复为新修订版",
  rollingBack: "正在恢复修订版……",
  cancelRollback: "取消",
  profileDigest: "配置 SHA-256",
  promptDigest: "提示词 SHA-256",
  restoredFrom: "恢复来源",
  legacyBaseline: "旧版基线",
  revisionSources: {
    created: "已创建",
    updated: "已更新",
    rollback: "回滚",
    imported: "已导入",
    migrated: "已迁移",
  },
  profileFields: {
    name: "名称",
    description: "说明",
    systemPrompt: "系统提示词",
    model: "模型",
    thinkingLevel: "思考级别",
    toolPolicy: "工具策略",
    enabledTools: "工作区工具",
    enabledSkills: "技能",
    enabledSubagents: "委派角色",
    subagentLimits: "委派预算",
    runLimits: "运行预算",
    automaticRecovery: "中断策略",
    modelAdvisor: "模型顾问",
    promptVariables: "提示词变量",
    toolLoopGuard: "工具循环防护",
    modelRoute: "模型路由",
  },
  promptPackageEyebrow: "已签名提示词基线",
  promptPackage: "提示词包",
  promptPackageBody:
    "将当前智能体修订版签名为仅含哈希的提示词来源。JSON 信封只携带系统提示词 SHA-256，绝不包含提示词正文。",
  promptPackagePublisher: "发布方",
  promptPackageDefaultPublisher: "Napier 提示词注册表",
  promptPackageSigner: "本地签名方",
  promptPackageNoSigner: "没有本地签名方",
  promptPackageSignerHint:
    "签名提示词包前，请先注册带有环境变量 Ed25519 签名器的扩展发布方。",
  promptSign: "签名并下载",
  promptVerify: "验证 JSON",
  promptQualify: "校验当前智能体",
  promptPackageWorking: "正在检查提示词包……",
  promptPackageSigned: "提示词包已签名并下载。信封仅包含哈希与修订版元数据。",
  promptPackageTooLarge: "提示词包 JSON 过大。",
  promptPackageReceiptActions: {
    signed: "已签名",
    verified: "已验证",
    qualified: "已校验",
  },
  promptPackageStatuses: {
    signed: "已签名",
    trusted: "可信",
    revoked: "已撤销",
    unknown_key: "未知密钥",
    expired: "已过期",
    invalid: "无效",
    qualified: "已校验",
    prompt_drift: "提示词漂移",
    agent_missing: "智能体缺失",
  },
  promptPackageManifestHash: "清单 SHA-256",
  promptPackageEnvelopeHash: "信封 SHA-256",
  promptPackageObservedPromptHash: "观测到的提示词 SHA-256",
  promptPackageKey: "密钥 SHA-256",
  promptPackageAgentRevision: "已签名修订版",
  promptPackageObservedRevision: "观测到的修订版",
  skillPackageEyebrow: "已签名技能基线",
  skillPackage: "技能包",
  skillPackageBody:
    "将所选智能体技能签名为仅含哈希的目录来源。安装只记录经核对的基线，绝不复制 SKILL.md 指令。",
  skillPackageActive: "当前基线",
  skillPackagePublisher: "发布方",
  skillPackageDefaultPublisher: "Napier 技能注册表",
  skillPackageSigner: "本地签名方",
  skillPackageNoSigner: "没有本地签名方",
  skillPackageSignerHint:
    "签名技能包前，请先注册带有环境变量 Ed25519 签名器的扩展发布方。",
  skillSign: "签名并下载",
  skillVerify: "验证 JSON",
  skillQualify: "校验工作区",
  skillInstall: "安装基线",
  skillPackageWorking: "正在检查技能包……",
  skillPackageSigned: "技能包已签名并下载。信封仅包含哈希与技能元数据。",
  skillPackageInstalled: "技能包基线已通过本地校验并安装。",
  skillPackageMatched: "此技能包已经是当前已核对基线。",
  skillPackageTooLarge: "技能包 JSON 过大。",
  skillPackageReplacementRequired: "安装不同技能包基线前，请确认替换。",
  skillPackagePublisherChangeRequired:
    "替换当前技能包基线前，请确认发布方或密钥变更。",
  skillPackageSkillSetChangeRequired:
    "替换当前技能包基线前，请确认技能集合变更。",
  skillPackageReplaceConfirm: "若此技能包通过校验，则替换当前基线。",
  skillPackagePublisherChangeConfirm: "允许替换基线更改发布方或签名密钥。",
  skillPackageSkillSetChangeConfirm: "允许替换基线更改已加载技能集合。",
  skillPackageReceiptActions: {
    signed: "已签名",
    verified: "已验证",
    qualified: "已校验",
    installed: "已安装",
  },
  skillPackageStatuses: {
    signed: "已签名",
    trusted: "可信",
    revoked: "已撤销",
    unknown_key: "未知密钥",
    expired: "已过期",
    invalid: "无效",
    qualified: "已校验",
    catalog_drift: "目录漂移",
    missing_skill: "技能缺失",
    installed: "已安装",
    matched: "已是当前版本",
  },
  skillPackageManifestHash: "清单 SHA-256",
  skillPackageEnvelopeHash: "信封 SHA-256",
  skillPackageCatalogHash: "目录 SHA-256",
  skillPackageObservedCatalogHash: "观测到的目录 SHA-256",
  skillPackageKey: "密钥 SHA-256",
  skillPackageCount: "技能数量",
  skillPackageInstallation: "安装信息",
  skillPackageReplaced: "被替换版本",
  skillContentEyebrow: "已核对技能内容",
  skillContent: "安装技能内容",
  skillContentBody:
    "写入 skills/<name>/SKILL.md 前，请核对候选 SKILL.md 正文。工作账本只记录哈希与路径元数据。",
  skillContentText: "候选 SKILL.md",
  skillContentPlaceholder:
    "---\nname: research-brief\n---\n\n# 研究简报\n\n说明应在什么情况下使用此 Skill。",
  skillContentFile: "加载 SKILL.md",
  skillContentPreview: "预览哈希",
  skillContentApply: "应用已核对写入",
  skillContentWorking: "正在核对技能……",
  skillContentTooLarge: "技能内容不得超过 128 KiB。",
  skillContentNoReview: "应用前请先预览候选技能内容。",
  skillContentInstallConfirmRequired: "写入新技能文件前，请确认安装。",
  skillContentReplacementConfirmRequired: "覆盖现有技能文件前，请确认替换。",
  skillContentConfirmInstall: "将此已核对技能内容安装到工作区。",
  skillContentConfirmReplacement: "使用此已核对内容替换现有技能文件。",
  skillContentReviewReady:
    "当前候选内容的核对哈希稳定；应用时必须回传同一哈希。",
  skillContentInstalled: "技能内容已通过带哈希前置条件的工作区写入器写入。",
  skillContentReplaced: "现有技能内容已通过带哈希前置条件的工作区写入器替换。",
  skillContentNoop: "候选内容已与工作区文件一致，无需写入。",
  skillContentActions: {
    install: "安装",
    replace: "替换",
    noop: "无需操作",
  },
  skillContentReceiptActions: {
    previewed: "已预览",
    applied: "已应用",
  },
  skillContentSkill: "技能",
  skillContentPath: "目标路径",
  skillContentBytes: "字节数",
  skillContentLines: "行数",
  skillContentCurrentFootprint: "当前内容",
  skillContentCandidateFootprint: "候选内容",
  skillContentDelta: "差异",
  skillContentNewFile: "新文件",
  skillContentAppliedState: "应用状态",
  skillContentAppliedYes: "是",
  skillContentAppliedNo: "否",
  skillContentReviewHash: "核对 SHA-256",
  skillContentCandidateHash: "候选内容 SHA-256",
  skillContentFrontmatterHash: "前置元数据 SHA-256",
  skillContentBodyHash: "正文 SHA-256",
  skillContentCurrentHash: "当前内容 SHA-256",
  skillContentByteDelta: "字节差异",
  skillContentLineDelta: "行数差异",
  credentialsEyebrow: "无密钥引用",
  credentials: "提供商凭证",
  provider: "提供商",
  source: "引用来源",
  environment: "环境变量",
  keychain: "macOS 钥匙串",
  referenceLabel: "引用名称",
  referenceLabelPlaceholder: "团队 OpenAI 密钥",
  environmentVariable: "环境变量名称",
  keychainService: "钥匙串服务",
  keychainAccount: "钥匙串账户",
  keychainSecret: "将密钥写入钥匙串",
  keychainSecretPlaceholder: "留空可注册已有项目",
  keychainReplace: "替换现有钥匙串项目",
  addReference: "注册引用",
  environmentVariablePlaceholder: "OPENAI_API_KEY",
  keychainServicePlaceholder: "napier.openai",
  keychainAccountPlaceholder: "workspace",
  noCredentials: "尚未注册凭证引用。",
  credentialSafety:
    "Napier 只保存定位信息。可选的钥匙串写入会将密钥一次性交给 macOS，随后仅保留服务和账户元数据。",
  credentialStatuses: {
    active: "已启用",
    disabled: "已停用",
  },
  credentialAvailability: {
    unknown: "尚未检查",
    available: "可用",
    missing: "不可用",
    error: "查询失败",
  },
  checkReference: "检查",
  enableReference: "启用",
  disableReference: "停用",
  workspace: "工作区边界",
  priceTable: "用量价格表",
  priceTableEyebrow: "预算校准",
  priceTables: "张价格表",
  priceTableBody:
    "提供商成本估算会绑定可刷新的价格表哈希，之后才影响运行预算检查。",
  providers: "提供商",
  catalogHash: "目录",
  priceTableSafety:
    "使用前会验证目录，拒绝被篡改的价格表哈希、重复提供商和缺失的必需提供商。",
  checkpoint: "证据检查点",
  checkpointEyebrow: "压缩连续性",
  calibration: "检查点校准",
  calibrationHash: "校准信息",
  coverage: "覆盖情况",
  coverageRate: "覆盖率",
  compression: "压缩比",
  fallbacks: "失败或省略",
  sourceHash: "来源",
  summaryHash: "摘要",
  decisions: "决策",
  openLoops: "未决事项",
  artifacts: "产物",
  checkpointSafety:
    "原始账本保持完整。此摘要按不可信数据处理，复用前会对照来源事件哈希验证。",
  calibrationSafety: "校准报告由账本事件重新生成，并绑定内容哈希。",
};
