import { deepMergeCopy, getLocale, type LocaleOverride } from "./locale";

export const conversationDetailCopyEn = {
  subagent: {
    label: "Subagent",
    model: "Model",
    turns: "Turns",
    steps: "Steps",
    usage: "Usage",
    tokens: "tokens",
    outcome: "Outcome",
    items: "items",
    evidence: "evidence",
    unknown: "unknown",
    risk: "Risk",
    blocker: "blocker",
    warning: "warning",
    stop: "Stop",
    outcomeSummary: "Outcome summary",
    detailsHidden: "details hidden",
    runningGuidance: "The delegated task is running independently.",
    emptyGuidance: "No structured outcome was recorded.",
    failurePrefix: "Delegation",
    failureSeparator: ". ",
    failureGuidance: "Inspect Trace for private diagnostics.",
    statuses: {
      pending: "Pending",
      running: "Running",
      completed: "Completed",
      failed: "Failed",
      cancelled: "Cancelled",
      timed_out: "Timed out",
    },
    roles: {
      researcher: "Researcher",
      reviewer: "Reviewer",
      general: "General",
      coder: "Coder",
    },
    stopReasons: {
      completed: "Completed",
      turn_capped: "Turn limit reached",
      timeout: "Timed out",
      cancelled: "Cancelled",
      error: "Error",
    },
    outcomeKinds: {
      finding: "Finding",
      risk: "Risk",
      recommendation: "Recommendation",
    },
  },
  artifact: {
    current: "Current",
    previous: "Previous",
    label: "Artifact",
    type: "Type",
    size: "Size",
    digest: "Digest",
    opening: "Opening…",
    preview: "Preview",
    downloading: "Downloading…",
    download: "Download",
    lines: "lines",
    previewLabel: "Preview",
    closePreview: "Close preview",
    statuses: {
      expected: "Expected",
      candidate: "Candidate",
      produced: "Produced",
      verified: "Verified",
      missing: "Missing",
      superseded: "Superseded",
    },
    kinds: {
      file: "File",
      directory: "Directory",
      url: "URL",
      other: "Other",
    },
  },
  citation: {
    label: "Citation",
    webEvidence: "Web source evidence",
    browserEvidence: "Browser source evidence",
    source: "Source",
    lines: "Lines",
    capture: "Capture",
    title: "Title",
    quote: "Quote",
    claim: "Claim",
    guidance:
      "Evidence binding only — source authority and claim sufficiency still require review.",
  },
  recovery: {
    label: "Retry",
    mode: "Mode",
    evidence: "Evidence",
    events: "events",
    tools: "tools",
    readOnly: "Read only",
    risk: "Risk",
    unsafe: "unsafe",
    unknown: "unknown",
    unresolved: "unresolved",
    stop: "Stop",
    sourceRun: "Source Run",
    receipt: "Receipt",
    traceGuidance:
      "The structured outcome is shown; private diagnostics remain in Trace.",
    activeGuidance:
      "Napier is reopening durable evidence without replaying side effects.",
    completedGuidance:
      "The continuation completed from a verified read-only boundary.",
    statuses: {
      skipped: "Blocked",
      claimed: "Claimed",
      running: "Running",
      completed: "Completed",
      failed: "Failed",
      cancelled: "Cancelled",
      interrupted: "Interrupted",
      abandoned: "Abandoned",
    },
    summaries: {
      skipped: "Automatic recovery stopped safely",
      completed: "Interrupted work recovered",
      claimed: "Recovery lease claimed",
      running: "Restoring from verified evidence",
      interrupted: "Recovery Run was interrupted",
      abandoned: "Recovery claim was abandoned",
      cancelled: "Recovery Run was cancelled",
      failed: "Recovery attempt failed",
    },
    modes: {
      manual: "Manual",
      safe_read_only: "Safe read only",
    },
    settlement: {
      timeout: "Timeout",
      turns: "Turn limit",
      tokens: "Token limit",
      cost: "Cost limit",
      minutes: "m",
      seconds: "s",
    },
    blockReasons: {
      configuration_missing: "Run configuration evidence is missing.",
      legacy_configuration: "Legacy schema has no bound recovery policy.",
      policy_manual: "The frozen Agent policy requires manual Resume.",
      run_not_interrupted: "The source Run is not interrupted.",
      workflow_managed: "The source Run is resumed by its Workflow Plan.",
      demo_model: "The demo model cannot verify current state.",
      event_limit_exceeded: "The evidence range exceeds the safety limit.",
      unresolved_tool_call: "A tool start has no unique terminal outcome.",
      unsafe_tool_effect: "A write or delegated side effect was observed.",
      unknown_tool_effect: "A tool effect is not proven read-only.",
      attempt_limit_reached: "The frozen attempt limit is exhausted.",
      untrusted_recovery_chain: "The recovery chain is not trusted.",
    },
  },
} as const;

export const conversationDetailZh: LocaleOverride<
  typeof conversationDetailCopyEn
> = {
  subagent: {
    label: "子智能体",
    model: "模型",
    turns: "轮次",
    steps: "步骤",
    usage: "用量",
    tokens: "令牌",
    outcome: "结果",
    items: "项",
    evidence: "条证据",
    unknown: "项未知",
    risk: "风险",
    blocker: "个阻断项",
    warning: "个警告",
    stop: "停止原因",
    outcomeSummary: "结果摘要",
    detailsHidden: "详情已隐藏",
    runningGuidance: "委派任务正在独立运行。",
    emptyGuidance: "未记录结构化结果。",
    failurePrefix: "委派任务",
    failureSeparator: "。",
    failureGuidance: "私有诊断信息请在追踪中查看。",
    statuses: {
      pending: "待处理",
      running: "运行中",
      completed: "已完成",
      failed: "失败",
      cancelled: "已取消",
      timed_out: "已超时",
    },
    roles: {
      researcher: "研究",
      reviewer: "审查",
      general: "通用",
      coder: "编码",
    },
    stopReasons: {
      completed: "已完成",
      turn_capped: "已达到轮次上限",
      timeout: "已超时",
      cancelled: "已取消",
      error: "发生错误",
    },
    outcomeKinds: {
      finding: "发现",
      risk: "风险",
      recommendation: "建议",
    },
  },
  artifact: {
    current: "当前",
    previous: "先前",
    label: "产物",
    type: "类型",
    size: "大小",
    digest: "摘要",
    opening: "正在打开…",
    preview: "预览",
    downloading: "正在下载…",
    download: "下载",
    lines: "行",
    previewLabel: "预览",
    closePreview: "关闭预览",
    statuses: {
      expected: "预期",
      candidate: "候选",
      produced: "已产出",
      verified: "已验证",
      missing: "缺失",
      superseded: "已替代",
    },
    kinds: {
      file: "文件",
      directory: "目录",
      url: "网址",
      other: "其他",
    },
  },
  citation: {
    label: "引用",
    webEvidence: "网页来源证据",
    browserEvidence: "浏览器来源证据",
    source: "来源",
    lines: "行号",
    capture: "内容快照",
    title: "标题",
    quote: "引文",
    claim: "主张",
    guidance: "此处仅证明证据绑定关系；来源权威性与主张充分性仍需审查。",
  },
  recovery: {
    label: "恢复",
    mode: "模式",
    evidence: "证据",
    events: "个事件",
    tools: "个工具调用",
    readOnly: "只读调用",
    risk: "风险",
    unsafe: "个不安全",
    unknown: "个效果未知",
    unresolved: "个未解决",
    stop: "停止原因",
    sourceRun: "来源运行",
    receipt: "回执",
    traceGuidance: "结构化结果已显示；私有诊断信息仍保留在追踪中。",
    activeGuidance: "Napier 正在从持久证据恢复，且不会重放副作用。",
    completedGuidance: "已从经过验证的只读边界完成后续执行。",
    statuses: {
      skipped: "已阻止",
      claimed: "已认领",
      running: "运行中",
      completed: "已完成",
      failed: "失败",
      cancelled: "已取消",
      interrupted: "已中断",
      abandoned: "已放弃",
    },
    summaries: {
      skipped: "自动恢复已安全停止",
      completed: "已恢复中断的工作",
      claimed: "已认领恢复租约",
      running: "正在从已验证证据恢复",
      interrupted: "恢复运行已中断",
      abandoned: "恢复认领已放弃",
      cancelled: "恢复运行已取消",
      failed: "恢复尝试失败",
    },
    modes: {
      manual: "手动",
      safe_read_only: "安全只读",
    },
    settlement: {
      timeout: "超时",
      turns: "轮次上限",
      tokens: "令牌上限",
      cost: "费用上限",
      minutes: "分",
      seconds: "秒",
    },
    blockReasons: {
      configuration_missing: "缺少运行配置证据。",
      legacy_configuration: "旧版数据结构未绑定恢复策略。",
      policy_manual: "冻结的智能体策略要求手动恢复。",
      run_not_interrupted: "来源运行并未中断。",
      workflow_managed: "来源运行由其工作流计划负责恢复。",
      demo_model: "演示模型无法验证当前状态。",
      event_limit_exceeded: "证据范围超出安全上限。",
      unresolved_tool_call: "工具调用开始后没有唯一的终态结果。",
      unsafe_tool_effect: "检测到写入或委派产生的副作用。",
      unknown_tool_effect: "无法证明工具效果为只读。",
      attempt_limit_reached: "已用尽冻结的尝试次数。",
      untrusted_recovery_chain: "恢复链不可信。",
    },
  },
};

export const conversationDetailCopy = deepMergeCopy(
  conversationDetailCopyEn,
  getLocale() === "zh" ? conversationDetailZh : {},
);
