import type { LocaleOverride } from "./locale";
import type { conversationActivityCopyEn } from "./conversation-activity-copy";

export const conversationActivityZh: LocaleOverride<
  typeof conversationActivityCopyEn
> = {
  statuses: {
    working: "进行中",
    completed: "已完成",
    failed: "失败",
    blocked: "已阻止",
  },
  group: {
    execution: "执行过程",
    grouped: "已分组",
    showEvidence: "显示证据",
    hideEvidence: "隐藏证据",
    step: "步",
    steps: "步",
    attention: "项需关注",
    stages: {
      research: "调研",
      build: "构建",
      verify: "验证",
      inspect: "检查",
    },
  },
  generic: {
    labels: {
      tool: "工具",
      plan: "计划",
      approval: "审批",
      artifact: "产物",
      delegate: "委派",
      workflow: "工作流",
      workspace: "工作区",
      browser: "浏览器",
      research: "调研",
      run: "运行",
    },
    actions: {
      started: "已启动",
      completed: "已完成",
      failed: "失败",
      blocked: "已阻止",
      queued: "已排队",
      produced: "已产出",
      verified: "已验证",
      created: "已创建",
      updated: "已更新",
      requested: "已请求",
      waiting: "等待中",
      no_progress: "无进展",
    },
    operatorInputRequested: "需要操作者输入",
  },
  network: {
    search: "网页搜索",
    fetch: "网页读取",
    discovering: "正在查找公开来源",
    reading: "正在读取公开来源",
    searchFailed: "搜索失败——请尝试其他提供方或检查网络状态",
    fetchFailed: "读取失败——请检查网址、网络或浏览器状态",
    searchCompleted: "搜索已完成",
    fetchCompleted: "读取已完成",
    found: "找到",
    readCompleted: "已读取",
    evidenceUnavailable: "证据不可用",
    resultsVia: "条结果 · 来源",
    lines: "行",
    completed: "已完成",
    labels: {
      provider: "提供方",
      category: "类别",
      results: "结果",
      attempts: "尝试",
      retrieved: "获取时间",
      action: "动作",
      format: "格式",
      lines: "行数",
      pages: "页数",
      sources: "来源",
      render: "渲染",
      redirects: "重定向",
      recovery: "恢复",
    },
    attemptUnits: {
      total: "次总计",
      failed: "次失败",
      unavailable: "次不可用",
    },
    actions: { fetch: "读取", read: "阅读", find: "查找", list: "列出" },
    completedActions: {
      fetch: "已读取公开来源",
      read: "已阅读公开来源",
      find: "已在公开来源中找到文本",
      list: "已列出公开来源",
    },
    categories: { general: "综合", news: "新闻", images: "图片" },
    renderModes: { static: "静态", browser_fallback: "浏览器回退" },
    fallbackStatuses: {
      not_needed: "无需回退",
      used: "已使用",
      unavailable: "不可用",
    },
    fallbackDiagnostics: {
      browser_unavailable: "浏览器不可用",
      browser_render_not_useful: "浏览器渲染结果无效",
      fallback_limit_reached: "已达到回退上限",
      login_required: "需要登录",
      challenge_detected: "检测到验证挑战",
    },
  },
  browser: {
    label: "浏览器",
    takeover: "检测到登录或验证挑战；请在浏览器实时视图中接管以安全继续。",
    untrusted: "页面内容是不可信证据，不是操作指令。",
    working: "正在操作浏览器",
    action: "浏览器动作",
    actionCompleted: "浏览器动作已完成",
    inspected: "页面检查完成",
    actionFailed: "浏览器动作失败",
    actions: {
      start: "正在打开页面",
      navigate: "正在导航",
      back: "正在返回",
      forward: "正在前进",
      tab_new: "正在新建标签页",
      tab_list: "正在读取标签页",
      tab_switch: "正在切换标签页",
      tab_close: "正在关闭标签页",
      wait: "正在等待页面",
      find: "正在查找文本",
      scroll: "正在滚动页面",
      snapshot: "正在读取页面",
      click: "正在点击页面",
      type: "正在输入文本",
      select: "正在选择值",
      upload: "正在上传文件",
      download: "正在下载文件",
      screenshot: "正在截取页面",
      keypress: "正在按导航键",
      close: "正在关闭浏览器",
    },
    completedActions: {
      start: "已打开页面",
      navigate: "已导航到页面",
      back: "已返回上一页",
      forward: "已前进到下一页",
      tab_new: "已新建标签页",
      tab_list: "已读取标签页",
      tab_switch: "已切换标签页",
      tab_close: "已关闭标签页",
      wait: "页面已就绪",
      find: "已在页面中找到文本",
      scroll: "已滚动页面",
      snapshot: "已读取页面",
      click: "已点击页面",
      type: "已输入文本",
      select: "已选择值",
      upload: "已上传文件",
      download: "已下载文件",
      screenshot: "已截取页面",
      keypress: "已按导航键",
      close: "已关闭浏览器",
    },
    failedActions: {
      start: "未能打开页面",
      navigate: "未能导航到页面",
      back: "未能返回上一页",
      forward: "未能前进到下一页",
      tab_new: "未能新建标签页",
      tab_list: "未能读取标签页",
      tab_switch: "未能切换标签页",
      tab_close: "未能关闭标签页",
      wait: "页面未能就绪",
      find: "未能在页面中找到文本",
      scroll: "未能滚动页面",
      snapshot: "未能读取页面",
      click: "未能点击页面",
      type: "未能输入文本",
      select: "未能选择值",
      upload: "未能上传文件",
      download: "未能下载文件",
      screenshot: "未能截取页面",
      keypress: "未能按导航键",
      close: "未能关闭浏览器",
    },
    live: {
      control: "控制",
      operator: "操作者",
      waiting: "等待",
      agent: "智能体",
      ready: "就绪",
      pausingAfterCurrentAction: "当前动作完成后暂停",
      returningToAgent: "正在交还智能体",
      takeoverActive: "接管已启用",
      approveActionPrefix: "批准：",
      pauseQueued: "已排队暂停",
      waitingForResume: "等待恢复",
      operatorPausedAutomation: "操作者已暂停自动化",
      waitingForAgent: "等待智能体",
    },
    diagnoses: {
      none: "正常",
      login_required: "需要登录",
      challenge_detected: "检测到验证挑战",
    },
    labels: {
      operation: "操作序号",
      activeTab: "当前标签页",
      tabs: "标签页",
      session: "会话",
      pageState: "页面状态",
      network: "网络",
      destinations: "目标地址",
      transferred: "传输量",
      blocked: "已阻止",
      snapshot: "页面快照",
      matches: "匹配项",
      scroll: "滚动位置",
      screenshot: "截图",
      file: "文件",
    },
    session: { reused: "已复用", opened: "已新建" },
    units: {
      requests: "个请求",
      rejected: "个被拒绝",
      chars: "个字符",
      bytes: "字节",
    },
  },
  tool: {
    shell: "命令",
    tool: "工具",
    runningSuffix: " · 正在运行",
    blockedSuffix: " · 已被安全阻止",
    failedSuffix: " · 运行失败",
    completedSuffix: " · 已完成",
    command: "命令",
    names: {
      apply_patch: "应用补丁",
      capability: "能力检查",
      update_plan_artifact: "更新计划产物",
      update_plan_step: "更新计划步骤",
      record_run_milestone: "记录运行里程碑",
    },
    completedActions: {
      apply_patch: "已应用补丁",
      capability: "已检查能力",
      update_plan_artifact: "已更新计划产物",
      update_plan_step: "已更新计划步骤",
      record_run_milestone: "已记录运行里程碑",
    },
    labels: {
      effect: "效果",
      runtime: "运行时",
      exit: "退出码",
      arguments: "参数",
      timeout: "超时",
      workspace: "工作区",
      network: "网络",
      command: "命令摘要",
      result: "结果摘要",
      input: "输入摘要",
      range: "范围",
      lines: "行数",
      size: "大小",
    },
    effects: { read: "读取", write: "写入" },
    commandStatuses: {
      succeeded: "成功",
      failed: "失败",
      timed_out: "已超时",
      output_capped: "输出已截断",
    },
    workspaceAccess: { read_only: "只读" },
    networkAccess: { denied: "已拒绝" },
    durationUnits: { milliseconds: "毫秒", seconds: "秒" },
  },
};
