import { deepMergeCopy, getLocale } from "./locale";
import { conversationActivityZh } from "./conversation-activity-copy.zh";

export const conversationActivityCopyEn = {
  statuses: {
    working: "Working",
    completed: "Completed",
    failed: "Failed",
    blocked: "Blocked",
  },
  group: {
    execution: "Execution",
    grouped: "grouped",
    showEvidence: "Show evidence",
    hideEvidence: "Hide evidence",
    step: "step",
    steps: "steps",
    attention: "need attention",
    stages: {
      research: "Research",
      build: "Build",
      verify: "Verify",
      inspect: "Inspect",
    },
  },
  generic: {
    labels: {
      tool: "Tool",
      plan: "Plan",
      approval: "Approval",
      artifact: "Artifact",
      delegate: "Delegate",
      workflow: "Workflow",
      workspace: "Workspace",
      browser: "Browser",
      research: "Research",
      run: "Run",
    },
    actions: {
      started: "Started",
      completed: "Completed",
      failed: "Failed",
      blocked: "Blocked",
      queued: "Queued",
      produced: "Produced",
      verified: "Verified",
      created: "Created",
      updated: "Updated",
      requested: "Requested",
      waiting: "Waiting",
      no_progress: "No progress",
    },
    operatorInputRequested: "Operator input requested",
  },
  network: {
    search: "Web search",
    fetch: "Web fetch",
    discovering: "Discovering public sources",
    reading: "Reading public source",
    searchFailed:
      "Search failed — try another provider or check network readiness",
    fetchFailed: "Fetch failed — check the URL, network, or Browser readiness",
    searchCompleted: "Search completed",
    fetchCompleted: "Fetch completed",
    found: "Found",
    readCompleted: "Read",
    evidenceUnavailable: "evidence unavailable",
    resultsVia: "results via",
    lines: "lines",
    completed: "completed",
    labels: {
      provider: "Provider",
      category: "Category",
      results: "Results",
      attempts: "Attempts",
      retrieved: "Retrieved",
      action: "Action",
      format: "Format",
      lines: "Lines",
      pages: "Pages",
      sources: "Sources",
      render: "Render",
      redirects: "Redirects",
      recovery: "Recovery",
    },
    attemptUnits: {
      total: "total",
      failed: "failed",
      unavailable: "unavailable",
    },
    actions: { fetch: "Fetch", read: "Read", find: "Find", list: "List" },
    completedActions: {
      fetch: "Fetched public source",
      read: "Read public source",
      find: "Found text in public source",
      list: "Listed public sources",
    },
    categories: { general: "General", news: "News", images: "Images" },
    renderModes: { static: "Static", browser_fallback: "Browser fallback" },
    fallbackStatuses: {
      not_needed: "Not needed",
      used: "Used",
      unavailable: "Unavailable",
    },
    fallbackDiagnostics: {
      browser_unavailable: "Browser unavailable",
      browser_render_not_useful: "Browser render not useful",
      fallback_limit_reached: "Fallback limit reached",
      login_required: "Login required",
      challenge_detected: "Challenge detected",
    },
  },
  browser: {
    label: "Browser",
    takeover:
      "Login or challenge detected. Take over in Browser Live view to continue safely.",
    untrusted: "Page content is untrusted evidence, not instructions.",
    working: "Working in Browser",
    action: "Browser action",
    actionCompleted: "Browser action completed",
    inspected: "Page inspected",
    actionFailed: "Browser action failed",
    actions: {
      start: "Opening page",
      navigate: "Navigating",
      back: "Going back",
      forward: "Going forward",
      tab_new: "Opening tab",
      tab_list: "Reading tabs",
      tab_switch: "Switching tab",
      tab_close: "Closing tab",
      wait: "Waiting for page",
      find: "Finding text",
      scroll: "Scrolling page",
      snapshot: "Reading page",
      click: "Clicking page",
      type: "Entering text",
      select: "Choosing values",
      upload: "Uploading file",
      download: "Downloading file",
      screenshot: "Capturing screenshot",
      keypress: "Pressing navigation key",
      close: "Closing Browser",
    },
    completedActions: {
      start: "Opened page",
      navigate: "Navigated to page",
      back: "Went back",
      forward: "Went forward",
      tab_new: "Opened tab",
      tab_list: "Read open tabs",
      tab_switch: "Switched tab",
      tab_close: "Closed tab",
      wait: "Page became ready",
      find: "Found text on page",
      scroll: "Scrolled page",
      snapshot: "Read page",
      click: "Clicked page",
      type: "Entered text",
      select: "Selected values",
      upload: "Uploaded file",
      download: "Downloaded file",
      screenshot: "Captured screenshot",
      keypress: "Pressed navigation key",
      close: "Closed Browser",
    },
    failedActions: {
      start: "Could not open page",
      navigate: "Could not navigate to page",
      back: "Could not go back",
      forward: "Could not go forward",
      tab_new: "Could not open tab",
      tab_list: "Could not read open tabs",
      tab_switch: "Could not switch tab",
      tab_close: "Could not close tab",
      wait: "Page did not become ready",
      find: "Could not find text on page",
      scroll: "Could not scroll page",
      snapshot: "Could not read page",
      click: "Could not click page",
      type: "Could not enter text",
      select: "Could not select values",
      upload: "Could not upload file",
      download: "Could not download file",
      screenshot: "Could not capture screenshot",
      keypress: "Could not press navigation key",
      close: "Could not close Browser",
    },
    live: {
      control: "Control",
      operator: "Operator",
      waiting: "Waiting",
      agent: "Agent",
      ready: "Ready",
      pausingAfterCurrentAction: "pausing after current action",
      returningToAgent: "returning to Agent",
      takeoverActive: "takeover active",
      approveActionPrefix: "approve ",
      pauseQueued: "pause queued",
      waitingForResume: "waiting for resume",
      operatorPausedAutomation: "operator paused automation",
      waitingForAgent: "waiting for Agent",
    },
    diagnoses: {
      none: "Normal",
      login_required: "Login required",
      challenge_detected: "Challenge detected",
    },
    labels: {
      operation: "Operation",
      activeTab: "Active tab",
      tabs: "Tabs",
      session: "Session",
      pageState: "Page state",
      network: "Network",
      destinations: "Destinations",
      transferred: "Transferred",
      blocked: "Blocked",
      snapshot: "Snapshot",
      matches: "Matches",
      scroll: "Scroll",
      screenshot: "Screenshot",
      file: "File",
    },
    session: { reused: "Reused", opened: "Opened" },
    units: {
      requests: "requests",
      rejected: "rejected",
      chars: "chars",
      bytes: "bytes",
    },
  },
  tool: {
    shell: "Shell",
    tool: "Tool",
    runningSuffix: " is running",
    blockedSuffix: " was blocked safely",
    failedSuffix: " failed",
    completedSuffix: " completed",
    command: "Command",
    names: {
      apply_patch: "Apply patch",
      capability: "Capability check",
      update_plan_artifact: "Update plan artifact",
      update_plan_step: "Update plan step",
      record_run_milestone: "Record run milestone",
    },
    completedActions: {
      apply_patch: "Applied patch",
      capability: "Checked capability",
      update_plan_artifact: "Updated plan artifact",
      update_plan_step: "Updated plan step",
      record_run_milestone: "Recorded run milestone",
    },
    labels: {
      effect: "Effect",
      runtime: "Runtime",
      exit: "Exit",
      arguments: "Arguments",
      timeout: "Timeout",
      workspace: "Workspace",
      network: "Network",
      command: "Command",
      result: "Result",
      input: "Input",
      range: "Range",
      lines: "Lines",
      size: "Size",
    },
    effects: { read: "Read", write: "Write" },
    commandStatuses: {
      succeeded: "Succeeded",
      failed: "Failed",
      timed_out: "Timed out",
      output_capped: "Output capped",
    },
    workspaceAccess: { read_only: "Read only" },
    networkAccess: { denied: "Denied" },
    durationUnits: { milliseconds: "ms", seconds: "s" },
  },
} as const;

export const conversationActivityCopy = deepMergeCopy(
  conversationActivityCopyEn,
  getLocale() === "zh" ? conversationActivityZh : {},
);
