export const copy = {
  appName: "Napier",
  appDescriptor: "Agent work ledger",
  newThread: "New ledger",
  recentThreads: "Ledgers",
  noThreads: "No ledgers yet",
  workspace: "Local workspace",
  localFirst: "Local-first",
  inspect: "Inspect",
  branch: "Branch here",
  stop: "Stop run",
  running: "Running",
  waiting: "Interrupted",
  idle: "Ready",
  failed: "Needs review",
  composerPlaceholder: "Give Napier a task, question, or durable goal...",
  send: "Run",
  shortcut: "⌘ ↵",
  tabs: {
    trace: "Trace",
    lab: "Lab",
    plan: "Plan",
    goal: "Goal",
    memory: "Memory",
    extensions: "Extend",
    automations: "Ops",
    context: "Context",
  },
  automationLoading: "Opening automation register...",
  extensionLoading: "Opening capability registry...",
  trace: {
    title: "Run evidence",
    empty: "Events will appear here as the run unfolds.",
    sequence: "SEQ",
    otel: {
      eyebrow: "VENDOR-NEUTRAL TRACE",
      title: "OpenTelemetry export",
      body: "Project this ledger into OTLP/JSON spans for Collector, Jaeger, Tempo, or another compatible backend.",
      scope: "Export scope",
      threadScope: "Complete Thread",
      runScope: "Single Run",
      export: "Export OTLP trace",
      exporting: "Binding spans...",
      exported: "OTLP trace exported",
      verify: "Verify archived JSON",
      verifying: "Checking archive...",
      verified: "OTLP trace verified",
      invalid: "OTLP trace invalid",
      noDiagnostics: "No diagnostics",
      spans: "Spans",
      events: "Events",
      safety:
        "Metadata-only export excludes prompts, completions, reasoning, tool I/O, notes, evidence text, and credential locators.",
      errors: {
        artifactTooLarge: "OTLP trace artifact is larger than 10 MiB.",
        artifactInvalid: "OTLP trace artifact must be valid JSON.",
      },
    },
  },
  lab: {
    eyebrow: "RUN LAB",
    title: "Compare evidence",
    count: "settled runs",
    empty: "Complete at least two runs to open a comparison.",
    baseline: "Baseline",
    candidate: "Candidate",
    selectRun: "Select a run",
    compare: "Compare",
    evaluate: "Evaluate",
    comparing: "Comparing...",
    evaluating: "Evaluating...",
    export: "Export replay",
    metricDelta: "Candidate delta",
    eventDelta: "Event delta",
    output: "Final output",
    changed: "Changed",
    unchanged: "Unchanged",
    duration: "Duration",
    events: "Events",
    tokens: "Tokens",
    tools: "Tool calls",
    cost: "Cost",
    noDelta: "No event-type differences.",
    configuration: "Configuration drift",
    configurationChanged: "Changed",
    configurationUnchanged: "Unchanged",
    configurationUnavailableShort: "Unavailable",
    configurationUnavailable:
      "One or both Runs predate configuration fingerprints. Drift is unknown.",
    configurationFields: {
      agentRevision: "Agent revision",
      model: "Model",
      systemPrompt: "System prompt",
      thinkingLevel: "Thinking level",
      toolPolicy: "Tool policy",
      enabledTools: "Workspace tools",
      enabledSkills: "Skills",
      enabledSubagents: "Subagents",
      subagentLimits: "Delegation limits",
      runLimits: "Run limits",
      automaticRecovery: "Recovery policy",
      executionMode: "Execution mode",
      skillCatalog: "Skill catalog",
    },
    verdict: "Independent verdict",
    noVerdict: "No evaluation has been recorded for this pair.",
    evidence: "Evaluator evidence",
    rubric: "Rubric scores",
    left: "L",
    right: "R",
    hashes: "Evidence hashes",
    demoNotice:
      "The demo model records an inconclusive verdict. Choose a configured live model for independent scoring.",
    safety:
      "Evaluators receive immutable snapshots, no tools, and untrusted ledger evidence. Verdicts bind to both event-stream hashes.",
    fixture: {
      eyebrow: "THREAD FIXTURE",
      title: "Portable ledger",
      body: "Carry the complete Thread, Agent revisions, Runs, plans, evaluations, human adjudications, reviewer consensus, quality gates, subagents, and ordered evidence as one replay fixture.",
      events: "events",
      runs: "runs",
      plans: "plans",
      evaluations: "evaluations",
      importedSource: "Imported source SHA-256",
      export: "Export full ledger",
      exporting: "Binding fixture...",
      verify: "Verify fixture",
      verifying: "Checking fixture...",
      import: "Import fixture",
      importing: "Importing fixture...",
      noDiagnostics: "No diagnostics",
      safety:
        "Both content and event-stream hashes are verified. Imported in-flight work is closed with an unknown outcome.",
      receipts: {
        exported: "Fixture exported",
        imported: "Fixture imported",
        verified: "Fixture verified",
        invalid: "Fixture invalid",
      },
    },
    replay: {
      eyebrow: "RUN REPLAY",
      title: "Snapshot verifier",
      body: "Verify an archived per-Run replay JSON against the active Thread boundary before using it for evidence review or CI regression checks.",
      verify: "Verify replay JSON",
      verifying: "Checking replay...",
      verified: "Replay verified",
      invalid: "Replay invalid",
      subagents: "subagents",
    },
    trust: {
      eyebrow: "TRUSTED PROVENANCE",
      title: "Receipt trust desk",
      body: "Bind release evidence to an Ed25519 identity, retain public trust anchors, and verify signed receipts without trusting their transport.",
      anchors: "Trust anchors",
      empty: "No receipt trust anchor is registered.",
      add: "Add trust anchor",
      adding: "Reading key...",
      label: "Anchor label",
      labelPlaceholder: "Release signing identity",
      source: "Anchor source",
      environment: "Local signer · environment",
      publicKey: "Verify only · public key",
      environmentVariable: "PKCS#8 private-key environment variable",
      publicKeySpki: "SPKI public key · Base64 DER",
      publicKeyPlaceholder: "MCowBQYDK2VwAyEA…",
      signing: "Local signing",
      verifyOnly: "Verify only",
      revoke: "Revoke",
      confirmRevoke: "Confirm revoke",
      cancel: "Cancel revocation",
      verifier: "Offline envelope verifier",
      verifierBody:
        "Deep-check payload hashes, signature statement, Ed25519 signature, and current anchor state.",
      chooseReceipt: "Verify signed JSON",
      verifying: "Verifying envelope...",
      statuses: {
        trusted: "Trusted",
        revoked: "Revoked",
      },
      verificationStatuses: {
        trusted: "Trusted origin",
        revoked: "Valid · key revoked",
        unknown_key: "Unknown signer",
        invalid: "Invalid envelope",
      },
      safety:
        "Private keys are read only at signing time from the named environment variable. SQLite and Ledger events retain public keys, fingerprints, and evidence hashes only.",
      errors: {
        tooLarge: "Trusted receipt files must be 10 MiB or smaller.",
      },
    },
    calibration: {
      eyebrow: "HUMAN TRUTH",
      title: "Evaluator calibration",
      body: "Append reviewed verdicts to immutable model judgments, then measure exact agreement within each evaluator and rubric cohort.",
      reviewed: "Reviewed",
      agreement: "Exact agreement",
      groups: "Calibration cohorts",
      samples: "samples",
      noSamples:
        "No human truth has been recorded. Review an evaluation to establish the first calibration sample.",
      register: "Evaluation review register",
      registerHint:
        "Current truth is append-only; revising a verdict preserves every prior review.",
      unreviewed: "Awaiting review",
      agreed: "Agreed",
      disagreed: "Diverged",
      modelVerdict: "Model verdict",
      expectedVerdict: "Expected verdict",
      review: "Review",
      revise: "Revise truth",
      save: "Record truth",
      saving: "Binding review...",
      cancel: "Cancel",
      note: "Review note",
      notePlaceholder: "State the evidence behind this human judgment.",
      revision: "Truth revision",
      evaluator: "Evaluator",
      rubric: "Rubric",
      reportHash: "Report SHA-256",
      matrix: "Verdict confusion matrix",
      modelAxis: "Model",
      truthAxis: "Truth",
      verdictMarks: {
        left_better: "L",
        right_better: "R",
        tie: "T",
        inconclusive: "I",
      },
      consensus: {
        open: "Panel review",
        provenance: "Panel consensus",
        eyebrow: "INDEPENDENT SIGN-OFF",
        title: "Reviewer consensus",
        close: "Close panel",
        body: "Keep each reviewer in an independent append-only lane. Preview applies quorum and agreement policy without changing Human Truth.",
        roster: "Reviewer lanes",
        emptyRoster: "No independent ballot has been recorded.",
        reviewerId: "Reviewer lane ID",
        reviewerIdPlaceholder: "release_owner",
        reviewerName: "Display name",
        reviewerNamePlaceholder: "Release owner",
        ballotNote: "Private ballot rationale",
        ballotNotePlaceholder:
          "State the evidence behind this independent verdict.",
        clear: "Clear lane",
        record: "Record ballot",
        recording: "Binding ballot...",
        gate: "Consensus policy",
        minimumReviewers: "Minimum reviewers",
        minimumAgreement: "Minimum agreement",
        allowInconclusive: "Allow inconclusive consensus",
        preview: "Preview consensus",
        previewing: "Computing...",
        resolve: "Resolve as truth",
        resolving: "Binding truth...",
        noLeader: "No unique leader",
        agreement: "panel agreement",
        previewRequired:
          "Preview the current lanes after changing consensus policy.",
        latestResolution: "Latest resolution",
        statuses: {
          ready: "Ready to resolve",
          insufficient_reviewers: "More reviewers required",
          no_consensus: "No consensus",
          inconclusive: "Inconclusive blocked",
        },
        safety:
          "Resolution is explicit and atomic. Ballot notes stay out of Ledger events; the resulting Human Truth revision binds the consensus report SHA-256.",
      },
      empty: "Run an evaluation to create a reviewable judgment.",
      safety:
        "Human truth never overwrites model output. Every revision binds the immutable evaluation SHA-256 and remains portable with the Thread fixture.",
    },
    casebook: {
      eyebrow: "REGRESSION ARCHIVE",
      title: "Evaluation Casebooks",
      body: "Curate reviewed judgments from many Threads into append-only, hash-bound gold sets for workspace-level evaluator calibration.",
      select: "Casebook volume",
      empty: "No Evaluation Casebook has been created.",
      create: "New Casebook",
      creating: "Creating volume...",
      save: "Save metadata",
      saving: "Binding revision...",
      edit: "Edit metadata",
      cancel: "Cancel",
      name: "Casebook name",
      namePlaceholder: "Release evaluator gold set",
      description: "Scope note",
      descriptionPlaceholder:
        "Define what belongs in this reviewed evidence collection.",
      currentRevision: "Current revision",
      cases: "Gold cases",
      agreement: "Agreement",
      cohorts: "Cohorts",
      curate: "Curate reviewed evaluation",
      curateAction: "Add case",
      refreshAction: "Refresh truth",
      curating: "Binding case...",
      noReviewed:
        "This Thread has no human-reviewed evaluation available for curation.",
      upToDate: "Current truth already curated",
      source: "Source",
      modelVerdict: "Model",
      expectedVerdict: "Truth",
      truthRevision: "Truth revision",
      caseHash: "Case SHA-256",
      evaluationHash: "Evaluation SHA-256",
      consensusEvidence: "Panel evidence",
      remove: "Remove from current revision",
      confirmRemove: "Confirm removal",
      removing: "Removing case...",
      history: "Revision ledger",
      export: "Export Casebook",
      exporting: "Binding artifact...",
      reportHash: "Calibration SHA-256",
      samples: "samples",
      safety:
        "Removing or refreshing a case creates a new Casebook revision. Prior revisions retain their exact evaluation, truth, provenance, and hashes.",
      qualification: {
        eyebrow: "EXECUTABLE GOLD SET",
        title: "Evaluator qualification",
        body: "Re-judge the current manifest with a selected evaluator. Every source Run is rebuilt and checked against its frozen snapshot hashes before scoring.",
        evaluator: "Candidate evaluator",
        minimumAgreement: "Minimum exact agreement",
        allowInconclusive: "Permit verified inconclusive judgments",
        run: "Qualify evaluator",
        running: "Replaying gold set...",
        neverRun: "Not run",
        agreement: "Agreement",
        verified: "Verified evidence",
        inconclusive: "Inconclusive",
        executionHash: "Execution SHA",
        expected: "Expected",
        actual: "Actual",
        expectedLeft: "Expected L",
        observedLeft: "Observed L",
        expectedRight: "Expected R",
        observedRight: "Observed R",
        unavailable: "unavailable",
        empty:
          "No qualification is bound to this revision. Run the current gold set to create one.",
        noCases: "Curate at least one reviewed case before qualification.",
        history: "Qualification history",
        current: "Current revision",
        stale: "Prior revision",
        receipt: "Qualification receipt",
        exportingReceipt: "Binding receipt...",
        signedReceipt: "Signed receipt",
        exportingSignedReceipt: "Signing receipt...",
        promoteBaseline: "Promote baseline",
        promotingBaseline: "Pinning baseline...",
        noSigner: "Register and select a local signing anchor first.",
        baseline: "Trusted qualification baseline",
        noBaseline: "No signed baseline has been promoted.",
        baselineCurrent: "Current and trusted",
        baselineStale: "Stale Casebook revision",
        baselineRevoked: "Signer revoked",
        baselineHash: "Baseline SHA",
        signer: "Signer key",
        statuses: {
          passed: "Qualified",
          failed: "Below gate",
          inconclusive: "Inconclusive",
        },
        caseStatuses: {
          agreed: "Agreed",
          disagreed: "Diverged",
          inconclusive: "Inconclusive",
        },
        evidenceStates: {
          verified: "Source hashes verified",
          drifted: "Source evidence drifted",
          missing: "Source evidence missing",
        },
      },
      revisionSources: {
        created: "Created",
        metadata_updated: "Metadata",
        case_curated: "Case curated",
        case_refreshed: "Truth refreshed",
        case_removed: "Case removed",
      },
    },
    suite: {
      eyebrow: "QUALITY GATE",
      title: "Evaluation suites",
      body: "Replay one baseline against a bounded candidate register with a revisioned rubric and deterministic gate.",
      create: "Create suite",
      update: "Save revision",
      edit: "Edit",
      cancel: "Cancel",
      run: "Run gate",
      running: "Evaluating batch...",
      receipt: "Gate receipt",
      exportingReceipt: "Binding receipt...",
      signedReceipt: "Signed receipt",
      exportingSignedReceipt: "Signing receipt...",
      name: "Suite name",
      namePlaceholder: "Release quality gate",
      baseline: "Baseline run",
      candidates: "Candidate register",
      candidatesHint: "Select 1–8 settled Runs.",
      passRate: "Minimum non-regression",
      candidateScore: "Minimum candidate score",
      allowInconclusive: "Allow partial inconclusive cases",
      evaluator: "Evaluator",
      empty: "No durable evaluation suite has been created.",
      revision: "Revision",
      latest: "Latest gate",
      neverRun: "Not run",
      average: "Candidate mean",
      cases: "Cases",
      digest: "Batch SHA-256",
      caseEvidence: "Case evidence",
      baselineScore: "Baseline",
      candidateScoreShort: "Candidate",
      pairDigest: "Pair SHA-256",
      history: "Execution history",
      safety:
        "Every case uses immutable Run snapshots and the no-tool evaluator. Pair, batch, and receipt hashes bind the complete gate evidence.",
      statuses: {
        passed: "Passed",
        failed: "Failed",
        inconclusive: "Inconclusive",
      },
      errors: {
        candidates: "Select at least one candidate distinct from baseline.",
        maximum: "Evaluation suites accept at most 8 candidates.",
      },
    },
    verdicts: {
      left_better: "Baseline better",
      right_better: "Candidate better",
      tie: "Tie",
      inconclusive: "Inconclusive",
    },
    statuses: {
      completed: "Completed",
      failed: "Failed",
      cancelled: "Cancelled",
      interrupted: "Interrupted",
    },
    errors: {
      distinct: "Choose two distinct settled runs.",
      replayTooLarge: "Run replay snapshots must be 10 MiB or smaller.",
      replayInvalid: "Choose a valid Napier Run replay snapshot JSON file.",
      fixtureTooLarge: "Replay fixtures must be 10 MiB or smaller.",
      fixtureInvalid: "Choose a valid Napier replay fixture JSON file.",
    },
  },
  plan: {
    eyebrow: "EXECUTION MAP",
    title: "Durable plan",
    count: "plans",
    empty:
      "Ask a live model to create a plan for multi-step work. Every transition will settle in the ledger.",
    objective: "Objective",
    progress: "Progress",
    criticalPath: "Critical path",
    readyPath: "Ready",
    blockedPath: "Blocked",
    replan: "Latest replan",
    replanSignal: "Replan signal",
    draft: "Draft",
    reviewDraft: "Review draft",
    reviewingDraft: "Reviewing",
    applyDraft: "Apply draft",
    applyingDraft: "Applying",
    modelReview: "Model review",
    score: "Score",
    risk: "Risk",
    hash: "Hash",
    response: "Response",
    reviewVerdicts: {
      approve: "Approve",
      revise: "Revise",
      reject: "Reject",
      inconclusive: "Inconclusive",
    },
    replanRisks: {
      low: "Low",
      medium: "Medium",
      high: "High",
    },
    replanStrategies: {
      recover_blocked: "Blocked recovery",
      scope_change: "Scope change",
      artifact_drift: "Artifact drift",
    },
    next: "Run next step",
    nextPrompt:
      "Continue the durable execution plan. Start the next ready step, perform it, verify its stated condition, and settle the step with concrete evidence before moving on.",
    noReady: "No step is currently ready to run.",
    none: "None",
    dependsOn: "Depends on",
    verification: "Verification",
    evidence: "Evidence",
    blocker: "Blocker",
    artifacts: "Artifact manifest",
    digest: "SHA-256",
    source: "Source run",
    archive: {
      eyebrow: "PLAN ARCHIVE",
      title: "Workflow archive",
      body: "Export the current durable plan, replan ledger, artifact manifest, and plan-scoped evidence events as one hash-bound workflow record.",
      export: "Export archive",
      exporting: "Binding archive...",
      verify: "Verify archive",
      verifying: "Checking archive...",
      exported: "Archive exported",
      verified: "Archive verified",
      invalid: "Archive invalid",
      noDiagnostics: "No diagnostics",
      events: "events",
      steps: "steps",
      artifacts: "artifacts",
      replans: "replans",
      eventStream: "Event stream",
      safety:
        "Archive verification is no-store and path-bound to the active Thread and Plan. Hashes cover the plan projection and ordered plan evidence events.",
      errors: {
        tooLarge: "Plan archives must be 10 MiB or smaller.",
        invalid: "Choose a valid Napier Plan archive JSON file.",
      },
    },
    blueprint: {
      eyebrow: "WORKFLOW BLUEPRINT",
      title: "Reusable plan",
      body: "Distill a settled plan into a reusable DAG: objective, steps, dependencies, artifact declarations, and source hashes without runtime evidence prose.",
      export: "Export blueprint",
      exporting: "Binding blueprint...",
      verify: "Verify blueprint",
      verifying: "Checking blueprint...",
      create: "Create plan",
      creating: "Creating plan...",
      exported: "Blueprint exported",
      verified: "Blueprint verified",
      invalid: "Blueprint invalid",
      created: "Plan created",
      noDiagnostics: "No diagnostics",
      steps: "steps",
      artifacts: "artifacts",
      safety:
        "Blueprint verification is no-store. Creating a plan replays the normal Plan creation gate and records only blueprint/source hashes in Ledger events.",
      library: {
        eyebrow: "BLUEPRINT LIBRARY",
        title: "Template shelf",
        body: "Keep verified workflow blueprints as local reusable templates, replay them into durable Plans, and audit current delivery outcomes without trusting the original transport.",
        refresh: "Refresh library",
        refreshing: "Reading library...",
        save: "Save verified",
        saving: "Saving template...",
        select: "Select best",
        selecting: "Selecting...",
        calibrate: "Calibrate",
        calibrating: "Calibrating...",
        backtestPolicy: "Backtest policies",
        backtestingPolicy: "Backtesting...",
        applyPolicyOverride: "Apply top policy",
        applyingPolicyOverride: "Applying policy...",
        reviewPolicyOverrideDrift: "Review override drift",
        reviewingPolicyOverrideDrift: "Reviewing drift...",
        create: "Create from template",
        creating: "Creating plan...",
        preview: "Preview",
        previewing: "Previewing...",
        history: "Export history",
        loadingHistory: "Exporting...",
        verifyHistory: "Verify history",
        verifyingHistory: "Verifying...",
        outcomes: "Export outcomes",
        loadingOutcomes: "Binding outcomes...",
        verifyOutcomes: "Verify outcomes",
        verifyingOutcomes: "Verifying outcomes...",
        promoteOutcomeBaseline: "Promote baseline",
        promotingOutcomeBaseline: "Promoting...",
        promoteReviewedOutcomeBaseline: "Promote reviewed",
        promotingReviewedOutcomeBaseline: "Promoting reviewed...",
        qualifyOutcomes: "Qualify outcomes",
        qualifyingOutcomes: "Qualifying outcomes...",
        reviewOutcomes: "Review outcomes",
        reviewingOutcomes: "Reviewing outcomes...",
        qualify: "Qualify",
        qualifying: "Checking...",
        archive: "Archive",
        archiving: "Archiving...",
        restore: "Restore",
        restoring: "Restoring...",
        empty: "No reusable workflow templates have been saved yet.",
        noVerified:
          "Export or verify a blueprint first, then save it into the library.",
        locked:
          "Creating from a template is locked while this Thread has an active or blocked Plan.",
        records: "templates",
        replays: "replays",
        threads: "threads",
        plans: "plans",
        completed: "completed",
        blocked: "blocked",
        cancelled: "cancelled",
        invalid: "invalid",
        active: "active",
        archived: "archived",
        candidates: "candidates",
        families: "families",
        qualified: "qualified",
        rejected: "rejected",
        reviewed: "reviewed",
        missing: "missing",
        policyFailed: "policy failed",
        selected: "Selected",
        score: "Score",
        risk: "Risk",
        input: "Input",
        response: "Response",
        review: "Review",
        source: "Source",
        shape: "Shape",
        updated: "Updated",
        expected: "Expected",
        actual: "Actual",
        declared: "Declared",
        observed: "Observed",
        eventSet: "Event set",
        replayHistory: "Replay history",
        outcomeSet: "Outcome set",
        outcomeBaseline: "Outcome baseline",
        selectionSet: "Selection set",
        portfolioSet: "Portfolio set",
        policySet: "Policy set",
        overrideSet: "Override set",
        driftReviewSet: "Drift review set",
        recommendationPolicy: "Policy",
        overridePolicy: "Override policy",
        bestPolicy: "Best policy",
        recommendation: "Recommendation",
        recommendedRetire: "Retire recommended",
        aligned: "Aligned",
        policySource: "Source",
        override: "Override",
        policies: "policies",
        divergent: "divergent",
        average: "Average",
        topFamily: "Top family",
        completion: "Completion",
        current: "Current",
        min: "Min",
        latest: "Latest",
        eventAnchor: "Replay event",
        eventVerified: "Replay event verified",
        eventInvalid: "Replay event invalid",
        eventVerification: "Verification",
        latestPreview: "Latest preview",
        noDiagnostics: "No diagnostics",
        statuses: {
          active: "Active",
          archived: "Archived",
        },
        qualificationStatuses: {
          qualified: "Source qualified",
          archived: "Template archived",
          source_missing: "Source missing",
          source_drift: "Source drift",
          invalid: "Template invalid",
        },
        previewStatuses: {
          ready: "Plan preview ready",
          not_qualified: "Preview blocked",
          blocked: "Open plan exists",
        },
        verificationStatuses: {
          valid: "History verified",
          invalid: "History invalid",
        },
        outcomeVerificationStatuses: {
          valid: "Outcomes verified",
          invalid: "Outcomes invalid",
        },
        outcomeQualificationStatuses: {
          qualified: "Outcome baseline qualified",
          missing_baseline: "Outcome baseline missing",
          policy_failed: "Outcome policy failed",
        },
        outcomeReviewVerdicts: {
          promote: "Outcome review promoted",
          revise: "Outcome review needs revision",
          reject: "Outcome review rejected",
          inconclusive: "Outcome review inconclusive",
        },
        outcomeReviewRisks: {
          low: "Low",
          medium: "Medium",
          high: "High",
        },
        outcomeStatuses: {
          active: "Active",
          completed: "Completed",
          blocked: "Blocked",
          cancelled: "Cancelled",
          plan_missing: "Plan missing",
          identity_mismatch: "Identity mismatch",
        },
        receipts: {
          saved: "Template saved",
          reused: "Template reused",
          archived: "Template archived",
          restored: "Template restored",
          created: "Plan created",
          history: "Replay history",
          outcomes: "Replay outcomes",
          outcomeBaseline: "Outcome baseline",
          selection: "Template selection",
          portfolioCalibrated: "Portfolio calibration",
          policyBacktested: "Policy backtest",
          policyOverrideApplied: "Policy override applied",
          policyOverrideDriftReviewed: "Policy override drift",
        },
        outcomeBaselineCreated: "Baseline promoted",
        outcomeBaselineReused: "Baseline already current",
        safety:
          "Saved templates retain hash-only source evidence. Outcome receipts bind current Plan projections without exposing objective, path, blocker, or evidence prose.",
        errors: {
          tooLarge: "Replay history receipts must be 2 MiB or smaller.",
          invalid: "Choose a valid Napier blueprint replay history JSON file.",
          outcomesTooLarge: "Replay outcome receipts must be 2 MiB or smaller.",
          outcomesInvalid:
            "Choose a valid Napier blueprint replay outcomes JSON file.",
        },
      },
      errors: {
        tooLarge: "Plan blueprints must be 2 MiB or smaller.",
        invalid: "Choose a valid Napier Plan blueprint JSON file.",
      },
    },
    statuses: {
      active: "Active",
      completed: "Completed",
      blocked: "Blocked",
      cancelled: "Cancelled",
      pending: "Pending",
      ready: "Ready",
      running: "Running",
      skipped: "Skipped",
      expected: "Expected",
      produced: "Produced",
      verified: "Verified",
      missing: "Missing",
      superseded: "Superseded",
    },
    safety:
      "Steps settle only with explicit evidence. File verification hashes actual workspace bytes; interrupted running steps become blocked with an unknown outcome.",
  },
  delegation: {
    eyebrow: "DELEGATION LEDGER",
    title: "Isolated tasks",
    prompt: "Task brief",
    result: "Returned evidence",
    error: "Failure record",
    turns: "Turns",
    steps: "Steps",
    statuses: {
      pending: "Queued",
      running: "Working",
      completed: "Complete",
      failed: "Failed",
      cancelled: "Cancelled",
      timed_out: "Timed out",
    },
  },
  goal: {
    title: "Durable goal",
    empty: "Set an objective that can span multiple runs.",
    placeholder: "Define a verifiable outcome...",
    set: "Set goal",
    clear: "Clear",
    active: "Active",
    completed: "Verified",
    blocked: "Blocked",
    evidence: "Latest evidence",
    noProgress: "No progress",
    guardrail: "Napier fails closed when evidence is insufficient.",
  },
  memory: {
    title: "Reviewed memory",
    eyebrow: "CONTEXT VAULT",
    loading: "Opening reviewed memory...",
    empty: "No memories have been proposed yet.",
    proposed: "Awaiting review",
    active: "Active context",
    history: "Review history",
    stale: "Review queue",
    placeholder:
      "Record a durable fact, preference, constraint, or decision...",
    correctionPlaceholder:
      "Rewrite the fact so the corrected version can replace it...",
    consolidationPlaceholder:
      "Write one complete fact that preserves the selected source evidence...",
    draftLabel: "Memory proposal",
    correctionDraftLabel: "Corrected memory proposal",
    consolidationDraftLabel: "Consolidated memory proposal",
    categoryLabel: "Memory category",
    scopeLabel: "Memory scope",
    add: "Propose memory",
    proposeCorrection: "Propose correction",
    proposeConsolidation: "Propose consolidation",
    approve: "Approve",
    reject: "Reject",
    archive: "Archive",
    restore: "Restore",
    refresh: "Refresh",
    markStale: "Mark stale",
    correct: "Correct",
    consolidate: "Consolidate",
    sourceSelected: "Selected",
    correction: "Correcting reviewed fact",
    consolidation: "Consolidating reviewed facts",
    cancelReplacement: "Cancel",
    removeSource: "Remove consolidation source",
    consolidationNeedsSources:
      "Select at least two compatible facts before proposing a consolidation.",
    pendingReplacement: "Pending replacement",
    changeRequired: "Change the fact before proposing its replacement.",
    reviewEvery: "Review every",
    reviewIntervalLabel: "Memory review interval in days",
    days: "days",
    review: "Review due",
    uses: "Runs used",
    lastUsed: "Last used",
    notScheduled: "On approval",
    never: "Never",
    corrects: "Corrects",
    consolidates: "Consolidates",
    supersededBy: "Superseded by",
    live: "LIVE",
    dueShort: "DUE",
    workspace: "Workspace",
    agent: "This agent",
    safety:
      "Only approved, in-date facts enter model context. Corrections and consolidations preserve every source as immutable review evidence.",
    errors: {
      consolidationScope: "Memory consolidation must preserve scope and Agent.",
      consolidationLimit: "Memory consolidation accepts at most 8 sources.",
    },
  },
  recovery: {
    eyebrow: "RECOVERY CHECKPOINT",
    title: "A run stopped before settlement.",
    body: "Resume from durable evidence. Napier will verify current state before repeating any operation with possible side effects.",
    action: "Resume safely",
    run: "Interrupted run",
  },
  context: {
    loading: "Opening Agent configuration...",
    observe: "Observe only",
    liveProvider: "Live provider",
    demoProvider: "Demo provider",
  },
  welcome: {
    eyebrow: "A glass-box agent runtime",
    title: "Work that leaves evidence.",
    body: "Napier turns conversations into durable ledgers: every model call, tool action, branch, goal, and artifact stays inspectable.",
    firstPrompt:
      "Ask Napier to inspect this workspace and propose the highest-leverage next step.",
  },
  notices: {
    demo: "Demo model",
    demoDetail: "Add a provider key on the server to run a live model.",
    disconnected: "The workspace could not be loaded.",
  },
} as const;
