import type { en } from "./copy";
import type { LocaleOverride } from "./locale";

/**
 * Chinese overrides for core UI surfaces. Missing keys fall back to English
 * via deepMergeCopy, so deep panels (lab, evaluation, receipt-trust, workflow)
 * remain English until a later translation pass.
 */
export const zh: LocaleOverride<typeof en> = {
  appName: "Napier",
  appDescriptor: "智能体工作台",
  settings: "设置",
  newThread: "新建会话",
  recentThreads: "会话",
  noThreads: "暂无会话",
  workspace: "本地工作区",
  localFirst: "本地优先",
  inspect: "查看",
  branch: "从此处分支",
  stop: "停止运行",
  running: "运行中",
  waiting: "已中断",
  idle: "就绪",
  failed: "待复核",
  composerPlaceholder: "给 Napier 一个任务、问题或长期目标……",
  steeringPlaceholder: "在保留会话记录的前提下调整当前运行……",
  send: "运行",
  modelUnavailable: "模型不可用",
  modelUnavailableHint: "开始运行或评估前，请在「上下文」中配置该提供方。",
  steer: "引导",
  queueFollowUp: "排队下一步",
  controlMode: "运行输入模式",
  inputMode: "输入",
  runControlMode: "运行控制",
  steering: "引导",
  followUp: "追加",
  shortcut: "⌘ ↵",
  trash: {
    action: "移至回收站",
    activeRun: "删除前请先停止正在进行的运行",
    confirm: "将此会话移至回收站？",
    confirmAction: "删除",
    cancel: "取消删除",
    trashing: "正在删除……",
    trashed: "已移至回收站",
    undo: "撤销",
    restoring: "正在恢复……",
  },
  composer: {
    runOptions: "运行选项",
    checkingRunOptions: "正在检查运行选项……",
  },
  sessionView: {
    eyebrow: "会话级控制台",
    title: "工作台",
    body: "此会话的持久意图、工作区产物、活动进程、浏览器状态与回放证据。",
    runs: "运行",
    plans: "计划",
    events: "事件",
    tools: "会话工具",
  },
  sections: {
    plan: "计划",
    studio: "工作室",
    goal: "目标",
    files: "文件",
    browser: "浏览器",
    processes: "进程",
    lab: "实验室",
    automations: "运维",
  },
  tabs: {
    conversation: "对话",
    session: "工作台",
    trace: "轨迹",
    processes: "进程",
    files: "文件",
    lab: "实验室",
    plan: "计划",
    goal: "目标",
    memory: "记忆",
    extensions: "扩展",
    automations: "运维",
    context: "上下文",
  },
  trace: {
    title: "运行证据",
    empty: "运行推进时，事件会显示在这里。",
    sequence: "序号",
  },
  goal: {
    title: "长期目标",
    empty: "设定一个可跨多次运行的目标。",
    placeholder: "定义一个可验证的结果……",
    set: "设定目标",
    clear: "清除",
    active: "进行中",
    completed: "已验证",
    blocked: "受阻",
    evidence: "最新证据",
    noProgress: "无进展",
    guardrail: "证据不足时 Napier 会安全终止。",
  },
  recovery: {
    eyebrow: "恢复检查点",
    title: "有一次运行在结算前中断。",
    body: "从持久证据恢复。Napier 会在重复任何可能有副作用的操作前先核实当前状态。",
    action: "安全恢复",
    run: "中断的运行",
    partial: {
      eyebrow: "部分完成检查点",
      title: "此任务已保留部分进展。",
      body: "从持久计划、证据和产物继续此任务。普通发送会改为开始新一轮运行。",
      action: "继续此任务",
      run: "部分完成的运行",
    },
  },
  context: {
    loading: "正在打开智能体配置……",
    observe: "仅观察",
    liveProvider: "在线提供方",
    demoProvider: "演示提供方",
  },
  workspaceSurface: {
    section: "工作区",
    sectionDescription: "此运行时所操作的本地文件夹",
    currentRoot: "当前文件夹",
    dataRoot: "会话数据根目录",
    inputLabel: "切换到其他文件夹",
    placeholder: "/项目的绝对路径",
    submit: "切换文件夹",
    switching: "正在切换工作区……",
    warning:
      "切换后会在新文件夹上重建运行时，并显示该文件夹自己的会话。当前文件夹的会话会保留，切回时重新出现。运行进行中时不可切换。",
    chipLabel: "工作区",
  },
  settingsSurface: {
    eyebrow: "工作区配置",
    title: "设置",
    body: "跨越单次对话或运行而持续保留的配置。",
    close: "关闭设置",
    contextSection: "智能体与模型",
    contextSectionDescription: "提供方、策略、技能与凭证",
    memorySection: "记忆",
    memorySectionDescription: "工作区知识与复盘节奏",
    extensionsSection: "扩展",
    extensionsSectionDescription: "MCP、扩展包与信任",
  },
  welcome: {
    eyebrow: "透明可观测的智能体运行时",
    title: "让工作留下证据。",
    body: "Napier 把对话沉淀为持久会话：每一次模型调用、工具操作、分支、目标与产物都可追溯查看。",
    firstPrompt: "让 Napier 检查此工作区，并提出最具价值的下一步。",
    cue: "在下方写下任务，证据会一并留存。",
  },
  notices: {
    demo: "演示模型",
    demoDetail: "在服务端添加提供方密钥即可运行在线模型。",
    disconnected: "无法加载工作区。",
  },
  language: {
    section: "语言",
    sectionDescription: "界面显示语言",
    chinese: "中文",
    english: "English",
    current: "当前语言",
  },
  narrative: {
    blockedBy: "受阻于",
    next: "下一步",
    browserControls: "浏览器控制",
    stop: "停止",
    emptyAction: "选择或新建一个会话",
  },
  projects: {
    heading: "项目",
    switching: "正在切换工作区……",
    current: "当前",
  },
};
