import type { en } from "./copy";
import { deepTraceCopyZh, delegationCopyZh, memoryCopyZh } from "./deep-ui-copy.zh";
import { goalCopyZh } from "./goal-copy";
import { labCopyZh } from "./lab-copy.zh";
import type { LocaleOverride } from "./locale";
import { contextCompactionCopyZh } from "./context-compaction-copy.zh";

/** Complete Chinese overrides for every string in the root application copy. */
export const zh: LocaleOverride<typeof en> = {
  appName: "Napier",
  appDescriptor: "智能体工作台",
  settings: "设置",
  newThread: "新建会话",
  recentThreads: "会话",
  noThreads: "暂无会话",
  workspace: "本地工作区",
  localFirst: "本地优先",
  inspect: "查看",
  branch: "从此处分支",
  stop: "停止运行",
  running: "运行中",
  waiting: "等待中",
  idle: "就绪",
  failed: "待复核",
  composerPlaceholder: "给 Napier 一个任务、问题或长期目标……",
  steeringPlaceholder: "在保留会话记录的前提下调整当前运行……",
  send: "运行",
  modelUnavailable: "模型不可用",
  modelUnavailableHint: "开始运行或评估前，请在「上下文」中配置该提供方。",
  readiness: {
    safeReadsOnly:
      "当前仅启用安全读取。任务需要编辑、命令、浏览器会话、扩展或子智能体时，请先配置 Sandbox。",
    hostDirect: "已明确启用无系统隔离的主机直连执行，命令会直接在本机运行。",
  },
  steer: "引导",
  queueFollowUp: "排队下一步",
  controlMode: "运行输入模式",
  inputMode: "输入",
  runControlMode: "运行控制",
  steering: "引导",
  followUp: "追加",
  shortcut: "⌘ ↵",
  trash: {
    action: "移至回收站",
    activeRun: "删除前请先停止正在进行的运行",
    confirm: "将此会话移至回收站？",
    confirmAction: "删除",
    cancel: "取消删除",
    trashing: "正在删除……",
    trashed: "已移至回收站",
    undo: "撤销",
    restoring: "正在恢复……",
  },
  sessionView: {
    eyebrow: "会话级控制台",
    title: "工作台",
    body: "此会话的持久意图、工作区产物、活动进程、浏览器状态与回放证据。",
    runs: "运行",
    plans: "计划",
    events: "事件",
    tools: "会话工具",
  },
  taskView: {
    eyebrow: "任务工作区",
    title: "任务",
    body: "汇总当前任务的目标、工作产物、运行环境与验证结果。",
    sections: {
      overview: "概览",
      changes: "变更",
      environment: "运行环境",
      validation: "验证",
    },
    overview: {
      objective: "目标",
      progress: "进度",
      artifacts: "工作产物",
      complete: "完成",
      current: "当前步骤",
      completedSteps: "已完成步骤",
      upcomingSteps: "后续步骤",
      planStatus: {
        active: "进行中",
        completed: "已完成",
        blocked: "受阻",
        cancelled: "已取消",
      },
      noPlan: "当前任务尚未记录执行计划。",
      noGoal: "如果任务需要跨多次运行持续推进，可添加长期目标。",
      addGoal: "添加长期目标",
      saveGoal: "保存目标",
      clearGoal: "清除目标",
      continue: "继续任务",
      decisionEyebrow: "等待你的选择",
      decisionNext: "上一轮运行已结束；先记录选择，再启动关联续跑。",
      reviewDecision: "处理决策",
      stepStatus: {
        pending: "待开始",
        ready: "可执行",
        running: "执行中",
        partial: "部分完成",
        completed: "已完成",
        blocked: "受阻",
        skipped: "已跳过",
      },
    },
    changes: {
      title: "变更与产物",
      body: "当前任务生成的文件、Artifact 与引用。",
      empty: "当前任务尚未记录变更或产物。",
      recovery: "恢复",
      recoveryBody: "恢复被移入 Napier 回收站的工作区内容。",
      references: "引用",
    },
    environment: {
      title: "运行环境",
      body: "当前任务正在使用的浏览器、进程与 Sandbox 资源。",
      browser: "浏览器",
      process: "进程",
      sandbox: "Sandbox",
      empty: "当前任务没有活动的运行环境资源。",
    },
    validation: {
      title: "验证",
      body: "只展示验证回执、诊断与产物 Ledger 中可直接确认的事实。",
      latestRun: "最近运行",
      checks: "验证矩阵",
      empty: "当前任务尚未记录验证证据。",
      passed: "已验证",
      failed: "失败",
      warning: "警告",
      unknown: "未知",
      stale: "证据早于后续工作区写入",
      source: "来源",
      evidence: "证据摘要",
      checksByKind: {
        typecheck: "类型检查",
        tests: "测试",
        diagnostics: "Lint / 诊断",
        artifact: "产物",
      },
      sources: {
        receipt: "验证回执",
        lsp: "LSP",
        ledger: "Ledger",
      },
      noEvidence: "未记录直接证据",
      exitCode: "退出码",
      duration: "耗时",
      diagnostics: "诊断",
      errors: "错误",
      warnings: "警告",
      artifactCounts: "已验证 {verified} · 已产出 {produced} · 缺失 {missing} · 总计 {total}",
    },
    status: {
      queued: "排队中",
      running: "运行中",
      waiting: "等待中",
      completed: "已完成",
      failed: "失败",
      cancelled: "已取消",
      interrupted: "已中断",
      pending: "待处理",
      ready: "就绪",
      partial: "部分完成",
      blocked: "受阻",
      skipped: "已跳过",
      candidate: "候选",
      produced: "已产出",
      verified: "已验证",
      missing: "缺失",
      superseded: "已替代",
    },
    duration: {
      minute: "分",
      second: "秒",
    },
  },
  sections: {
    plan: "计划",
    studio: "工作室",
    goal: "目标",
    files: "文件",
    browser: "浏览器",
    processes: "进程",
    lab: "实验室",
    automations: "运维",
  },
  tabs: {
    conversation: "对话",
    session: "任务",
    trace: "轨迹",
    subagents: "子智能体",
    processes: "进程",
    files: "文件",
    lab: "实验室",
    plan: "计划",
    goal: "目标",
    memory: "记忆",
    extensions: "扩展",
    automations: "运维",
    context: "上下文",
  },
  automationLoading: "正在打开自动化注册表……",
  processLoading: "正在打开 Sandbox 进程注册表……",
  filesLoading: "正在打开可逆工作区恢复……",
  extensionLoading: "正在打开能力注册表……",
  planLoading: "持久计划",
  planNextPrompt:
    "继续执行持久计划。从下一个就绪步骤开始，完成该步骤、验证其条件，并用具体证据结算后再继续。",
  trace: {
    title: "运行轨迹",
    empty: "运行推进时，事件会显示在这里。",
    emptyTitle: "尚未记录运行轨迹",
    mapEyebrow: "执行路径",
    body: "默认优先呈现可读的关键动作，完整隐私边界内审计可随时切换查看。",
    plotting: "记录中",
    recorded: "已记录",
    elapsed: "耗时",
    turns: "轮次",
    calls: "调用",
    keyActions: "关键动作",
    sequence: "序号",
    showEarlier: "显示更早事件",
    evidenceTitle: "证据与诊断",
    evidenceBody: "导出回执、摘要覆盖、模型上下文、审查与委派记录。",
    harness: {
      eyebrow: "模型运行策略",
      title: "本次模型策略",
      empty: "当前任务尚未记录模型运行策略。",
      profile: "提示方言",
      intent: "任务意图",
      tools: "可见工具",
      saved: "节省 Schema",
      retries: "重试",
      model: "模型",
      omitted: "延后工具",
      none: "无",
      receipt: "回执",
      intents: {
        browser: "浏览器",
        coding: "编码",
        data: "数据",
        research: "调研",
        general: "通用",
      },
    },
    modelAdapter: {
      eyebrow: "模型适配器",
      title: "提供方请求策略",
      empty: "当前任务尚未记录模型适配器选择。",
      api: "API",
      cache: "缓存",
      source: "来源",
      streamCap: "流式上限",
      modelCap: "模型上限",
      tokenSource: "Token 来源",
      adapter: "适配器",
      legacy: "旧版不可用",
      receipt: "回执",
    },
    contextEnvelope: {
      eyebrow: "模型上下文",
      title: "提供方请求信封",
      empty: "当前任务尚未记录模型上下文信封。",
      turn: "轮次",
      messages: "消息",
      users: "用户消息",
      assistants: "助手消息",
      toolResults: "工具结果",
      other: "其他",
      promptBytes: "Prompt 字节",
      toolCount: "工具",
      toolSchemaBytes: "工具 Schema 字节",
      toolSchemaTokens: "工具 Schema 估算",
      prompt: "Prompt",
      messageSet: "消息集合",
      toolNames: "工具名称",
      toolDefinitions: "工具定义",
      response: "响应",
      responseMissing: "没有绑定响应",
      stop: "停止原因",
      receipt: "回执",
    },
    contextPruning: {
      eyebrow: "上下文裁剪",
      title: "工具结果上下文预算",
      empty: "当前任务尚未记录工具结果上下文决策。",
      attempt: "尝试",
      results: "结果",
      replaced: "已压缩",
      saved: "节省文本",
      active: "活跃文本",
      superseded: "已取代读取",
      repeated: "重复错误",
      large: "大型输出",
      emptyResults: "空结果",
      context: "上下文集合",
      receipt: "回执",
    },
    contextContinuity: {
      eyebrow: "上下文连续性",
      title: "压缩交接边界",
      empty: "当前任务尚未记录上下文压缩检查点。",
      coverage: "压缩范围",
      retained: "保留历史起点",
      messages: "来源消息",
      executionEvents: "执行事件",
      decisions: "决策",
      openLoops: "未决事项",
      artifacts: "产物",
      executionBinding: "执行绑定",
      messageBinding: "消息绑定",
      summary: "摘要绑定",
      unavailable: "旧版不可用",
      states: {
        bound: "执行状态已绑定",
        legacy_unbound: "旧版仅消息检查点",
      },
    },
    ...deepTraceCopyZh,
  },
  lab: labCopyZh,
  delegation: delegationCopyZh,
  goal: goalCopyZh,
  memory: memoryCopyZh,
  recovery: {
    eyebrow: "恢复检查点",
    title: "有一次运行在结算前中断。",
    body: "从持久证据恢复。Napier 会在重复任何可能有副作用的操作前先核实当前状态。",
    action: "安全恢复",
    run: "中断的运行",
    partial: {
      eyebrow: "部分完成检查点",
      title: "此任务已保留部分进展。",
      body: "从持久计划、证据和产物继续此任务。普通发送会改为开始新一轮运行。",
      action: "继续此任务",
      run: "部分完成的运行",
    },
  },
  context: {
    loading: "正在打开智能体配置……",
    observe: "仅观察",
    liveProvider: "在线提供方",
    demoProvider: "演示提供方",
  },
  workspaceSurface: {
    section: "工作区",
    sectionDescription: "此运行时所操作的本地文件夹",
    currentRoot: "当前文件夹",
    dataRoot: "会话数据根目录",
    inputLabel: "切换到其他文件夹",
    placeholder: "/项目的绝对路径",
    submit: "切换文件夹",
    switching: "正在切换工作区……",
    warning:
      "切换后会在新文件夹上重建运行时，并显示该文件夹自己的会话。当前文件夹的会话会保留，切回时重新出现。运行进行中时不可切换。",
    chipLabel: "工作区",
  },
  settingsSurface: {
    eyebrow: "工作区配置",
    title: "设置",
    body: "跨越单次对话或运行而持续保留的配置。",
    close: "关闭设置",
    sectionsLabel: "设置分区",
    contextSection: "智能体与模型",
    contextSectionDescription: "提供方、策略、技能与凭证",
    memorySection: "记忆",
    memorySectionDescription: "工作区知识与复盘节奏",
    extensionsSection: "扩展",
    extensionsSectionDescription: "MCP 与插件能力概览",
    automationsSection: "自动化",
    automationsSectionDescription: "工作区计划任务与入站渠道",
    developerSection: "开发者",
    developerSectionDescription: "实验、Fixture、试用与工作流工具",
    developerIntro: "高级诊断和治理能力保留在普通任务路径之外。",
    runLab: "运行实验室与评测",
    contextCompaction: contextCompactionCopyZh,
    workflowStudio: "工作流工作室",
    productTrial: "产品试用记录器",
    designSection: "设计系统",
    designSectionDescription: "Token、组件与交互状态",
    designShowcase: {
      tokenEyebrow: "DESIGN.md / TOKEN",
      colors: "语义色彩",
      colorLabels: {
        accent: "主色",
        success: "成功",
        warning: "警告",
        danger: "危险",
        surface: "表面",
        muted: "弱化",
      },
      typography: "字体层级",
      headingSample: "可靠完成工作，清晰说明结果。",
      bodySample: "Napier 让任务保持易读，证据始终只需一次明确操作即可查看。",
      technicalSample: "模型、工具与运行轨迹注释",
      controls: "控件",
      primaryAction: "主要操作",
      secondaryAction: "次要操作",
      disabledAction: "已禁用操作",
      taskName: "任务名称",
      taskNameValue: "桌面任务工作台",
      fieldHelp: "输入框清晰呈现标签、值、帮助信息和焦点状态。",
      states: "任务状态",
      stateLabels: {
        ready: "就绪",
        working: "工作中",
        waiting: "等待中",
        failed: "失败",
        completed: "已完成",
      },
      emptyStateLabel: "空状态示例",
      emptyStateTitle: "暂无产物",
      emptyStateBody: "任务产生可持久化工作成果后，输出会显示在这里。",
    },
  },
  developerWorkbench: {
    eyebrow: "高级控制面",
    title: "开发者工作台",
    body: "面向明确操作流程的自动化、评测、发布与设计控制。",
    close: "关闭开发者工作台",
    sectionsLabel: "开发者工作台分区",
    open: "开发者工作台",
    automationsSection: "自动化工作台",
    automationsSectionDescription: "计划任务、入站渠道与恢复",
    labSection: "实验与工作流",
    labSectionDescription: "评测、Fixture、信任与产品试用",
    publishingSection: "发布治理",
    publishingSectionDescription: "Publisher、签名、灰度与部署",
    designSection: "设计系统",
    designSectionDescription: "Token、组件与交互状态",
    extensionPublishingEyebrow: "扩展交付",
    extensionPublishingTitle: "扩展发布治理",
    extensionPublishingBody: "通过明确的复核门禁签名、验证、发布、更新与部署扩展包。",
    agentPublishingEyebrow: "智能体交付",
    agentPublishingTitle: "智能体包发布",
    agentPublishingBody: "在普通智能体配置之外创建并检查签名的 Skill 与 Prompt 包。",
  },
  modelPicker: {
    title: "选择模型",
    searchLabel: "搜索模型",
    searchPlaceholder: "搜索提供方或模型……",
    showUnavailable: "显示未配置模型",
    configured: "凭证可用",
    unavailable: "未配置",
    context: "上下文",
    reasoning: "推理",
    vision: "视觉",
    recommended: "智能体默认",
    recent: "最近使用",
    empty: "没有匹配的模型。",
  },
  welcome: {
    eyebrow: "透明可观测的智能体运行时",
    title: "让工作留下证据。",
    body: "Napier 把对话沉淀为持久会话：每一次模型调用、工具操作、分支、目标与产物都可追溯查看。",
    firstPrompt: "让 Napier 检查此工作区，并提出最具价值的下一步。",
    cue: "在下方写下任务，证据会一并留存。",
  },
  notices: {
    demo: "演示模型",
    demoDetail: "在服务端添加提供方密钥即可运行在线模型。",
    disconnected: "无法加载工作区。",
  },
  language: {
    section: "语言",
    sectionDescription: "界面显示语言",
    chinese: "中文",
    english: "English",
    current: "当前语言",
  },
  narrative: {
    blockedBy: "受阻于",
    next: "下一步",
    currentAction: "当前动作",
    elapsed: "已用时间",
    details: "详情",
    runMetrics: "运行指标",
    harness: "运行模式",
    harnessFocused: "聚焦",
    harnessFull: "完整",
    harnessTools: "个工具",
    environmentFallback: "只读环境降级",
    environmentFallbackBody:
      "Sandbox 暂不可用。安全读取可以继续；编辑和进程能力保持关闭。",
    environmentToolsActive: "个工具可用",
    environmentRepair: "运行选项 → Sandbox 设置",
    browserControls: "浏览器控制",
    stop: "停止",
    emptyAction: "选择或新建一个会话",
  },
  projects: {
    heading: "项目",
    switching: "正在切换工作区……",
    current: "当前",
  },
};
