import type { en } from "./copy";
import type { LocaleOverride } from "./locale";

/**
 * Chinese overrides for core UI surfaces. Missing keys fall back to English
 * via deepMergeCopy, so deep panels (lab, evaluation, receipt-trust, workflow)
 * remain English until a later translation pass.
 */
export const zh: LocaleOverride<typeof en> = {
  appName: "Napier",
  appDescriptor: "智能体工作台账",
  settings: "设置",
  newThread: "新建台账",
  recentThreads: "台账",
  noThreads: "暂无台账",
  workspace: "本地工作区",
  localFirst: "本地优先",
  inspect: "查看",
  branch: "在此分支",
  stop: "停止运行",
  running: "运行中",
  waiting: "已中断",
  idle: "就绪",
  failed: "待复核",
  composerPlaceholder: "给 Napier 一个任务、问题或长期目标……",
  steeringPlaceholder: "在不丢失台账的前提下调整当前运行……",
  send: "运行",
  modelUnavailable: "模型不可用",
  modelUnavailableHint: "开始运行或评估前，请在「上下文」中配置该提供方。",
  steer: "引导",
  queueFollowUp: "排队下一步",
  controlMode: "运行输入模式",
  inputMode: "输入",
  runControlMode: "运行控制",
  steering: "引导",
  followUp: "追加",
  shortcut: "⌘ ↵",
  tabs: {
    conversation: "对话",
    session: "会话",
    trace: "轨迹",
    processes: "进程",
    files: "文件",
    lab: "实验室",
    plan: "计划",
    goal: "目标",
    memory: "记忆",
    extensions: "扩展",
    automations: "运维",
    context: "上下文",
  },
  trace: {
    title: "运行证据",
    empty: "运行推进时，事件会显示在这里。",
    sequence: "序号",
  },
  goal: {
    title: "长期目标",
    empty: "设定一个可跨多次运行的目标。",
    placeholder: "定义一个可验证的结果……",
    set: "设定目标",
    clear: "清除",
    active: "进行中",
    completed: "已验证",
    blocked: "受阻",
    evidence: "最新证据",
    noProgress: "无进展",
    guardrail: "证据不足时 Napier 会安全终止。",
  },
  recovery: {
    eyebrow: "恢复检查点",
    title: "有一次运行在结算前中断。",
    body: "从持久证据恢复。Napier 会在重复任何可能有副作用的操作前先核实当前状态。",
    action: "安全恢复",
    run: "中断的运行",
  },
  context: {
    loading: "正在打开智能体配置……",
    observe: "仅观察",
    liveProvider: "在线提供方",
    demoProvider: "演示提供方",
  },
  workspaceSurface: {
    section: "工作区",
    sectionDescription: "此运行时所操作的本地文件夹",
    currentRoot: "当前文件夹",
    dataRoot: "台账数据根目录",
    inputLabel: "切换到其他文件夹",
    placeholder: "/项目的绝对路径",
    submit: "切换文件夹",
    switching: "正在切换工作区……",
    warning:
      "切换会在新文件夹上重建运行时并显示该文件夹自己的台账。当前文件夹的台账会保留，切回时会重新出现。运行进行中时不可切换。",
    chipLabel: "工作区",
  },
  welcome: {
    eyebrow: "透明可观测的智能体运行时",
    title: "留下证据的工作。",
    body: "Napier 把对话变成持久台账：每一次模型调用、工具操作、分支、目标与产物都可追溯查看。",
    firstPrompt: "让 Napier 检查此工作区并提出最具价值的下一步。",
  },
  notices: {
    demo: "演示模型",
    demoDetail: "在服务端添加提供方密钥即可运行在线模型。",
    disconnected: "无法加载工作区。",
  },
  language: {
    section: "语言",
    sectionDescription: "界面显示语言",
    chinese: "中文",
    english: "English",
    current: "当前语言",
  },
  narrative: {
    blockedBy: "受阻于",
    next: "下一步",
    browserControls: "浏览器控制",
    stop: "停止",
  },
  projects: {
    heading: "项目",
    switching: "正在切换工作区……",
    current: "当前",
  },
};
