import { deepMergeCopy, getLocale } from "./locale";
import { zh } from "./copy.zh";
import { recoveryCopy } from "./recovery-copy";

export const en = {
  appName: "Napier",
  appDescriptor: "Agent work ledger",
  settings: "Settings",
  newThread: "New ledger",
  recentThreads: "Ledgers",
  noThreads: "No ledgers yet",
  workspace: "Local workspace",
  localFirst: "Local-first",
  inspect: "Inspect",
  branch: "Branch here",
  stop: "Stop run",
  running: "Running",
  waiting: "Interrupted",
  idle: "Ready",
  failed: "Needs review",
  composerPlaceholder: "Give Napier a task, question, or durable goal...",
  steeringPlaceholder: "Redirect the active run without losing its ledger...",
  send: "Run",
  modelUnavailable: "Model unavailable",
  modelUnavailableHint:
    "Configure this provider in Context before starting a run or evaluation.",
  steer: "Steer",
  queueFollowUp: "Queue next",
  controlMode: "Run input mode",
  inputMode: "Input",
  runControlMode: "Run control",
  steering: "Steering",
  followUp: "Follow-up",
  shortcut: "⌘ ↵",
  tabs: {
    conversation: "Conversation",
    session: "Session",
    trace: "Trace",
    processes: "Processes",
    files: "Files",
    lab: "Lab",
    plan: "Plan",
    goal: "Goal",
    memory: "Memory",
    extensions: "Extend",
    automations: "Ops",
    context: "Context",
  },
  automationLoading: "Opening automation register...",
  processLoading: "Opening sandbox process register...",
  filesLoading: "Opening reversible workspace recovery...",
  extensionLoading: "Opening capability registry...",
  planLoading: "Durable plan",
  planNextPrompt:
    "Continue the durable execution plan. Start the next ready step, perform it, verify its stated condition, and settle the step with concrete evidence before moving on.",
  trace: {
    title: "Run evidence",
    empty: "Events will appear here as the run unfolds.",
    sequence: "SEQ",
    otel: {
      eyebrow: "VENDOR-NEUTRAL TRACE",
      title: "OpenTelemetry export",
      body: "Project this ledger into OTLP/JSON spans for Collector, Jaeger, Tempo, or another compatible backend.",
      scope: "Export scope",
      threadScope: "Complete Thread",
      runScope: "Single Run",
      export: "Export OTLP trace",
      exporting: "Binding spans...",
      exported: "OTLP trace exported",
      verify: "Verify archived JSON",
      verifying: "Checking archive...",
      verified: "OTLP trace verified",
      invalid: "OTLP trace invalid",
      noDiagnostics: "No diagnostics",
      spans: "Spans",
      events: "Events",
      eventAnchor: "Event anchor",
      safety:
        "Metadata-only export excludes prompts, completions, reasoning, tool I/O, notes, evidence text, and credential locators.",
      errors: {
        artifactTooLarge: "OTLP trace artifact is larger than 10 MiB.",
        artifactInvalid: "OTLP trace artifact must be valid JSON.",
      },
    },
    summary: {
      eyebrow: "SUMMARY BOUNDARY",
      title: "Trace summary coverage",
      genericTypes: "Generic fallback",
      noGeneric: "No generic fallback in this event set.",
      receipt: "Receipt",
      verificationPending: "Verifying receipt",
      verificationValid: "Receipt verified",
      verificationInvalid: "Receipt invalid",
      noDiagnostics: "No diagnostics",
      sources: {
        bounded: "Bounded",
        fixed: "Fixed",
        category: "Category",
        generic: "Generic",
      },
    },
  },
  lab: {
    eyebrow: "RUN LAB",
    title: "Compare evidence",
    count: "settled runs",
    empty: "Complete at least two runs to open a comparison.",
    baseline: "Baseline",
    candidate: "Candidate",
    selectRun: "Select a run",
    compare: "Compare",
    evaluate: "Evaluate",
    comparing: "Comparing...",
    evaluating: "Evaluating...",
    export: "Export replay",
    metricDelta: "Candidate delta",
    eventDelta: "Event delta",
    output: "Final output",
    changed: "Changed",
    unchanged: "Unchanged",
    duration: "Duration",
    events: "Events",
    tokens: "Tokens",
    tools: "Tool calls",
    contextEnvelopes: "Context envelopes",
    embeddedContextEnvelopes: "Embedded envelopes",
    contextBindings: "Context binds",
    contextMisses: "Context misses",
    contextCoverage: "Context coverage",
    contextCoverageClean: "Clean",
    contextCoveragePartial: "Partial",
    contextCoverageMissing: "Missing",
    contextCoverageRegressed: "Regressed",
    contextCoverageHealthy:
      "Candidate model responses are fully bound to context envelopes.",
    contextCoverageDelta: "Delta",
    contextCoverageDiagnostics: "Diagnostics",
    traceSummaryCoverage: "Trace summary coverage",
    traceSummaryClean: "Clean",
    traceSummaryGenericPresent: "Generic fallback",
    traceSummaryRegressed: "Regressed",
    traceSummaryHealthy:
      "Candidate trace summaries avoid the generic raw-payload fallback.",
    traceSummaryDiagnostics: "Summary diagnostics",
    traceSummaryGeneric: "Generic",
    traceSummaryGenericDelta: "Generic delta",
    traceSummaryDedicatedDelta: "Dedicated delta",
    traceSummaryDelta: "Summary delta",
    traceSummaryReceipt: "Summary receipt",
    traceSummaryVerification: "Summary verification",
    traceSummaryVerified: "Verified",
    traceSummaryInvalid: "Invalid",
    cost: "Cost",
    noDelta: "No event-type differences.",
    configuration: "Configuration drift",
    configurationChanged: "Changed",
    configurationUnchanged: "Unchanged",
    configurationUnavailableShort: "Unavailable",
    configurationUnavailable:
      "One or both Runs predate configuration fingerprints. Drift is unknown.",
    verdict: "Independent verdict",
    noVerdict: "No evaluation has been recorded for this pair.",
    evidence: "Evaluator evidence",
    rubric: "Rubric scores",
    left: "L",
    right: "R",
    hashes: "Evidence hashes",
    governance: "Governance",
    demoNotice:
      "The demo model records an inconclusive verdict. Choose a configured live model for independent scoring.",
    safety:
      "Evaluators receive immutable snapshots, no tools, and untrusted ledger evidence. Verdicts bind to both event-stream hashes.",
    fixture: {
      eyebrow: "THREAD FIXTURE",
      title: "Portable ledger",
      body: "Carry the complete Thread, Agent revisions, Runs, plans, evaluations, human adjudications, reviewer consensus, quality gates, subagents, and ordered evidence as one replay fixture.",
      events: "events",
      contextEnvelopes: "context envelopes",
      embeddedEnvelopes: "embedded envelopes",
      runs: "runs",
      plans: "plans",
      evaluations: "evaluations",
      importedSource: "Imported source SHA-256",
      sourceEvents: "source events",
      localImportedCutoff: "local cutoff",
      importReceipt: "import receipt",
      export: "Export full ledger",
      exporting: "Binding fixture...",
      verify: "Verify fixture",
      verifying: "Checking fixture...",
      import: "Import fixture",
      importing: "Importing fixture...",
      noDiagnostics: "No diagnostics",
      safety:
        "Both content and event-stream hashes are verified. Imported in-flight work is closed with an unknown outcome.",
      receipts: {
        exported: "Fixture exported",
        imported: "Fixture imported",
        verified: "Fixture verified",
        invalid: "Fixture invalid",
      },
    },
    replay: {
      eyebrow: "RUN REPLAY",
      title: "Snapshot verifier",
      body: "Verify an archived per-Run replay JSON against the active Thread boundary before using it for evidence review or CI regression checks.",
      verify: "Verify replay JSON",
      verifying: "Checking replay...",
      verified: "Replay verified",
      invalid: "Replay invalid",
      subagents: "subagents",
    },
    trust: {
      eyebrow: "TRUSTED PROVENANCE",
      title: "Receipt trust desk",
      body: "Bind release evidence to an Ed25519 identity, retain public trust anchors, and verify signed receipts without trusting their transport.",
      anchors: "Trust anchors",
      empty: "No receipt trust anchor is registered.",
      add: "Add trust anchor",
      adding: "Reading key...",
      label: "Anchor label",
      labelPlaceholder: "Release signing identity",
      source: "Anchor source",
      environment: "Local signer · environment",
      publicKey: "Verify only · public key",
      environmentVariable: "PKCS#8 private-key environment variable",
      publicKeySpki: "SPKI public key · Base64 DER",
      publicKeyPlaceholder: "MCowBQYDK2VwAyEA…",
      signing: "Local signing",
      verifyOnly: "Verify only",
      revoke: "Revoke",
      confirmRevoke: "Confirm revoke",
      cancel: "Cancel revocation",
      verifier: "Offline envelope verifier",
      verifierBody:
        "Deep-check payload hashes, signature statement, Ed25519 signature, and current anchor state.",
      chooseReceipt: "Verify signed JSON",
      verifying: "Verifying envelope...",
      exportDirectory: "Export anchor directory",
      exportingDirectory: "Exporting directory...",
      signDirectoryMetadata: "Sign directory metadata",
      signingDirectoryMetadata: "Signing metadata...",
      verifyDirectoryMetadata: "Verify directory metadata",
      verifyingDirectoryMetadata: "Verifying metadata...",
      directoryMetadataPublisher: "Napier Trust Registry",
      chooseDirectory: "Verify anchor directory",
      verifyingDirectory: "Verifying directory...",
      directorySource: "Hosted directory URL",
      directorySourcePlaceholder: "https://trust.example.com/anchors.json",
      subscriptionLabel: "Subscription label",
      subscriptionLabelPlaceholder: "Release trust feed",
      expectedAnchorSet: "Expected anchor-set SHA-256",
      expectedAnchorSetPlaceholder: "Optional rotation pin",
      discoverDirectory: "Discover directory",
      discoveringDirectory: "Discovering directory...",
      subscribeDirectory: "Subscribe",
      subscribingDirectory: "Subscribing...",
      directorySubscriptions: "Directory subscriptions",
      evaluateQuorum: "Evaluate quorum",
      evaluatingQuorum: "Evaluating...",
      quorumAgreement: "source agreement",
      quorumWeight: "weight",
      quorumPublishers: "publishers",
      nextRefresh: "next",
      transparencyTail: "tail",
      useSubscription: "Use",
      subscriptionInUse: "In use",
      refreshSubscription: "Refresh subscription",
      pauseSubscription: "Pause subscription",
      resumeSubscription: "Resume subscription",
      externalDirectoryActive:
        "Signed JSON verification is using the active external directory.",
      externalDirectoryReady: "External directory active",
      externalTrustedKeys: "trusted verifier keys",
      clearExternalDirectory: "Return to local receipt trust anchors",
      hashOnlyRemoteSource:
        "Remote source and response are retained as hashes.",
      noDiagnostics: "No diagnostics",
      directoryAge: "Directory age",
      policyHash: "Policy",
      statuses: {
        trusted: "Trusted",
        revoked: "Revoked",
      },
      verificationStatuses: {
        trusted: "Trusted origin",
        revoked: "Valid · key revoked",
        unknown_key: "Unknown signer",
        invalid: "Invalid envelope",
      },
      verificationDirectorySources: {
        uploaded: "Uploaded directory",
        active_selection: "Active verifier selection",
      },
      directoryVerificationStatuses: {
        valid: "Directory valid",
        invalid: "Directory invalid",
      },
      directoryMetadataVerificationStatuses: {
        trusted: "Metadata trusted",
        revoked: "Metadata key revoked",
        unknown_key: "Unknown metadata signer",
        invalid: "Metadata invalid",
      },
      directoryDiscoveryStatuses: {
        valid: "Hosted directory accepted",
        invalid: "Hosted directory rejected",
      },
      subscriptionStatuses: {
        active: "Active",
        paused: "Paused",
      },
      subscriptionRefreshStatuses: {
        promoted: "rotation promoted",
        unchanged: "directory unchanged",
        rollback_rejected: "rollback rejected",
        rejected: "refresh rejected",
        failed: "refresh failed",
      },
      quorumStatuses: {
        agreed: "Quorum agreed",
        insufficient_sources: "Quorum lacks sources",
        split: "Quorum split",
        policy_failed: "Quorum policy failed",
      },
      checkpointRegistryQuorumStatuses: {
        agreed: "Checkpoint quorum agreed",
        insufficient_sources: "Checkpoint quorum lacks sources",
        split: "Checkpoint registries split",
        policy_failed: "Checkpoint quorum policy failed",
        stale: "Checkpoint registries stale",
      },
      baselineWorkbench: "Baseline activation",
      baselineWorkbenchBody:
        "Review signed quorum baselines against the current last-good directory feeds before activating a verifier set.",
      baselineWorkbenchEmpty:
        "No quorum-promotion baseline has been imported or promoted yet.",
      latestBaseline: "Latest quorum baseline",
      baselineSourcesAligned: "sources aligned",
      verifyBaseline: "Review baseline",
      verifyingBaseline: "Reviewing...",
      importBaseline: "Import baseline archive",
      importingBaseline: "Importing...",
      signBaselineActivation: "Sign activation",
      signingBaselineActivation: "Signing...",
      applyBaselineActivation: "Apply activation",
      applyingBaselineActivation: "Applying...",
      refreshActivationSelectionDrift: "Audit drift",
      refreshingActivationSelectionDrift: "Auditing...",
      reviewActivationSelectionRotation: "Review rotation",
      reviewingActivationSelectionRotation: "Reviewing...",
      proposeActivationSelectionRotation: "Propose rotation",
      proposingActivationSelectionRotation: "Proposing...",
      signActivationSelectionRotationProposal: "Sign proposal",
      signingActivationSelectionRotationProposal: "Signing proposal...",
      preflightActivationSelectionRotationProposal: "Preflight proposal",
      preflightingActivationSelectionRotationProposal: "Preflighting...",
      exportActivationSelectionCheckpoint: "Export checkpoint",
      exportingActivationSelectionCheckpoint: "Exporting checkpoint...",
      signActivationSelectionCheckpoint: "Sign checkpoint",
      signingActivationSelectionCheckpoint: "Signing checkpoint...",
      activationSelectionCheckpointSource: "Hosted checkpoint URL",
      activationSelectionCheckpointSourcePlaceholder:
        "https://trust.example.com/activation-selection-checkpoint.json",
      checkpointSubscriptionLabel: "Checkpoint subscription label",
      checkpointSubscriptionLabelPlaceholder: "Activation checkpoint registry",
      expectedActivationSelectionCheckpoint: "Expected checkpoint SHA-256",
      expectedActivationSelectionCheckpointPlaceholder:
        "Optional checkpoint pin",
      discoverActivationSelectionCheckpoint: "Discover checkpoint",
      discoveringActivationSelectionCheckpoint: "Discovering checkpoint...",
      subscribeActivationSelectionCheckpoint: "Subscribe checkpoint",
      subscribingActivationSelectionCheckpoint: "Subscribing checkpoint...",
      checkpointSubscriptions: "Checkpoint subscriptions",
      evaluateCheckpointRegistryQuorum: "Evaluate checkpoint quorum",
      evaluatingCheckpointRegistryQuorum: "Evaluating checkpoint quorum...",
      promoteCheckpointRegistryQuorumBaseline: "Promote checkpoint quorum",
      promotingCheckpointRegistryQuorumBaseline:
        "Promoting checkpoint quorum...",
      checkpointRegistryQuorumBaseline: "Checkpoint quorum baseline",
      verifyCheckpointRegistryQuorumBaseline: "Verify checkpoint baseline",
      verifyingCheckpointRegistryQuorumBaseline:
        "Checking checkpoint baseline...",
      importCheckpointRegistryQuorumBaseline: "Import checkpoint baseline",
      importingCheckpointRegistryQuorumBaseline:
        "Importing checkpoint baseline...",
      checkpointRegistryQuorumBaselineImported: "Checkpoint baseline imported",
      checkpointRegistryQuorumBaselineAlreadyImported:
        "Checkpoint baseline already archived",
      refreshCheckpointSubscription: "Refresh checkpoint",
      refreshingCheckpointSubscription: "Refreshing checkpoint...",
      updatingCheckpointSubscription: "Updating checkpoint...",
      verifyActivationSelectionCheckpoint: "Verify checkpoint",
      verifyingActivationSelectionCheckpoint: "Checking checkpoint...",
      activeBaselineActivation: "Active verifier selection",
      activeBaselineActivationBody: "CAS-bound approval is active",
      activationSelectionDriftAudit: "Selection drift audit",
      activationSelectionRotationReview: "Rotation review",
      activationSelectionRotationProposal: "Rotation proposal",
      signedActivationSelectionRotationProposal: "Signed rotation proposal",
      activationSelectionRotationProposalPreflight: "Proposal preflight",
      activationSelectionCheckpoint: "Selection checkpoint",
      signedActivationSelectionCheckpoint: "Signed checkpoint",
      activationSelectionCheckpointEntries: "selection entries",
      exportBaselineActivationHistory: "Export activation history",
      exportingBaselineActivationHistory: "Exporting history...",
      verifyBaselineActivationHistory: "Verify activation history",
      verifyingBaselineActivationHistory: "Checking history...",
      baselineActivationHistory: "Activation history",
      baselineActivationHistoryApproved: "approved decisions",
      baselineActivationHistoryBaselines: "baselines",
      baselineUnknownSource: "Archived source",
      baselineSourceStatuses: {
        aligned: "Current last-good directory matches",
        directory_drift: "Directory hash drift",
        anchor_set_drift: "Anchor-set drift",
        no_last_good: "No last-good directory",
        missing_subscription: "No active subscription",
      },
      baselineVerificationStatuses: {
        trusted: "Baseline trusted",
        revoked: "Baseline key revoked",
        unknown_key: "Unknown baseline signer",
        invalid: "Baseline invalid",
      },
      baselinePolicyStatuses: {
        accepted: "Activation policy accepted",
        rejected: "Activation policy rejected",
      },
      baselineActivationDecisionStatuses: {
        approved: "Activation approved",
        rejected: "Activation rejected",
      },
      activationSelectionDriftStatuses: {
        missing_selection: "No active verifier selection",
        aligned: "Selection matches current quorum",
        directory_drift: "Directory hash drift detected",
        anchor_set_drift: "Anchor-set drift detected",
        quorum_unavailable: "Current quorum unavailable",
      },
      activationSelectionRotationStatuses: {
        eligible: "Candidate can replace active selection",
        already_active: "Candidate is already active",
        blocked: "Candidate failed rotation gates",
        stale_selection: "Selection CAS precondition failed",
        missing_decision: "Activation decision is missing",
      },
      activationSelectionRotationProposalStatuses: {
        proposed: "Rotation proposal ready",
        already_active: "Candidate is already active",
        blocked: "Proposal failed gates",
        stale_selection: "Selection CAS precondition failed",
        missing_decision: "Activation decision is missing",
        missing_checkpoint_registry_baseline:
          "Checkpoint quorum baseline is missing",
      },
      activationSelectionRotationProposalPreflightStatuses: {
        accepted: "Signed proposal is fresh",
        rejected: "Signed proposal rejected",
        not_required: "Proposal not required",
      },
      activationSelectionCheckpointVerificationStatuses: {
        valid: "Checkpoint matches local state",
        divergent: "Checkpoint diverges from local state",
        invalid: "Checkpoint invalid",
      },
      activationSelectionCheckpointDiscoveryStatuses: {
        valid: "Hosted checkpoint accepted",
        invalid: "Hosted checkpoint rejected",
      },
      baselineActivationHistoryVerificationStatuses: {
        valid: "History matches local state",
        divergent: "History diverges from local state",
        invalid: "History invalid",
      },
      safety:
        "Private keys are read only at signing time. Subscription URLs stay in the local workspace snapshot for refresh; Ledger events expose only URL fingerprints and evidence hashes.",
      errors: {
        tooLarge: "Trusted receipt files must be 10 MiB or smaller.",
        directoryTooLarge:
          "Receipt trust anchor directory files must be 2 MiB or smaller.",
      },
    },
    calibration: {
      eyebrow: "HUMAN TRUTH",
      title: "Evaluator calibration",
      body: "Append reviewed verdicts to immutable model judgments, then measure exact agreement within each evaluator and rubric cohort.",
      reviewed: "Reviewed",
      agreement: "Exact agreement",
      groups: "Calibration cohorts",
      samples: "samples",
      noSamples:
        "No human truth has been recorded. Review an evaluation to establish the first calibration sample.",
      register: "Evaluation review register",
      registerHint:
        "Current truth is append-only; revising a verdict preserves every prior review.",
      unreviewed: "Awaiting review",
      agreed: "Agreed",
      disagreed: "Diverged",
      modelVerdict: "Model verdict",
      expectedVerdict: "Expected verdict",
      review: "Review",
      revise: "Revise truth",
      save: "Record truth",
      saving: "Binding review...",
      cancel: "Cancel",
      note: "Review note",
      notePlaceholder: "State the evidence behind this human judgment.",
      revision: "Truth revision",
      evaluator: "Evaluator",
      rubric: "Rubric",
      reportHash: "Report SHA-256",
      matrix: "Verdict confusion matrix",
      modelAxis: "Model",
      truthAxis: "Truth",
      verdictMarks: {
        left_better: "L",
        right_better: "R",
        tie: "T",
        inconclusive: "I",
      },
      consensus: {
        open: "Panel review",
        provenance: "Panel consensus",
        eyebrow: "INDEPENDENT SIGN-OFF",
        title: "Reviewer consensus",
        close: "Close panel",
        body: "Keep each reviewer in an independent append-only lane. Preview applies quorum and agreement policy without changing Human Truth.",
        roster: "Reviewer lanes",
        emptyRoster: "No independent ballot has been recorded.",
        reviewerId: "Reviewer lane ID",
        reviewerIdPlaceholder: "release_owner",
        reviewerName: "Display name",
        reviewerNamePlaceholder: "Release owner",
        ballotNote: "Private ballot rationale",
        ballotNotePlaceholder:
          "State the evidence behind this independent verdict.",
        clear: "Clear lane",
        record: "Record ballot",
        recording: "Binding ballot...",
        gate: "Consensus policy",
        minimumReviewers: "Minimum reviewers",
        minimumAgreement: "Minimum agreement",
        allowInconclusive: "Allow inconclusive consensus",
        preview: "Preview consensus",
        previewing: "Computing...",
        resolve: "Resolve as truth",
        resolving: "Binding truth...",
        noLeader: "No unique leader",
        agreement: "panel agreement",
        previewRequired:
          "Preview the current lanes after changing consensus policy.",
        latestResolution: "Latest resolution",
        statuses: {
          ready: "Ready to resolve",
          insufficient_reviewers: "More reviewers required",
          no_consensus: "No consensus",
          inconclusive: "Inconclusive blocked",
        },
        safety:
          "Resolution is explicit and atomic. Ballot notes stay out of Ledger events; the resulting Human Truth revision binds the consensus report SHA-256.",
      },
      empty: "Run an evaluation to create a reviewable judgment.",
      safety:
        "Human truth never overwrites model output. Every revision binds the immutable evaluation SHA-256 and remains portable with the Thread fixture.",
    },
    casebook: {
      eyebrow: "REGRESSION ARCHIVE",
      title: "Evaluation Casebooks",
      body: "Curate reviewed judgments from many Threads into append-only, hash-bound gold sets for workspace-level evaluator calibration.",
      select: "Casebook volume",
      empty: "No Evaluation Casebook has been created.",
      create: "New Casebook",
      creating: "Creating volume...",
      save: "Save metadata",
      saving: "Binding revision...",
      edit: "Edit metadata",
      cancel: "Cancel",
      name: "Casebook name",
      namePlaceholder: "Release evaluator gold set",
      description: "Scope note",
      descriptionPlaceholder:
        "Define what belongs in this reviewed evidence collection.",
      currentRevision: "Current revision",
      cases: "Gold cases",
      agreement: "Agreement",
      cohorts: "Cohorts",
      curate: "Curate reviewed evaluation",
      curateAction: "Add case",
      refreshAction: "Refresh truth",
      curating: "Binding case...",
      noReviewed:
        "This Thread has no human-reviewed evaluation available for curation.",
      upToDate: "Current truth already curated",
      source: "Source",
      modelVerdict: "Model",
      expectedVerdict: "Truth",
      truthRevision: "Truth revision",
      caseHash: "Case SHA-256",
      evaluationHash: "Evaluation SHA-256",
      consensusEvidence: "Panel evidence",
      remove: "Remove from current revision",
      confirmRemove: "Confirm removal",
      removing: "Removing case...",
      history: "Revision ledger",
      export: "Export Casebook",
      exporting: "Binding artifact...",
      reportHash: "Calibration SHA-256",
      samples: "samples",
      safety:
        "Removing or refreshing a case creates a new Casebook revision. Prior revisions retain their exact evaluation, truth, provenance, and hashes.",
      qualification: {
        eyebrow: "EXECUTABLE GOLD SET",
        title: "Evaluator qualification",
        body: "Re-judge the current manifest with a selected evaluator. Every source Run is rebuilt and checked against its frozen snapshot hashes before scoring.",
        evaluator: "Candidate evaluator",
        minimumAgreement: "Minimum exact agreement",
        allowInconclusive: "Permit verified inconclusive judgments",
        run: "Qualify evaluator",
        running: "Replaying gold set...",
        neverRun: "Not run",
        agreement: "Agreement",
        verified: "Verified evidence",
        inconclusive: "Inconclusive",
        executionHash: "Execution SHA",
        expected: "Expected",
        actual: "Actual",
        expectedLeft: "Expected L",
        observedLeft: "Observed L",
        expectedRight: "Expected R",
        observedRight: "Observed R",
        unavailable: "unavailable",
        empty:
          "No qualification is bound to this revision. Run the current gold set to create one.",
        noCases: "Curate at least one reviewed case before qualification.",
        history: "Qualification history",
        current: "Current revision",
        stale: "Prior revision",
        receipt: "Qualification receipt",
        exportingReceipt: "Binding receipt...",
        signedReceipt: "Signed receipt",
        exportingSignedReceipt: "Signing receipt...",
        promoteBaseline: "Promote baseline",
        promotingBaseline: "Pinning baseline...",
        noSigner: "Register and select a local signing anchor first.",
        baseline: "Trusted qualification baseline",
        noBaseline: "No signed baseline has been promoted.",
        baselineCurrent: "Current and trusted",
        baselineStale: "Stale Casebook revision",
        baselineRevoked: "Signer revoked",
        baselineHash: "Baseline SHA",
        signer: "Signer key",
        statuses: {
          passed: "Qualified",
          failed: "Below gate",
          inconclusive: "Inconclusive",
        },
        caseStatuses: {
          agreed: "Agreed",
          disagreed: "Diverged",
          inconclusive: "Inconclusive",
        },
        evidenceStates: {
          verified: "Source hashes verified",
          drifted: "Source evidence drifted",
          missing: "Source evidence missing",
        },
      },
      revisionSources: {
        created: "Created",
        metadata_updated: "Metadata",
        case_curated: "Case curated",
        case_refreshed: "Truth refreshed",
        case_removed: "Case removed",
      },
    },
    suite: {
      eyebrow: "QUALITY GATE",
      title: "Evaluation suites",
      body: "Replay one baseline against a bounded candidate register with a revisioned rubric and deterministic gate.",
      create: "Create suite",
      update: "Save revision",
      edit: "Edit",
      cancel: "Cancel",
      run: "Run gate",
      running: "Evaluating batch...",
      receipt: "Gate receipt",
      exportingReceipt: "Binding receipt...",
      signedReceipt: "Signed receipt",
      exportingSignedReceipt: "Signing receipt...",
      name: "Suite name",
      namePlaceholder: "Release quality gate",
      baseline: "Baseline run",
      candidates: "Candidate register",
      candidatesHint: "Select 1–8 settled Runs.",
      passRate: "Minimum non-regression",
      candidateScore: "Minimum candidate score",
      allowInconclusive: "Allow partial inconclusive cases",
      evaluator: "Evaluator",
      empty: "No durable evaluation suite has been created.",
      revision: "Revision",
      latest: "Latest gate",
      neverRun: "Not run",
      average: "Candidate mean",
      cases: "Cases",
      digest: "Batch SHA-256",
      caseEvidence: "Case evidence",
      baselineScore: "Baseline",
      candidateScoreShort: "Candidate",
      pairDigest: "Pair SHA-256",
      history: "Execution history",
      safety:
        "Every case uses immutable Run snapshots and the no-tool evaluator. Pair, batch, and receipt hashes bind the complete gate evidence.",
      statuses: {
        passed: "Passed",
        failed: "Failed",
        inconclusive: "Inconclusive",
      },
      errors: {
        candidates: "Select at least one candidate distinct from baseline.",
        maximum: "Evaluation suites accept at most 8 candidates.",
      },
    },
    verdicts: {
      left_better: "Baseline better",
      right_better: "Candidate better",
      tie: "Tie",
      inconclusive: "Inconclusive",
    },
    statuses: {
      completed: "Completed",
      failed: "Failed",
      cancelled: "Cancelled",
      interrupted: "Interrupted",
    },
    errors: {
      distinct: "Choose two distinct settled runs.",
      replayTooLarge: "Run replay snapshots must be 10 MiB or smaller.",
      replayInvalid: "Choose a valid Napier Run replay snapshot JSON file.",
      fixtureTooLarge: "Replay fixtures must be 10 MiB or smaller.",
      fixtureInvalid: "Choose a valid Napier replay fixture JSON file.",
    },
  },
  delegation: {
    eyebrow: "DELEGATION LEDGER",
    title: "Isolated tasks",
    prompt: "Task brief",
    result: "Returned evidence",
    outcome: "Typed outcome",
    error: "Failure record",
    turns: "Turns",
    steps: "Steps",
    items: "Items",
    evidence: "Evidence",
    unknowns: "Unknowns",
    envelope: "Envelope",
    receipt: "Receipt",
    verifyEvidence: "Verify evidence",
    verifyingEvidence: "Verifying...",
    verifyFailed: "Evidence verification failed.",
    reviewOutcome: "Review outcome",
    reviewingOutcome: "Reviewing...",
    reviewFailed: "Independent review failed.",
    independentReviewerRequired:
      "Select a model different from the Subagent worker to review.",
    reviewerModelUnavailable:
      "Configure this provider before using it as an independent reviewer.",
    score: "Score",
    risk: "Risk",
    reviewVerdicts: {
      accept: "Independent review accepted",
      revise: "Independent review requests revision",
      reject: "Independent review rejected",
      inconclusive: "Independent review inconclusive",
    },
    aligned: "Aligned",
    drifted: "Drifted",
    missing: "Missing",
    legacyEvidence: "Legacy outcome has no workspace hashes.",
    verificationStatuses: {
      aligned: "Current evidence aligned",
      divergent: "Evidence drift detected",
      unavailable: "Verification unavailable",
    },
    statuses: {
      pending: "Queued",
      running: "Working",
      completed: "Complete",
      failed: "Failed",
      cancelled: "Cancelled",
      timed_out: "Timed out",
    },
  },
  goal: {
    title: "Durable goal",
    empty: "Set an objective that can span multiple runs.",
    placeholder: "Define a verifiable outcome...",
    set: "Set goal",
    clear: "Clear",
    active: "Active",
    completed: "Verified",
    blocked: "Blocked",
    evidence: "Latest evidence",
    noProgress: "No progress",
    guardrail: "Napier fails closed when evidence is insufficient.",
  },
  memory: {
    title: "Reviewed memory",
    eyebrow: "CONTEXT VAULT",
    loading: "Opening reviewed memory...",
    empty: "No memories have been proposed yet.",
    proposed: "Awaiting review",
    active: "Active context",
    history: "Review history",
    stale: "Review queue",
    placeholder:
      "Record a durable fact, preference, constraint, or decision...",
    correctionPlaceholder:
      "Rewrite the fact so the corrected version can replace it...",
    consolidationPlaceholder:
      "Write one complete fact that preserves the selected source evidence...",
    draftLabel: "Memory proposal",
    correctionDraftLabel: "Corrected memory proposal",
    consolidationDraftLabel: "Consolidated memory proposal",
    categoryLabel: "Memory category",
    scopeLabel: "Memory scope",
    add: "Propose memory",
    proposeCorrection: "Propose correction",
    proposeConsolidation: "Propose consolidation",
    approve: "Approve",
    reject: "Reject",
    archive: "Archive",
    restore: "Restore",
    refresh: "Refresh",
    markStale: "Mark stale",
    correct: "Correct",
    consolidate: "Consolidate",
    sourceSelected: "Selected",
    correction: "Correcting reviewed fact",
    consolidation: "Consolidating reviewed facts",
    cancelReplacement: "Cancel",
    removeSource: "Remove consolidation source",
    consolidationNeedsSources:
      "Select at least two compatible facts before proposing a consolidation.",
    pendingReplacement: "Pending replacement",
    changeRequired: "Change the fact before proposing its replacement.",
    reviewEvery: "Review every",
    reviewIntervalLabel: "Memory review interval in days",
    days: "days",
    review: "Review due",
    uses: "Runs used",
    lastUsed: "Last used",
    notScheduled: "On approval",
    never: "Never",
    corrects: "Corrects",
    consolidates: "Consolidates",
    supersededBy: "Superseded by",
    live: "LIVE",
    dueShort: "DUE",
    workspace: "Workspace",
    agent: "This agent",
    safety:
      "Only approved, in-date facts enter model context. Corrections and consolidations preserve every source as immutable review evidence.",
    errors: {
      consolidationScope: "Memory consolidation must preserve scope and Agent.",
      consolidationLimit: "Memory consolidation accepts at most 8 sources.",
    },
  },
  recovery: recoveryCopy,
  context: {
    loading: "Opening Agent configuration...",
    observe: "Observe only",
    liveProvider: "Live provider",
    demoProvider: "Demo provider",
  },
  workspaceSurface: {
    section: "Workspace",
    sectionDescription: "Local folder this runtime operates on",
    currentRoot: "Active folder",
    dataRoot: "Ledger data root",
    inputLabel: "Switch to another folder",
    placeholder: "/absolute/path/to/project",
    submit: "Switch folder",
    switching: "Switching workspace...",
    warning:
      "Switching rebuilds the runtime on the new folder and shows that folder's own ledgers. This folder's ledgers stay intact and return if you switch back. Not allowed while a run is active.",
    chipLabel: "Workspace",
  },
  welcome: {
    eyebrow: "A glass-box agent runtime",
    title: "Work that leaves evidence.",
    body: "Napier turns conversations into durable ledgers: every model call, tool action, branch, goal, and artifact stays inspectable.",
    firstPrompt:
      "Ask Napier to inspect this workspace and propose the highest-leverage next step.",
  },
  notices: {
    demo: "Demo model",
    demoDetail: "Add a provider key on the server to run a live model.",
    disconnected: "The workspace could not be loaded.",
  },
  language: {
    section: "Language",
    sectionDescription: "Interface display language",
    chinese: "中文",
    english: "English",
    current: "Current language",
  },
  narrative: {
    blockedBy: "Blocked by",
    next: "Next",
    browserControls: "Browser controls",
    stop: "Stop",
  },
  projects: {
    heading: "Projects",
    switching: "Switching workspace...",
    current: "Current",
  },
} as const;

export type Copy = typeof en;

export const copy: Copy = deepMergeCopy(en, getLocale() === "zh" ? zh : {});
