export const deepTraceCopyZh = {
  otel: {
    eyebrow: "厂商中立轨迹",
    title: "OpenTelemetry 导出",
    body: "将此 Ledger 投影为 OTLP/JSON Span，供 Collector、Jaeger、Tempo 或其他兼容后端使用。",
    scope: "导出范围",
    threadScope: "完整会话",
    runScope: "单次运行",
    export: "导出 OTLP 轨迹",
    exporting: "正在绑定 Span……",
    exported: "OTLP 轨迹已导出",
    verify: "验证归档 JSON",
    verifying: "正在检查归档……",
    verified: "OTLP 轨迹已验证",
    invalid: "OTLP 轨迹无效",
    noDiagnostics: "无诊断信息",
    spans: "Span",
    events: "事件",
    eventAnchor: "事件锚点",
    safety:
      "仅元数据导出会排除 Prompt、补全、推理、工具输入输出、备注、证据文本和凭据定位信息。",
    errors: {
      artifactTooLarge: "OTLP 轨迹 Artifact 超过 10 MiB。",
      artifactInvalid: "OTLP 轨迹 Artifact 必须是有效 JSON。",
    },
  },
  summary: {
    eyebrow: "摘要边界",
    title: "轨迹摘要覆盖",
    genericTypes: "通用回退",
    noGeneric: "此事件集中没有通用回退。",
    receipt: "回执",
    verificationPending: "正在验证回执",
    verificationValid: "回执已验证",
    verificationInvalid: "回执无效",
    noDiagnostics: "无诊断信息",
    sources: {
      bounded: "已限制",
      fixed: "固定摘要",
      category: "分类摘要",
      generic: "通用摘要",
    },
  },
} as const;

export const delegationCopyZh = {
  eyebrow: "委派记录",
  title: "隔离任务",
  prompt: "任务简报",
  result: "返回证据",
  outcome: "类型化结果",
  error: "失败记录",
  turns: "轮次",
  steps: "步骤",
  items: "项目",
  evidence: "证据",
  unknowns: "未知项",
  envelope: "信封",
  receipt: "回执",
  verifyEvidence: "验证证据",
  verifyingEvidence: "正在验证……",
  verifyFailed: "证据验证失败。",
  reviewOutcome: "审查结果",
  reviewingOutcome: "正在审查……",
  reviewFailed: "独立审查失败。",
  independentReviewerRequired: "请选择与子智能体工作模型不同的模型进行审查。",
  reviewerModelUnavailable:
    "将此 Provider 配置完成后才能作为独立审查模型使用。",
  score: "评分",
  risk: "风险",
  reviewVerdicts: {
    accept: "独立审查已接受",
    revise: "独立审查要求修订",
    reject: "独立审查已拒绝",
    inconclusive: "独立审查无结论",
  },
  aligned: "一致",
  drifted: "已漂移",
  missing: "缺失",
  legacyEvidence: "旧版结果没有工作区哈希。",
  verificationStatuses: {
    aligned: "当前证据一致",
    divergent: "检测到证据漂移",
    unavailable: "验证不可用",
  },
  statuses: {
    pending: "已排队",
    running: "工作中",
    completed: "已完成",
    failed: "失败",
    cancelled: "已取消",
    timed_out: "已超时",
  },
} as const;

export const memoryCopyZh = {
  title: "已评审记忆",
  eyebrow: "上下文仓库",
  loading: "正在打开已评审记忆……",
  empty: "尚未提议记忆。",
  proposed: "等待评审",
  active: "活动上下文",
  history: "评审历史",
  stale: "评审队列",
  placeholder: "记录持久事实、偏好、约束或决定……",
  correctionPlaceholder: "重写该事实，使修正版可以替换它……",
  consolidationPlaceholder: "编写一个保留所选来源证据的完整事实……",
  draftLabel: "记忆提议",
  correctionDraftLabel: "修正记忆提议",
  consolidationDraftLabel: "合并记忆提议",
  categoryLabel: "记忆类别",
  scopeLabel: "记忆范围",
  add: "提议记忆",
  proposeCorrection: "提议修正",
  proposeConsolidation: "提议合并",
  approve: "批准",
  reject: "拒绝",
  archive: "归档",
  restore: "恢复",
  refresh: "刷新",
  markStale: "标记为待复核",
  correct: "修正",
  consolidate: "合并",
  sourceSelected: "已选择",
  correction: "正在修正已评审事实",
  consolidation: "正在合并已评审事实",
  cancelReplacement: "取消",
  removeSource: "移除合并来源",
  consolidationNeedsSources: "提议合并前，请至少选择两个兼容事实。",
  pendingReplacement: "等待替换",
  changeRequired: "提议替换前，请修改事实内容。",
  reviewEvery: "每隔",
  reviewIntervalLabel: "记忆复核间隔天数",
  days: "天复核",
  review: "需要复核",
  uses: "使用运行数",
  lastUsed: "最近使用",
  notScheduled: "批准时",
  never: "从未",
  corrects: "修正对象",
  consolidates: "合并来源",
  supersededBy: "替代项",
  live: "生效中",
  dueShort: "待复核",
  workspace: "工作区",
  agent: "当前智能体",
  safety:
    "只有已批准且未过期的事实会进入模型上下文。修正和合并会把每个来源保留为不可变评审证据。",
  errors: {
    consolidationScope: "记忆合并必须保留范围与智能体。",
    consolidationLimit: "记忆合并最多接收 8 个来源。",
  },
} as const;
