export const desktopWorkbenchCopy = {
  taskView: {
    eyebrow: "TASK WORKSPACE",
    title: "Task",
    body: "Intent, work products, active runtime, and validation for this task.",
    sections: {
      overview: "Overview",
      changes: "Changes",
      environment: "Runtime environment",
      validation: "Validation",
    },
    overview: {
      objective: "Goal",
      progress: "Progress",
      artifacts: "Work products",
      complete: "complete",
      current: "Current step",
      completedSteps: "Completed steps",
      upcomingSteps: "Upcoming steps",
      planStatus: {
        active: "Running",
        completed: "Completed",
        blocked: "Blocked",
        cancelled: "Cancelled",
      },
      noPlan: "No execution plan has been recorded for this task yet.",
      noGoal: "Add a durable goal when this task should continue across runs.",
      addGoal: "Add durable goal",
      saveGoal: "Save goal",
      clearGoal: "Clear goal",
      continue: "Continue task",
      decisionEyebrow: "WAITING FOR INPUT",
      decisionNext:
        "The previous run is complete. Record an answer, then start the linked continuation.",
      reviewDecision: "Review decision",
      stepStatus: {
        pending: "Pending",
        ready: "Ready",
        running: "Running",
        partial: "Partial",
        completed: "Completed",
        blocked: "Blocked",
        skipped: "Skipped",
      },
    },
    changes: {
      title: "Changes and outputs",
      body: "Files, artifacts, and references produced for the current task.",
      empty: "No task changes or outputs have been recorded yet.",
      recovery: "Recovery",
      recoveryBody: "Restore workspace items moved to Napier trash.",
      references: "References",
    },
    environment: {
      title: "Runtime environment",
      body: "Active browser, process, and Sandbox resources for this task.",
      browser: "Browser",
      process: "Processes",
      sandbox: "Sandbox",
      empty: "No runtime resource is active for this task.",
    },
    validation: {
      title: "Validation",
      body: "Direct evidence from verification receipts, diagnostics, and the artifact ledger.",
      latestRun: "Latest run",
      checks: "Validation matrix",
      empty: "No validation evidence has been recorded yet.",
      passed: "Verified",
      failed: "Failed",
      warning: "Warning",
      unknown: "Unknown",
      stale: "Evidence predates a later workspace write",
      source: "Source",
      evidence: "Evidence",
      checksByKind: {
        typecheck: "Typecheck",
        tests: "Tests",
        diagnostics: "Lint / diagnostics",
        artifact: "Artifacts",
      },
      sources: {
        receipt: "Verification receipt",
        lsp: "LSP",
        ledger: "Ledger",
      },
      noEvidence: "No direct evidence recorded",
      exitCode: "exit",
      duration: "duration",
      diagnostics: "diagnostics",
      errors: "errors",
      warnings: "warnings",
      artifactCounts:
        "verified {verified} · produced {produced} · missing {missing} · total {total}",
    },
    status: {
      queued: "Queued",
      running: "Running",
      waiting: "Waiting",
      completed: "Completed",
      failed: "Failed",
      cancelled: "Cancelled",
      interrupted: "Interrupted",
      pending: "Pending",
      ready: "Ready",
      partial: "Partial",
      blocked: "Blocked",
      skipped: "Skipped",
      candidate: "Candidate",
      produced: "Produced",
      verified: "Verified",
      missing: "Missing",
      superseded: "Superseded",
    },
    duration: {
      minute: "m",
      second: "s",
    },
  },
  trace: {
    title: "Run trajectory",
    empty: "Events will appear here as the run unfolds.",
    emptyTitle: "No trajectory recorded",
    mapEyebrow: "Execution cartography",
    body: "Readable actions first, with the complete privacy-bounded audit one switch away.",
    plotting: "Plotting",
    recorded: "Recorded",
    elapsed: "Elapsed",
    turns: "Turns",
    calls: "Calls",
    keyActions: "Key actions",
    sequence: "SEQ",
    showEarlier: "Show earlier events",
    evidenceTitle: "Evidence and diagnostics",
    evidenceBody:
      "Export receipts, summary coverage, model context, reviews, and delegation records.",
    harness: {
      eyebrow: "MODEL HARNESS",
      title: "Resolved model strategy",
      empty: "No model Harness decision has been recorded for this task.",
      profile: "Prompt dialect",
      intent: "Task intent",
      tools: "Visible tools",
      saved: "Schema saved",
      retries: "Retries",
      model: "Model",
      omitted: "Deferred tools",
      none: "None",
      receipt: "Receipt",
      intents: {
        browser: "Browser",
        coding: "Coding",
        data: "Data",
        research: "Research",
        general: "General",
      },
    },
    modelAdapter: {
      eyebrow: "MODEL ADAPTER",
      title: "Provider request policies",
      empty: "No Model Adapter selection has been recorded for this task.",
      api: "API",
      cache: "Cache",
      source: "Source",
      streamCap: "Stream cap",
      modelCap: "Model cap",
      tokenSource: "Token source",
      adapter: "Adapter",
      legacy: "Legacy unavailable",
      receipt: "Receipt",
    },
    contextEnvelope: {
      eyebrow: "MODEL CONTEXT",
      title: "Provider request envelopes",
      empty: "No model context envelope has been recorded for this task.",
      turn: "Turn",
      messages: "Messages",
      users: "Users",
      assistants: "Assistants",
      toolResults: "Tool results",
      other: "Other",
      promptBytes: "Prompt bytes",
      toolCount: "Tools",
      toolSchemaBytes: "Tool schema bytes",
      toolSchemaTokens: "Tool schema est.",
      prompt: "Prompt",
      messageSet: "Messages",
      toolNames: "Tool names",
      toolDefinitions: "Tool definitions",
      response: "Response",
      responseMissing: "No bound response",
      stop: "Stop",
      receipt: "Receipt",
    },
    contextPruning: {
      eyebrow: "CONTEXT PRUNING",
      title: "Tool-result context budget",
      empty: "No tool-result context decision has been recorded for this task.",
      attempt: "Attempt",
      results: "Results",
      replaced: "Compacted",
      saved: "Text saved",
      active: "Active text",
      superseded: "Superseded",
      repeated: "Repeated errors",
      large: "Large outputs",
      emptyResults: "Empty results",
      context: "Context set",
      receipt: "Receipt",
    },
    contextContinuity: {
      eyebrow: "CONTEXT CONTINUITY",
      title: "Compaction handoff boundary",
      empty:
        "No context-compaction checkpoint has been recorded for this task.",
      coverage: "Compacted range",
      retained: "Live history from",
      messages: "Source messages",
      executionEvents: "Execution events",
      decisions: "Decisions",
      openLoops: "Open loops",
      artifacts: "Artifacts",
      executionBinding: "Execution binding",
      messageBinding: "Message binding",
      summary: "Summary binding",
      unavailable: "Legacy unavailable",
      states: {
        bound: "Execution state bound",
        legacy_unbound: "Legacy message-only checkpoint",
      },
    },
    otel: {
      eyebrow: "VENDOR-NEUTRAL TRACE",
      title: "OpenTelemetry export",
      body: "Project this ledger into OTLP/JSON spans for Collector, Jaeger, Tempo, or another compatible backend.",
      scope: "Export scope",
      threadScope: "Complete Thread",
      runScope: "Single Run",
      export: "Export OTLP trace",
      exporting: "Binding spans...",
      exported: "OTLP trace exported",
      verify: "Verify archived JSON",
      verifying: "Checking archive...",
      verified: "OTLP trace verified",
      invalid: "OTLP trace invalid",
      noDiagnostics: "No diagnostics",
      spans: "Spans",
      events: "Events",
      eventAnchor: "Event anchor",
      safety:
        "Metadata-only export excludes prompts, completions, reasoning, tool I/O, notes, evidence text, and credential locators.",
      errors: {
        artifactTooLarge: "OTLP trace artifact is larger than 10 MiB.",
        artifactInvalid: "OTLP trace artifact must be valid JSON.",
      },
    },
    summary: {
      eyebrow: "SUMMARY BOUNDARY",
      title: "Trace summary coverage",
      genericTypes: "Generic fallback",
      noGeneric: "No generic fallback in this event set.",
      receipt: "Receipt",
      verificationPending: "Verifying receipt",
      verificationValid: "Receipt verified",
      verificationInvalid: "Receipt invalid",
      noDiagnostics: "No diagnostics",
      sources: {
        bounded: "Bounded",
        fixed: "Fixed",
        category: "Category",
        generic: "Generic",
      },
    },
  },
  settingsSurface: {
    eyebrow: "Persistent preferences",
    title: "Settings",
    body: "Configuration that survives beyond a single conversation or Run.",
    close: "Close settings",
    sectionsLabel: "Settings sections",
    contextSection: "Agent & Model",
    contextSectionDescription: "Providers, policies, skills and credentials",
    memorySection: "Memory",
    memorySectionDescription: "Workspace knowledge and review cadence",
    extensionsSection: "Extensions",
    extensionsSectionDescription: "MCP and plugin capability overview",
    automationsSection: "Automations",
    automationsSectionDescription: "Workspace schedules and inbound channels",
    developerSection: "Developer",
    developerSectionDescription:
      "Experiments, fixtures, trials and workflow tools",
    developerIntro:
      "Advanced diagnostics and governance controls stay outside the ordinary task path.",
    runLab: "Run lab and evaluations",
    contextCompaction: {
      eyebrow: "CONTEXT CHECKPOINT",
      title: "Compaction preview and fork",
      body: "Inspect a model-generated checkpoint before applying it to a new Thread. The source Ledger is never rewritten.",
      forkOnly: "Fork only",
      retainedMessages: "Recent messages to retain",
      source: "Preview source",
      messages: "messages",
      messagesCompacted: "messages summarized",
      previewAction: "Generate preview",
      previewing: "Generating…",
      previewReady: "PREVIEW READY",
      summary: "Checkpoint summary",
      decisions: "Decisions",
      openLoops: "Open loops",
      artifacts: "Artifacts",
      none: "None recorded.",
      range: "Source range",
      retainedFrom: "Raw history from",
      continuity: "Continuity events",
      sourceHash: "Source set",
      forkTitle: "New Thread title",
      applyAction: "Create compacted fork",
      applying: "Creating fork…",
      applyNote:
        "Apply is single-use and fails closed if the source Ledger changed after preview.",
      noThread: "Open a Thread to preview compaction.",
      modelUnavailable: "Select a configured provider model.",
      notEnoughMessages: "At least three messages are required.",
      runActive: "Wait for the active Run to finish.",
      untitledThread: "Untitled Thread",
    },
    workflowStudio: "Workflow studio",
    productTrial: "Product trial recorder",
    designSection: "Design system",
    designSectionDescription: "Tokens, components and interaction states",
    designShowcase: {
      tokenEyebrow: "DESIGN.md / TOKENS",
      colors: "Semantic colors",
      colorLabels: {
        accent: "Accent",
        success: "Success",
        warning: "Warning",
        danger: "Danger",
        surface: "Surface",
        muted: "Muted",
      },
      typography: "Typography",
      headingSample: "Reliable work, clearly explained.",
      bodySample:
        "Napier keeps the task readable while evidence stays one deliberate interaction away.",
      technicalSample: "Model, tool, and trajectory annotations",
      controls: "Controls",
      primaryAction: "Primary action",
      secondaryAction: "Secondary action",
      disabledAction: "Disabled action",
      taskName: "Task name",
      taskNameValue: "Desktop workbench",
      fieldHelp: "Inputs expose label, value, help, and focus state.",
      states: "Task states",
      stateLabels: {
        ready: "Ready",
        working: "Working",
        waiting: "Waiting",
        failed: "Failed",
        completed: "Completed",
      },
      emptyStateLabel: "Empty state example",
      emptyStateTitle: "No artifacts yet",
      emptyStateBody:
        "Outputs appear here after the task produces durable work.",
    },
  },
  developerWorkbench: {
    eyebrow: "Advanced control plane",
    title: "Developer Workbench",
    body: "Automation, evaluation, publishing, and design controls for deliberate operator workflows.",
    close: "Close Developer Workbench",
    sectionsLabel: "Developer Workbench sections",
    open: "Developer Workbench",
    automationsSection: "Automations",
    automationsSectionDescription: "Schedules, inbound channels and recovery",
    labSection: "Lab & workflow",
    labSectionDescription: "Evaluations, fixtures, trust and product trials",
    publishingSection: "Publishing",
    publishingSectionDescription:
      "Publishers, signatures, rollout and deployment",
    designSection: "Design system",
    designSectionDescription: "Tokens, components and interaction states",
    extensionPublishingEyebrow: "EXTENSION DELIVERY",
    extensionPublishingTitle: "Extension publishing governance",
    extensionPublishingBody:
      "Sign, verify, release, update, and deploy extension packages through explicit review gates.",
    agentPublishingEyebrow: "AGENT DELIVERY",
    agentPublishingTitle: "Agent package publishing",
    agentPublishingBody:
      "Create and inspect signed Skill and Prompt packages outside ordinary Agent configuration.",
  },
  modelPicker: {
    title: "Choose a model",
    searchLabel: "Search models",
    searchPlaceholder: "Search provider or model…",
    showUnavailable: "Show unavailable models",
    configured: "Credential ready",
    unavailable: "Not configured",
    context: "context",
    reasoning: "Reasoning",
    vision: "Vision",
    recommended: "Agent default",
    recent: "Recently used",
    empty: "No models match this search.",
    setupChecking: "Checking this workspace…",
    setupCheckingBody:
      "Looking for reusable server-side credential locations without reading or displaying their values.",
    setupTitle: "Live credentials found",
    setupBody:
      "This workspace keeps its own model permissions. Enable a provider to use its models here; only the credential location is saved.",
    setupMissingTitle: "No live model is enabled",
    setupMissingBody:
      "Add a provider credential in Agent & Model settings, then check again.",
    enable: "Enable",
    enabling: "Enabling…",
    retrySetup: "Check again",
    openSettings: "Model settings",
  },
  workspaceSurface: {
    section: "Workspace",
    sectionDescription: "Local folder this runtime operates on",
    currentRoot: "Active folder",
    dataRoot: "Ledger data root",
    inputLabel: "Switch to another folder",
    placeholder: "/absolute/path/to/project",
    submit: "Switch folder",
    switching: "Switching workspace...",
    warning:
      "Switching rebuilds the runtime on the new folder and shows that folder's own ledgers. This folder's ledgers stay intact and return if you switch back. Not allowed while a run is active.",
    chipLabel: "Workspace",
  },
  welcome: {
    title: "What would you like to accomplish?",
    body: "Describe the outcome. Napier keeps the plan, actions, and evidence together.",
    cue: "Start with a common task",
    starters: {
      inspect: {
        title: "Understand this project",
        body: "Map its structure, entry points, and risks",
        prompt:
          "Inspect this workspace and explain its architecture, primary entry points, and highest-risk areas.",
      },
      build: {
        title: "Build a feature",
        body: "Plan, implement, and verify a scoped change",
        prompt:
          "Help me implement a feature in this workspace. Start by understanding the existing structure, then propose a focused plan.",
      },
      debug: {
        title: "Diagnose a problem",
        body: "Reproduce the issue and confirm its cause",
        prompt:
          "Help me diagnose a problem in this project. Reproduce it, identify the root cause, then propose and verify a fix.",
      },
      review: {
        title: "Review current changes",
        body: "Check correctness, risks, and regressions",
        prompt:
          "Review the uncommitted changes in this workspace for correctness, risks, and missing test coverage.",
      },
      test: {
        title: "Strengthen the tests",
        body: "Find valuable gaps and add coverage",
        prompt:
          "Inspect this project's test suite, identify the most valuable coverage gaps, and add focused tests.",
      },
      plan: {
        title: "Turn a goal into a plan",
        body: "Define steps, checks, and deliverables",
        prompt:
          "Turn my goal into an executable plan with concrete steps, verification criteria, and final deliverables.",
      },
    },
  },
  notices: {
    demo: "Demo model",
    demoDetail: "Add a provider key on the server to run a live model.",
    disconnected: "The workspace could not be loaded.",
  },
  language: {
    section: "Language",
    sectionDescription: "Interface display language",
    chinese: "中文",
    english: "English",
    current: "Current language",
  },
} as const;
