export const desktopWorkbenchCopy = {
  taskView: {
    eyebrow: "TASK WORKSPACE",
    title: "Task",
    body: "Intent, work products, active runtime, and validation for this task.",
    sections: {
      overview: "Overview",
      changes: "Changes",
      environment: "Runtime environment",
      validation: "Validation",
    },
    overview: {
      objective: "Goal",
      progress: "Progress",
      artifacts: "Work products",
      complete: "complete",
      current: "Current step",
      completedSteps: "Completed steps",
      upcomingSteps: "Upcoming steps",
      planStatus: {
        active: "Running",
        completed: "Completed",
        blocked: "Blocked",
        cancelled: "Cancelled",
      },
      noPlan: "No execution plan has been recorded for this task yet.",
      noGoal: "Add a durable goal when this task should continue across runs.",
      addGoal: "Add durable goal",
      saveGoal: "Save goal",
      clearGoal: "Clear goal",
      continue: "Continue task",
    },
    changes: {
      title: "Changes and outputs",
      body: "Files, artifacts, and references produced for the current task.",
      empty: "No task changes or outputs have been recorded yet.",
      recovery: "Recovery",
      recoveryBody: "Restore workspace items moved to Napier trash.",
      references: "References",
    },
    environment: {
      title: "Runtime environment",
      body: "Active browser, process, and Sandbox resources for this task.",
      browser: "Browser",
      process: "Processes",
      sandbox: "Sandbox",
      empty: "No runtime resource is active for this task.",
    },
    validation: {
      title: "Validation",
      body: "Task checks and evidence without internal receipts or experiment controls.",
      latestRun: "Latest run",
      checks: "Plan checks",
      empty: "No validation evidence has been recorded yet.",
      passed: "Verified",
      pending: "Pending",
    },
    status: {
      queued: "Queued",
      running: "Running",
      waiting: "Waiting",
      completed: "Completed",
      failed: "Failed",
      cancelled: "Cancelled",
      interrupted: "Interrupted",
      pending: "Pending",
      ready: "Ready",
      partial: "Partial",
      blocked: "Blocked",
      skipped: "Skipped",
      candidate: "Candidate",
      produced: "Produced",
      verified: "Verified",
      missing: "Missing",
      superseded: "Superseded",
    },
    duration: {
      minute: "m",
      second: "s",
    },
  },
  trace: {
    title: "Run trajectory",
    empty: "Events will appear here as the run unfolds.",
    emptyTitle: "No trajectory recorded",
    mapEyebrow: "Execution cartography",
    body: "Readable actions first, with the complete privacy-bounded audit one switch away.",
    plotting: "Plotting",
    recorded: "Recorded",
    elapsed: "Elapsed",
    turns: "Turns",
    calls: "Calls",
    keyActions: "Key actions",
    sequence: "SEQ",
    showEarlier: "Show earlier events",
    evidenceTitle: "Evidence and diagnostics",
    evidenceBody:
      "Export receipts, summary coverage, model context, reviews, and delegation records.",
    harness: {
      eyebrow: "MODEL HARNESS",
      title: "Resolved model strategy",
      empty: "No model Harness decision has been recorded for this task.",
      profile: "Prompt dialect",
      intent: "Task intent",
      tools: "Visible tools",
      saved: "Schema saved",
      retries: "Retries",
      model: "Model",
      omitted: "Deferred tools",
      none: "None",
      receipt: "Receipt",
      intents: {
        browser: "Browser",
        coding: "Coding",
        data: "Data",
        research: "Research",
        general: "General",
      },
    },
    modelAdapter: {
      eyebrow: "MODEL ADAPTER",
      title: "Provider request policies",
      empty: "No Model Adapter selection has been recorded for this task.",
      api: "API",
      cache: "Cache",
      source: "Source",
      streamCap: "Stream cap",
      modelCap: "Model cap",
      tokenSource: "Token source",
      adapter: "Adapter",
      legacy: "Legacy unavailable",
      receipt: "Receipt",
    },
    contextEnvelope: {
      eyebrow: "MODEL CONTEXT",
      title: "Provider request envelopes",
      empty: "No model context envelope has been recorded for this task.",
      turn: "Turn",
      messages: "Messages",
      users: "Users",
      assistants: "Assistants",
      toolResults: "Tool results",
      other: "Other",
      promptBytes: "Prompt bytes",
      toolCount: "Tools",
      toolSchemaBytes: "Tool schema bytes",
      toolSchemaTokens: "Tool schema est.",
      prompt: "Prompt",
      messageSet: "Messages",
      toolNames: "Tool names",
      toolDefinitions: "Tool definitions",
      response: "Response",
      responseMissing: "No bound response",
      stop: "Stop",
      receipt: "Receipt",
    },
    contextPruning: {
      eyebrow: "CONTEXT PRUNING",
      title: "Tool-result context budget",
      empty: "No tool-result context decision has been recorded for this task.",
      attempt: "Attempt",
      results: "Results",
      replaced: "Compacted",
      saved: "Text saved",
      active: "Active text",
      superseded: "Superseded",
      repeated: "Repeated errors",
      large: "Large outputs",
      emptyResults: "Empty results",
      context: "Context set",
      receipt: "Receipt",
    },
    contextContinuity: {
      eyebrow: "CONTEXT CONTINUITY",
      title: "Compaction handoff boundary",
      empty:
        "No context-compaction checkpoint has been recorded for this task.",
      coverage: "Compacted range",
      retained: "Live history from",
      messages: "Source messages",
      executionEvents: "Execution events",
      decisions: "Decisions",
      openLoops: "Open loops",
      artifacts: "Artifacts",
      executionBinding: "Execution binding",
      messageBinding: "Message binding",
      summary: "Summary binding",
      unavailable: "Legacy unavailable",
      states: {
        bound: "Execution state bound",
        legacy_unbound: "Legacy message-only checkpoint",
      },
    },
    otel: {
      eyebrow: "VENDOR-NEUTRAL TRACE",
      title: "OpenTelemetry export",
      body: "Project this ledger into OTLP/JSON spans for Collector, Jaeger, Tempo, or another compatible backend.",
      scope: "Export scope",
      threadScope: "Complete Thread",
      runScope: "Single Run",
      export: "Export OTLP trace",
      exporting: "Binding spans...",
      exported: "OTLP trace exported",
      verify: "Verify archived JSON",
      verifying: "Checking archive...",
      verified: "OTLP trace verified",
      invalid: "OTLP trace invalid",
      noDiagnostics: "No diagnostics",
      spans: "Spans",
      events: "Events",
      eventAnchor: "Event anchor",
      safety:
        "Metadata-only export excludes prompts, completions, reasoning, tool I/O, notes, evidence text, and credential locators.",
      errors: {
        artifactTooLarge: "OTLP trace artifact is larger than 10 MiB.",
        artifactInvalid: "OTLP trace artifact must be valid JSON.",
      },
    },
    summary: {
      eyebrow: "SUMMARY BOUNDARY",
      title: "Trace summary coverage",
      genericTypes: "Generic fallback",
      noGeneric: "No generic fallback in this event set.",
      receipt: "Receipt",
      verificationPending: "Verifying receipt",
      verificationValid: "Receipt verified",
      verificationInvalid: "Receipt invalid",
      noDiagnostics: "No diagnostics",
      sources: {
        bounded: "Bounded",
        fixed: "Fixed",
        category: "Category",
        generic: "Generic",
      },
    },
  },
  settingsSurface: {
    eyebrow: "Workspace configuration",
    title: "Settings",
    body: "Configuration that survives beyond a single conversation or Run.",
    close: "Close settings",
    sectionsLabel: "Settings sections",
    contextSection: "Agent & Model",
    contextSectionDescription: "Providers, policies, skills and credentials",
    memorySection: "Memory",
    memorySectionDescription: "Workspace knowledge and review cadence",
    extensionsSection: "Extensions",
    extensionsSectionDescription: "MCP, packages and trust",
    automationsSection: "Automations",
    automationsSectionDescription: "Workspace schedules and inbound channels",
    developerSection: "Developer",
    developerSectionDescription:
      "Experiments, fixtures, trials and workflow tools",
    developerIntro:
      "Advanced diagnostics and governance controls stay outside the ordinary task path.",
    runLab: "Run lab and evaluations",
    workflowStudio: "Workflow studio",
    productTrial: "Product trial recorder",
    designSection: "Design system",
    designSectionDescription: "Tokens, components and interaction states",
    designShowcase: {
      tokenEyebrow: "DESIGN.md / TOKENS",
      colors: "Semantic colors",
      colorLabels: {
        accent: "Accent",
        success: "Success",
        warning: "Warning",
        danger: "Danger",
        surface: "Surface",
        muted: "Muted",
      },
      typography: "Typography",
      headingSample: "Reliable work, clearly explained.",
      bodySample:
        "Napier keeps the task readable while evidence stays one deliberate interaction away.",
      technicalSample: "Model, tool, and trajectory annotations",
      controls: "Controls",
      primaryAction: "Primary action",
      secondaryAction: "Secondary action",
      disabledAction: "Disabled action",
      taskName: "Task name",
      taskNameValue: "Desktop workbench",
      fieldHelp: "Inputs expose label, value, help, and focus state.",
      states: "Task states",
      stateLabels: {
        ready: "Ready",
        working: "Working",
        waiting: "Waiting",
        failed: "Failed",
        completed: "Completed",
      },
      emptyStateLabel: "Empty state example",
      emptyStateTitle: "No artifacts yet",
      emptyStateBody:
        "Outputs appear here after the task produces durable work.",
    },
  },
} as const;
