import { extensionCopyZh } from "./extension-copy.zh";
import { deepMergeCopy, getLocale } from "./locale";

export const extensionCopyEn = {
  eyebrow: "CAPABILITY REGISTRY",
  title: "Reviewed extensions",
  loading: "Opening capability registry...",
  empty: "No external capabilities have been proposed.",
  name: "Server name",
  namePlaceholder: "Research records",
  transport: "Transport",
  http: "Streamable HTTP",
  stdio: "Sandboxed stdio",
  url: "Streamable HTTP URL",
  urlPlaceholder: "https://example.com/mcp",
  headerName: "Header name (optional)",
  headerNamePlaceholder: "Authorization",
  headerEnv: "Credential env var (optional)",
  headerEnvPlaceholder: "RESEARCH_MCP_TOKEN",
  command: "Absolute executable",
  commandPlaceholder: "/opt/napier/bin/records-mcp",
  args: "Arguments (one per line)",
  argsPlaceholder: "--stdio\n--format=json",
  cwd: "Workspace cwd (optional)",
  cwdPlaceholder: "services/records",
  envTarget: "Child variable (optional)",
  envTargetPlaceholder: "MCP_TOKEN",
  envSource: "Source env variable (optional)",
  envSourcePlaceholder: "RECORDS_SOURCE_TOKEN",
  requestedAccess: "Tool effects",
  sandboxAccess: "Sandbox access",
  network: "Network outbound",
  workspaceRead: "Workspace read",
  workspaceWrite: "Workspace write",
  derivedAccess: "Derived transport gates",
  processDerived: "process.spawn",
  secretDerived: "secrets.env",
  cwdDerived: "cwd implies workspace.read",
  trust: "Trust",
  connection: "Connection",
  effect: "Effect",
  read: "External read",
  write: "External write",
  unknown: "Unclassified",
  propose: "Propose connection",
  approve: "Approve source",
  reject: "Reject",
  connect: "Connect & discover",
  disconnect: "Disconnect",
  enable: "Enable for agent",
  disable: "Disable for agent",
  tools: "Discovered tools",
  noTools: "Connect the approved source to discover tools.",
  approveRead: "Approve read",
  approveWrite: "Approve write",
  routingHint: "Routing hint",
  routingHintPlaceholder:
    "When should the Agent choose this tool? Keep it local and reviewed.",
  revoke: "Revoke",
  schema: "Schema",
  provenance: "Provenance",
  capabilities: "Capabilities",
  activeTools: "approved tools",
  plugins: {
    eyebrow: "FIRST-PARTY PLUGINS",
    title: "Kernel capabilities",
    body: "Built-in capabilities use versioned manifests and the same owner-scoped Kernel lifecycle. Disablement removes their services, hooks, and projections.",
    empty: "No first-party plugins are installed.",
    enabled: "Enabled",
    disabled: "Disabled",
    contributes: "Contributes",
    permissions: "Permissions",
    dependencies: "Dependencies",
    host: "Host",
    client: "Client",
    noPermissions: "No additional permissions",
    noDependencies: "No plugin dependencies",
  },
  mappingCount: "explicit env mappings",
  stdioSafety:
    "No shell is used. The executable must be absolute; cwd stays inside the workspace; child variables map only from named server environment variables.",
  safety:
    "Connection trust, tool effects, and agent enablement are separate gates. Stdio starts only through a supported OS sandbox with explicit process capabilities.",
  packages: {
    eyebrow: "SIGNED PACKAGE PROVENANCE",
    title: "Publisher & package desk",
    body: "Freeze publisher identity, transport, capabilities, tool schemas, reviewed effects, and the local stdio executable digest into an Ed25519 envelope.",
    anchors: "Publisher keys",
    emptyAnchors: "No publisher keys registered.",
    signing: "Local signer",
    verifyOnly: "Verify only",
    trusted: "Trusted",
    revoked: "Revoked",
    revoke: "Revoke key",
    confirmRevoke: "Confirm revoke",
    cancel: "Cancel",
    addPublisher: "Register publisher",
    addPublisherBusy: "Registering...",
    label: "Key label",
    labelPlaceholder: "Release publisher",
    source: "Key source",
    environment: "Environment signer",
    publicKey: "SPKI public key",
    environmentVariable: "Private key environment variable",
    environmentPlaceholder: "NAPIER_EXTENSION_SIGNING_KEY",
    publicKeySpki: "Ed25519 SPKI PEM",
    publicKeyPlaceholder: "-----BEGIN PUBLIC KEY-----",
    signingTitle: "Issue signed package",
    signingBody:
      "Only a ready catalog with every tool effect reviewed can be signed.",
    extension: "Reviewed Extension",
    signingAnchor: "Signing key",
    publisher: "Publisher",
    publisherPlaceholder: "Example Labs",
    dependencies: "Signed dependencies (optional)",
    dependenciesPlaceholder:
      "research_core@^2.1.0\nartifact_store@>=1.4.0 <2.0.0",
    dependenciesHint:
      "One canonical package_name@SemVer range per line. Dependencies are frozen into the signature.",
    expiresAt: "Expiry (optional)",
    chooseExtension: "Choose ready Extension",
    chooseAnchor: "Choose local signer",
    download: "Sign & download",
    downloading: "Signing...",
    transferTitle: "Offline transfer",
    transferBody:
      "Verify any package, lockfile, or channel index against this workspace. Only trusted packages can be imported as new pending Extensions.",
    verify: "Verify artifact",
    verifying: "Verifying...",
    import: "Import package",
    importing: "Importing...",
    updateTitle: "Reviewed package update",
    updateBody:
      "Compare a trusted candidate against one installed package before replacing any durable binding.",
    updateTarget: "Installed package",
    chooseUpdateTarget: "Choose installed package",
    previewUpdate: "Preview update",
    previewingUpdate: "Comparing...",
    applyUpdate: "Apply & reset review",
    applyingUpdate: "Applying...",
    cancelUpdate: "Discard preview",
    currentPackage: "Current",
    nextPackage: "Candidate",
    updateChanges: "Frozen differences",
    noUpdateChanges: "This exact envelope is already installed.",
    reviewReset:
      "Applying preserves the Extension ID but disconnects it and clears source, capability, tool-effect, and Agent approval.",
    confirmPublisherChange:
      "I approve the publisher identity or signing-key change.",
    confirmVersionOverride:
      "I approve this rollback or non-SemVer version transition.",
    versionDirections: {
      upgrade: "Upgrade",
      same: "Same version",
      regression: "Rollback",
      unknown: "Opaque version",
    },
    changeLabels: {
      publisher: "Publisher",
      version: "Version",
      metadata: "Metadata",
      transport: "Transport",
      capabilities: "Capabilities",
      tools: "Tool schemas",
      effects: "Tool effects",
      dependencies: "Dependencies",
      executable: "Executable",
      lifecycle: "Lifecycle",
      signature: "Signature",
    },
    added: "Added",
    removed: "Removed",
    schemaChanged: "Schema changed",
    descriptionChanged: "Description changed",
    effectChanged: "Effect changed",
    routingHintChanged: "Routing hint changed",
    dependencyChanged: "Range changed",
    deploymentTitle: "Atomic package deployment",
    deploymentBody:
      "Review up to eight trusted packages as one dependency-resolved install and update transaction.",
    rolloutTitle: "Rollout channels",
    rolloutBody:
      "Pin the current signed package graph to a named channel, then replay that channel through deployment review.",
    rolloutName: "Channel name",
    rolloutNamePlaceholder: "stable",
    publishRollout: "Publish channel",
    publishingRollout: "Publishing...",
    previewRollout: "Preview rollout",
    previewingRollout: "Previewing...",
    rolloutEmpty: "No rollout channels have been published.",
    rolloutPackageCount: "packages",
    rolloutRevision: "revision",
    rolloutLockfile: "lockfile",
    planHash: "plan",
    keyHash: "key",
    manifestHash: "manifest",
    indexEnvelopeHash: "index envelope",
    lockfileHash: "lockfile",
    envelopeHash: "envelope",
    indexHash: "index",
    channelCount: "channels",
    bindingHash: "binding",
    previewHash: "preview",
    rolloutPublished:
      "Rollout channel published with a policy-bound lockfile. Applying it still uses deployment CAS and local review reset.",
    rolloutApplied:
      "Rollout channel applied through atomic package deployment. Installed packages remain pending for local approval.",
    rolloutPolicy:
      "Policy locks allowed package names, publisher keys, max package count, trusted publishers, and dependency closure.",
    channelIndexTitle: "Channel index registry",
    channelIndexBody:
      "Sign active rollout channels as a summary-only registry index. It carries channel hashes, lockfile hashes, optional lockfile locators, and policy hashes, never package envelopes or local approvals.",
    channelIndexAnchor: "Index signer",
    channelIndexPublisher: "Index publisher",
    channelIndexPublisherPlaceholder: "Napier Channel Registry",
    signChannelIndex: "Sign index",
    signingChannelIndex: "Signing...",
    channelIndexSigned:
      "Channel index exported with summary hashes and hash-bound lockfile locators only. Importing packages still requires lockfile verification, rollout preview, deployment CAS, and local review.",
    channelIndexVerified:
      "Channel index signature verified. It proves channel summary provenance only; deployment still uses the normal lockfile and rollout gates.",
    exportLockfile: "Export lockfile",
    exportingLockfile: "Exporting...",
    lockfileExported:
      "Lockfile exported with complete signed envelopes. Re-import it through package deployment to replay this set in another workspace.",
    lockfileVerified:
      "Lockfile verified with complete signed envelopes and dependency closure. Deployment still replays the normal review and CAS gates.",
    previewDeployment: "Select package set",
    previewingDeployment: "Resolving graph...",
    applyDeployment: "Deploy set & reset review",
    applyingDeployment: "Deploying...",
    cancelDeployment: "Discard deployment plan",
    deploymentCandidates: "Candidates",
    deploymentInstalls: "Installs",
    deploymentUpdates: "Updates",
    deploymentOrder: "Dependency-first order",
    dependencyResolution: "Resolved dependencies",
    deploymentReviewReset:
      "One stale binding or dependency failure rejects the entire set. Every installed or updated package starts pending with no inherited local approval.",
    confirmDeploymentPublishers:
      "I approve every publisher identity or signing-key change in this set.",
    confirmDeploymentVersions:
      "I approve every rollback or non-SemVer transition in this set.",
    deploymentActions: {
      install: "Install",
      update: "Update",
    },
    resolutionSources: {
      candidate: "candidate",
      installed: "installed",
    },
    packageRevision: "Package revision",
    packageHistory: "Prior packages",
    signedNotApproved:
      "A valid signature proves publisher identity and frozen contents. Source approval, tool review, and Agent enablement remain separate local decisions.",
    packageBadge: "Signed package",
    packageTrust: "Package trust",
    publisherKey: "Publisher key",
    manifest: "Manifest",
    executable: "Executable",
    actions: {
      signed: "Package signed",
      verified: "Package verified",
      imported: "Package imported",
      updated: "Package updated",
      deployed: "Package set deployed",
      rollout_published: "Rollout published",
      rollout_applied: "Rollout applied",
      lockfile_verified: "Lockfile verified",
      lockfile_exported: "Lockfile exported",
      channel_index_signed: "Channel index signed",
      channel_index_verified: "Channel index verified",
    },
    verificationStatuses: {
      trusted: "Trusted",
      revoked: "Revoked key",
      unknown_key: "Unknown key",
      expired: "Expired",
      invalid: "Invalid package, lockfile, or index",
      configuration_drift: "Configuration drift",
      executable_mismatch: "Executable mismatch",
    },
    errors: {
      tooLarge: "Signed Extension package exceeds the 4 MiB import limit.",
      deploymentTooLarge:
        "Package deployment accepts at most 8 files and 16 MiB total.",
      invalid: "The selected file is not valid JSON.",
      invalidLockfile:
        "The selected lockfile does not contain signed packages.",
      lockfileTooLarge: "Extension package lockfiles accept at most 16 MiB.",
      channelIndexTooLarge:
        "Extension package channel indices accept at most 1 MiB.",
      invalidDependency:
        "Dependencies must use canonical package_name@SemVer range lines.",
    },
  },
  statuses: {
    pending: "Pending review",
    approved: "Approved",
    rejected: "Rejected",
    untested: "Untested",
    connecting: "Connecting",
    ready: "Ready",
    error: "Connection error",
    disconnected: "Disconnected",
  },
  errors: {
    capability: "Select at least one external tool effect.",
    headerPair:
      "Header name and environment variable must be provided together.",
    command: "Stdio requires an absolute executable path.",
    envPair:
      "Child variable and source environment variable must be provided together.",
  },
} as const;

export const extensionCopy = deepMergeCopy(
  extensionCopyEn,
  getLocale() === "zh" ? extensionCopyZh : {},
);
