import type { LocaleOverride } from "./locale";
import type { extensionCopyEn } from "./extension-copy";

export const extensionCopyZh: LocaleOverride<typeof extensionCopyEn> = {
  eyebrow: "能力注册表",
  title: "已评审扩展",
  loading: "正在打开能力注册表……",
  empty: "尚未提议外部能力。",
  name: "服务名称",
  namePlaceholder: "研究记录",
  transport: "传输方式",
  http: "流式 HTTP",
  stdio: "Sandbox stdio",
  url: "流式 HTTP URL",
  urlPlaceholder: "https://example.com/mcp",
  headerName: "请求头名称（可选）",
  headerNamePlaceholder: "Authorization",
  headerEnv: "凭据环境变量（可选）",
  headerEnvPlaceholder: "RESEARCH_MCP_TOKEN",
  command: "可执行文件绝对路径",
  commandPlaceholder: "/opt/napier/bin/records-mcp",
  args: "参数（每行一个）",
  argsPlaceholder: "--stdio\n--format=json",
  cwd: "工作区 cwd（可选）",
  cwdPlaceholder: "services/records",
  envTarget: "子进程变量（可选）",
  envTargetPlaceholder: "MCP_TOKEN",
  envSource: "来源环境变量（可选）",
  envSourcePlaceholder: "RECORDS_SOURCE_TOKEN",
  requestedAccess: "工具效果",
  sandboxAccess: "Sandbox 访问",
  network: "出站网络",
  workspaceRead: "读取工作区",
  workspaceWrite: "写入工作区",
  derivedAccess: "派生传输门禁",
  processDerived: "process.spawn",
  secretDerived: "secrets.env",
  cwdDerived: "cwd 表示需要 workspace.read",
  trust: "信任",
  connection: "连接",
  effect: "效果",
  read: "外部读取",
  write: "外部写入",
  unknown: "未分类",
  propose: "提议连接",
  approve: "批准来源",
  reject: "拒绝",
  connect: "连接并发现工具",
  disconnect: "断开连接",
  enable: "为智能体启用",
  disable: "为智能体停用",
  tools: "已发现工具",
  noTools: "连接已批准来源后即可发现工具。",
  approveRead: "批准读取",
  approveWrite: "批准写入",
  routingHint: "路由提示",
  routingHintPlaceholder:
    "智能体应在何时选择此工具？提示需保持本地且经过评审。",
  revoke: "撤销",
  schema: "结构",
  provenance: "来源",
  capabilities: "能力",
  activeTools: "个已批准工具",
  plugins: {
    eyebrow: "第一方插件",
    title: "Kernel 能力",
    body: "内置能力使用版本化清单和相同的所有者作用域 Kernel 生命周期。停用后会移除其服务、Hook 与投影。",
    empty: "没有安装第一方插件。",
    enabled: "已启用",
    disabled: "已停用",
    contributes: "贡献项",
    permissions: "权限",
    dependencies: "依赖",
    host: "宿主",
    client: "客户端",
    noPermissions: "无需额外权限",
    noDependencies: "无插件依赖",
  },
  mappingCount: "个显式环境变量映射",
  stdioSafety:
    "不会使用 Shell。可执行文件必须是绝对路径；cwd 必须留在工作区内；子进程变量只能映射自已命名的服务端环境变量。",
  safety:
    "连接信任、工具效果和智能体启用是三道独立门禁。Stdio 只能通过受支持的操作系统 Sandbox 启动，并使用显式进程能力。",
  packages: {
    eyebrow: "签名包来源",
    title: "发布者与包管理",
    body: "将发布者身份、传输方式、能力、工具结构、已评审效果和本地 stdio 可执行文件摘要冻结到 Ed25519 信封中。",
    anchors: "发布者密钥",
    emptyAnchors: "尚未注册发布者密钥。",
    signing: "本地签名者",
    verifyOnly: "仅验证",
    trusted: "可信",
    revoked: "已撤销",
    revoke: "撤销密钥",
    confirmRevoke: "确认撤销",
    cancel: "取消",
    addPublisher: "注册发布者",
    addPublisherBusy: "正在注册……",
    label: "密钥标签",
    labelPlaceholder: "发布签名者",
    source: "密钥来源",
    environment: "环境签名者",
    publicKey: "SPKI 公钥",
    environmentVariable: "私钥环境变量",
    environmentPlaceholder: "NAPIER_EXTENSION_SIGNING_KEY",
    publicKeySpki: "Ed25519 SPKI PEM",
    publicKeyPlaceholder: "-----BEGIN PUBLIC KEY-----",
    signingTitle: "签发已签名包",
    signingBody: "只有全部工具效果均已评审且就绪的目录才能签名。",
    extension: "已评审扩展",
    signingAnchor: "签名密钥",
    publisher: "发布者",
    publisherPlaceholder: "示例实验室",
    dependencies: "已签名依赖（可选）",
    dependenciesPlaceholder:
      "research_core@^2.1.0\nartifact_store@>=1.4.0 <2.0.0",
    dependenciesHint:
      "每行填写一个规范的 package_name@SemVer 范围；依赖会被冻结到签名中。",
    expiresAt: "到期时间（可选）",
    chooseExtension: "选择就绪扩展",
    chooseAnchor: "选择本地签名者",
    download: "签名并下载",
    downloading: "正在签名……",
    transferTitle: "离线传输",
    transferBody:
      "针对当前工作区验证任意包、锁文件或通道索引。只有可信包才能作为新的待审扩展导入。",
    verify: "验证 Artifact",
    verifying: "正在验证……",
    import: "导入包",
    importing: "正在导入……",
    updateTitle: "已评审包更新",
    updateBody: "替换任何持久绑定前，将可信候选包与一个已安装包进行比较。",
    updateTarget: "已安装包",
    chooseUpdateTarget: "选择已安装包",
    previewUpdate: "预览更新",
    previewingUpdate: "正在比较……",
    applyUpdate: "应用并重置评审",
    applyingUpdate: "正在应用……",
    cancelUpdate: "丢弃预览",
    currentPackage: "当前版本",
    nextPackage: "候选版本",
    updateChanges: "冻结差异",
    noUpdateChanges: "这一准确的信封已经安装。",
    reviewReset:
      "应用后会保留扩展 ID，但会断开连接并清除来源、能力、工具效果和智能体批准。",
    confirmPublisherChange: "我批准发布者身份或签名密钥变更。",
    confirmVersionOverride: "我批准此次回滚或非 SemVer 版本迁移。",
    versionDirections: {
      upgrade: "升级",
      same: "版本相同",
      regression: "回滚",
      unknown: "不透明版本",
    },
    changeLabels: {
      publisher: "发布者",
      version: "版本",
      metadata: "元数据",
      transport: "传输方式",
      capabilities: "能力",
      tools: "工具结构",
      effects: "工具效果",
      dependencies: "依赖",
      executable: "可执行文件",
      lifecycle: "生命周期",
      signature: "签名",
    },
    added: "已新增",
    removed: "已移除",
    schemaChanged: "结构已变化",
    descriptionChanged: "说明已变化",
    effectChanged: "效果已变化",
    routingHintChanged: "路由提示已变化",
    dependencyChanged: "范围已变化",
    deploymentTitle: "原子包部署",
    deploymentBody:
      "将最多八个可信包作为一笔完成依赖解析的安装与更新事务进行评审。",
    rolloutTitle: "发布通道",
    rolloutBody: "把当前签名包图固定到命名通道，再通过部署评审重放该通道。",
    rolloutName: "通道名称",
    rolloutNamePlaceholder: "稳定版",
    publishRollout: "发布通道",
    publishingRollout: "正在发布……",
    previewRollout: "预览发布",
    previewingRollout: "正在预览……",
    rolloutEmpty: "尚未发布任何通道。",
    rolloutPackageCount: "个包",
    rolloutRevision: "修订",
    rolloutLockfile: "锁文件",
    planHash: "计划",
    keyHash: "密钥",
    manifestHash: "清单",
    indexEnvelopeHash: "索引信封",
    lockfileHash: "锁文件",
    envelopeHash: "信封",
    indexHash: "索引",
    channelCount: "个通道",
    bindingHash: "绑定",
    previewHash: "预览",
    rolloutPublished:
      "发布通道已使用策略绑定的锁文件发布；应用时仍会执行部署 CAS 和本地评审重置。",
    rolloutApplied: "发布通道已通过原子包部署应用；已安装包仍需等待本地批准。",
    rolloutPolicy:
      "策略会锁定允许的包名、发布者密钥、最大包数、可信发布者和依赖闭包。",
    channelIndexTitle: "通道索引注册表",
    channelIndexBody:
      "将活动发布通道签名为只含摘要的注册索引。它包含通道哈希、锁文件哈希、可选锁文件定位符和策略哈希，但不包含包信封或本地批准。",
    channelIndexAnchor: "索引签名者",
    channelIndexPublisher: "索引发布者",
    channelIndexPublisherPlaceholder: "Napier 通道注册表",
    signChannelIndex: "签名索引",
    signingChannelIndex: "正在签名……",
    channelIndexSigned:
      "通道索引已导出，仅包含摘要哈希和哈希绑定的锁文件定位符；导入包仍需经过锁文件验证、发布预览、部署 CAS 和本地评审。",
    channelIndexVerified:
      "通道索引签名已验证。它只证明通道摘要来源；部署仍使用常规锁文件和发布门禁。",
    exportLockfile: "导出锁文件",
    exportingLockfile: "正在导出……",
    lockfileExported:
      "锁文件已连同完整签名信封导出；可在其他工作区通过包部署重新导入并重放这组包。",
    lockfileVerified:
      "锁文件及其完整签名信封和依赖闭包已验证；部署仍会重放常规评审与 CAS 门禁。",
    previewDeployment: "选择包集合",
    previewingDeployment: "正在解析依赖图……",
    applyDeployment: "部署集合并重置评审",
    applyingDeployment: "正在部署……",
    cancelDeployment: "丢弃部署计划",
    deploymentCandidates: "候选包",
    deploymentInstalls: "安装",
    deploymentUpdates: "更新",
    deploymentOrder: "依赖优先顺序",
    dependencyResolution: "已解析依赖",
    deploymentReviewReset:
      "一个过期绑定或依赖失败会拒绝整个集合；每个安装或更新的包都会从无继承本地批准的待审状态开始。",
    confirmDeploymentPublishers:
      "我批准此集合中的全部发布者身份或签名密钥变更。",
    confirmDeploymentVersions: "我批准此集合中的全部回滚或非 SemVer 迁移。",
    deploymentActions: {
      install: "安装",
      update: "更新",
    },
    resolutionSources: {
      candidate: "候选包",
      installed: "已安装包",
    },
    packageRevision: "包修订",
    packageHistory: "历史包",
    signedNotApproved:
      "有效签名证明发布者身份和冻结内容；来源批准、工具评审与智能体启用仍是独立的本地决策。",
    packageBadge: "已签名包",
    packageTrust: "包信任",
    publisherKey: "发布者密钥",
    manifest: "清单",
    executable: "可执行文件",
    actions: {
      signed: "包已签名",
      verified: "包已验证",
      imported: "包已导入",
      updated: "包已更新",
      deployed: "包集合已部署",
      rollout_published: "发布通道已发布",
      rollout_applied: "发布通道已应用",
      lockfile_verified: "锁文件已验证",
      lockfile_exported: "锁文件已导出",
      channel_index_signed: "通道索引已签名",
      channel_index_verified: "通道索引已验证",
    },
    verificationStatuses: {
      trusted: "可信",
      revoked: "密钥已撤销",
      unknown_key: "未知密钥",
      expired: "已过期",
      invalid: "包、锁文件或索引无效",
      configuration_drift: "配置漂移",
      executable_mismatch: "可执行文件不匹配",
    },
    errors: {
      tooLarge: "签名扩展包超过 4 MiB 导入上限。",
      deploymentTooLarge: "包部署最多接收 8 个文件，总大小不超过 16 MiB。",
      invalid: "所选文件不是有效 JSON。",
      invalidLockfile: "所选锁文件不包含签名包。",
      lockfileTooLarge: "扩展包锁文件最大为 16 MiB。",
      channelIndexTooLarge: "扩展包通道索引最大为 1 MiB。",
      invalidDependency:
        "依赖必须使用规范的 package_name@SemVer 范围格式，每行一个。",
    },
  },
  statuses: {
    pending: "等待评审",
    approved: "已批准",
    rejected: "已拒绝",
    untested: "未测试",
    connecting: "正在连接",
    ready: "就绪",
    error: "连接错误",
    disconnected: "已断开",
  },
  errors: {
    capability: "请至少选择一种外部工具效果。",
    headerPair: "请求头名称和环境变量必须同时提供。",
    command: "Stdio 要求可执行文件使用绝对路径。",
    envPair: "子进程变量和来源环境变量必须同时提供。",
  },
};
