export const goalCopyEn = {
  eyebrow: "OBJECTIVE",
  title: "Durable goal",
  empty: "Set an objective that can span multiple runs.",
  placeholder: "Define a verifiable outcome...",
  set: "Set goal",
  clear: "Clear",
  active: "Active",
  completed: "Verified",
  blocked: "Blocked",
  evidence: "Latest evidence",
  noProgress: "No progress",
  status: "Status",
  continuations: "Continuations",
  blockers: {
    none: "No blocker",
    missing_evidence: "Missing evidence",
    needs_user_input: "Needs user input",
    run_failed: "Run failed",
    external_wait: "Waiting on an external dependency",
    goal_not_met_yet: "Goal not met yet",
  },
  guardrail: "Napier fails closed when evidence is insufficient.",
} as const;

export const goalCopyZh = {
  eyebrow: "目标",
  title: "长期目标",
  empty: "设定一个可跨多次运行的目标。",
  placeholder: "定义一个可验证的结果……",
  set: "设定目标",
  clear: "清除",
  active: "进行中",
  completed: "已验证",
  blocked: "受阻",
  evidence: "最新证据",
  noProgress: "无进展",
  status: "状态",
  continuations: "继续次数",
  blockers: {
    none: "无阻断项",
    missing_evidence: "缺少证据",
    needs_user_input: "需要用户输入",
    run_failed: "运行失败",
    external_wait: "等待外部依赖",
    goal_not_met_yet: "目标尚未达成",
  },
  guardrail: "证据不足时 Napier 会安全终止。",
} as const;
export { memoryProvenanceCopyEn } from "./memory-copy";
