export const labSuiteCopyZh = {
  eyebrow: "质量门禁",
  title: "评估 Suite",
  body: "使用带修订的量表和确定性门禁，把一个基线与有界候选列表进行回放比较。",
  create: "创建 Suite",
  update: "保存修订",
  edit: "编辑",
  cancel: "取消",
  run: "运行门禁",
  running: "正在评估批次……",
  receipt: "门禁回执",
  exportingReceipt: "正在绑定回执……",
  signedReceipt: "已签名回执",
  exportingSignedReceipt: "正在签名回执……",
  name: "Suite 名称",
  namePlaceholder: "发布质量门禁",
  baseline: "基线运行",
  candidates: "候选列表",
  candidatesHint: "请选择 1–8 次已结算运行。",
  passRate: "最低非退化率",
  candidateScore: "最低候选评分",
  allowInconclusive: "允许部分场景无结论",
  evaluator: "评估器",
  empty: "尚未创建持久评估 Suite。",
  revision: "修订",
  latest: "最新门禁",
  neverRun: "尚未运行",
  average: "候选平均值",
  cases: "场景",
  digest: "批次 SHA-256",
  caseEvidence: "场景证据",
  baselineScore: "基线",
  candidateScoreShort: "候选项",
  pairDigest: "配对 SHA-256",
  history: "执行历史",
  safety:
    "每个场景都使用不可变运行快照和无工具评估器。配对、批次与回执哈希会绑定完整门禁证据。",
  statuses: {
    passed: "通过",
    failed: "失败",
    inconclusive: "无结论",
  },
  errors: {
    candidates: "请至少选择一个与基线不同的候选项。",
    maximum: "评估 Suite 最多接收 8 个候选项。",
  },
} as const;
