export const labCalibrationCopyZh = {
  eyebrow: "人工真值",
  title: "评估器校准",
  body: "把已评审结论追加到不可变模型判断，并在每个评估器与量表分组内计算准确一致率。",
  reviewed: "已评审",
  agreement: "准确一致率",
  groups: "校准分组",
  samples: "个样本",
  noSamples: "尚未记录人工真值。请评审一次评估以建立首个校准样本。",
  register: "评估审查记录",
  registerHint: "当前真值只可追加；修订结论会保留每次历史审查。",
  unreviewed: "等待评审",
  agreed: "一致",
  disagreed: "存在差异",
  modelVerdict: "模型结论",
  expectedVerdict: "预期结论",
  review: "评审",
  revise: "修订真值",
  save: "记录真值",
  saving: "正在绑定审查……",
  cancel: "取消",
  note: "审查备注",
  notePlaceholder: "说明支持此人工判断的证据。",
  revision: "真值修订",
  evaluator: "评估器",
  rubric: "量表",
  reportHash: "报告 SHA-256",
  matrix: "结论混淆矩阵",
  modelAxis: "模型",
  truthAxis: "真值",
  verdictMarks: {
    left_better: "左",
    right_better: "右",
    tie: "平",
    inconclusive: "无",
  },
  consensus: {
    open: "小组评审",
    provenance: "小组共识",
    eyebrow: "独立签核",
    title: "审查者共识",
    close: "关闭小组",
    body: "让每位审查者使用独立且只可追加的通道。预览会应用法定人数与一致率策略，但不会修改人工真值。",
    roster: "审查者通道",
    emptyRoster: "尚未记录独立投票。",
    reviewerId: "审查者通道 ID",
    reviewerIdPlaceholder: "release_owner",
    reviewerName: "显示名称",
    reviewerNamePlaceholder: "发布负责人",
    ballotNote: "私有投票理由",
    ballotNotePlaceholder: "说明支持此独立结论的证据。",
    clear: "清除通道",
    record: "记录投票",
    recording: "正在绑定投票……",
    gate: "共识策略",
    minimumReviewers: "最少审查者",
    minimumAgreement: "最低一致率",
    allowInconclusive: "允许无结论共识",
    preview: "预览共识",
    previewing: "正在计算……",
    resolve: "解析为真值",
    resolving: "正在绑定真值……",
    noLeader: "没有唯一领先结论",
    agreement: "小组一致率",
    previewRequired: "更改共识策略后，请预览当前通道。",
    latestResolution: "最新解析结果",
    statuses: {
      ready: "可以解析",
      insufficient_reviewers: "需要更多审查者",
      no_consensus: "尚无共识",
      inconclusive: "无结论被阻止",
    },
    safety:
      "解析操作明确且原子化。投票备注不会进入 Ledger 事件；最终人工真值修订会绑定共识报告 SHA-256。",
  },
  empty: "运行一次评估以创建可审查判断。",
  safety:
    "人工真值不会覆盖模型输出。每次修订都会绑定不可变评估 SHA-256，并随会话 Fixture 保持可移植。",
} as const;
