export const labCasebookCopyZh = {
  eyebrow: "回归归档",
  title: "评估 Casebook",
  body: "把多个会话中已评审的判断整理成只可追加、哈希绑定的黄金集合，用于工作区级评估器校准。",
  select: "Casebook 卷",
  empty: "尚未创建评估 Casebook。",
  create: "新建 Casebook",
  creating: "正在创建卷……",
  save: "保存元数据",
  saving: "正在绑定修订……",
  edit: "编辑元数据",
  cancel: "取消",
  name: "Casebook 名称",
  namePlaceholder: "发布评估黄金集",
  description: "范围说明",
  descriptionPlaceholder: "定义哪些内容属于此已评审证据集合。",
  currentRevision: "当前修订",
  cases: "黄金场景",
  agreement: "一致率",
  cohorts: "分组",
  curate: "整理已评审评估",
  curateAction: "添加场景",
  refreshAction: "刷新真值",
  curating: "正在绑定场景……",
  noReviewed: "此会话没有可供整理的人工评审评估。",
  upToDate: "当前真值已整理",
  source: "来源",
  modelVerdict: "模型",
  expectedVerdict: "真值",
  truthRevision: "真值修订",
  caseHash: "场景 SHA-256",
  evaluationHash: "评估 SHA-256",
  consensusEvidence: "小组证据",
  remove: "从当前修订移除",
  confirmRemove: "确认移除",
  removing: "正在移除场景……",
  history: "修订记录",
  export: "导出 Casebook",
  exporting: "正在绑定 Artifact……",
  reportHash: "校准 SHA-256",
  samples: "个样本",
  safety:
    "移除或刷新场景会创建新的 Casebook 修订；历史修订会保留准确的评估、真值、来源与哈希。",
  qualification: {
    eyebrow: "可执行黄金集",
    title: "评估器资格验证",
    body: "使用所选评估器重新判断当前 Manifest。评分前会重建每个来源运行，并针对冻结快照哈希进行检查。",
    evaluator: "候选评估器",
    minimumAgreement: "最低准确一致率",
    allowInconclusive: "允许经过验证的无结论判断",
    run: "验证评估器",
    running: "正在回放黄金集……",
    neverRun: "尚未运行",
    agreement: "一致率",
    verified: "已验证证据",
    inconclusive: "无结论",
    executionHash: "执行 SHA",
    expected: "预期",
    actual: "实际",
    expectedLeft: "预期左侧",
    observedLeft: "观测左侧",
    expectedRight: "预期右侧",
    observedRight: "观测右侧",
    unavailable: "不可用",
    empty: "当前修订尚未绑定资格验证。运行当前黄金集以创建记录。",
    noCases: "资格验证前，请至少整理一个已评审场景。",
    history: "资格验证历史",
    current: "当前修订",
    stale: "历史修订",
    receipt: "资格验证回执",
    exportingReceipt: "正在绑定回执……",
    signedReceipt: "已签名回执",
    exportingSignedReceipt: "正在签名回执……",
    promoteBaseline: "提升为基线",
    promotingBaseline: "正在固定基线……",
    noSigner: "请先注册并选择本地签名信任锚。",
    baseline: "可信资格验证基线",
    noBaseline: "尚未提升已签名基线。",
    baselineCurrent: "当前且可信",
    baselineStale: "Casebook 修订已过期",
    baselineRevoked: "签名者已撤销",
    baselineHash: "基线 SHA",
    signer: "签名密钥",
    statuses: {
      passed: "符合资格",
      failed: "低于门禁",
      inconclusive: "无结论",
    },
    caseStatuses: {
      agreed: "一致",
      disagreed: "存在差异",
      inconclusive: "无结论",
    },
    evidenceStates: {
      verified: "来源哈希已验证",
      drifted: "来源证据已漂移",
      missing: "缺少来源证据",
    },
  },
  revisionSources: {
    created: "已创建",
    metadata_updated: "元数据已更新",
    case_curated: "场景已整理",
    case_refreshed: "真值已刷新",
    case_removed: "场景已移除",
  },
} as const;
