export const labTrustCoreCopyZh = {
  eyebrow: "可信来源",
  title: "回执信任台",
  body: "将发布证据绑定到 Ed25519 身份，保留公开信任锚，并在不信任传输层的情况下验证签名回执。",
  anchors: "信任锚",
  empty: "尚未注册回执信任锚。",
  add: "添加信任锚",
  adding: "正在读取密钥……",
  label: "信任锚标签",
  labelPlaceholder: "发布签名身份",
  source: "信任锚来源",
  environment: "本地签名者 · 环境变量",
  publicKey: "仅验证 · 公钥",
  environmentVariable: "PKCS#8 私钥环境变量",
  environmentVariablePlaceholder: "NAPIER_RELEASE_SIGNING_KEY",
  publicKeySpki: "SPKI 公钥 · Base64 DER",
  publicKeyPlaceholder: "MCowBQYDK2VwAyEA…",
  signing: "本地签名",
  verifyOnly: "仅验证",
  revoke: "撤销",
  confirmRevoke: "确认撤销",
  cancel: "取消撤销",
  verifier: "离线信封验证器",
  verifierBody: "深度检查载荷哈希、签名声明、Ed25519 签名和当前信任锚状态。",
  chooseReceipt: "验证签名 JSON",
  verifying: "正在验证信封……",
  exportDirectory: "导出信任锚目录",
  exportingDirectory: "正在导出目录……",
  signDirectoryMetadata: "签名目录元数据",
  signingDirectoryMetadata: "正在签名元数据……",
  verifyDirectoryMetadata: "验证目录元数据",
  verifyingDirectoryMetadata: "正在验证元数据……",
  directoryMetadataPublisher: "Napier 信任注册表",
  chooseDirectory: "验证信任锚目录",
  verifyingDirectory: "正在验证目录……",
  directorySource: "托管目录 URL",
  directorySourcePlaceholder: "https://trust.example.com/anchors.json",
  subscriptionLabel: "订阅标签",
  subscriptionLabelPlaceholder: "发布信任源",
  expectedAnchorSet: "预期信任锚集合 SHA-256",
  expectedAnchorSetPlaceholder: "可选轮换固定值",
  discoverDirectory: "发现目录",
  discoveringDirectory: "正在发现目录……",
  subscribeDirectory: "订阅",
  subscribingDirectory: "正在订阅……",
  directorySubscriptions: "目录订阅",
  evaluateQuorum: "评估法定人数",
  evaluatingQuorum: "正在评估……",
  quorumAgreement: "来源一致率",
  quorumWeight: "权重",
  quorumPublishers: "发布者",
  nextRefresh: "下次刷新",
  transparencyTail: "透明日志末尾",
  useSubscription: "使用",
  subscriptionInUse: "使用中",
  refreshSubscription: "刷新订阅",
  pauseSubscription: "暂停订阅",
  resumeSubscription: "恢复订阅",
  externalDirectoryActive: "签名 JSON 验证正在使用活动外部目录。",
  externalDirectoryReady: "外部目录已启用",
  externalTrustedKeys: "个可信验证密钥",
  clearExternalDirectory: "恢复使用本地回执信任锚",
  hashOnlyRemoteSource: "远程来源与响应只会保留为哈希。",
  noDiagnostics: "无诊断信息",
  directoryAge: "目录年龄",
  policyHash: "策略",
  statuses: {
    trusted: "可信",
    revoked: "已撤销",
  },
  verificationStatuses: {
    trusted: "来源可信",
    revoked: "有效 · 密钥已撤销",
    unknown_key: "未知签名者",
    invalid: "信封无效",
  },
  verificationDirectorySources: {
    uploaded: "上传的目录",
    active_selection: "活动验证器选择",
  },
  directoryVerificationStatuses: {
    valid: "目录有效",
    invalid: "目录无效",
  },
  directoryMetadataVerificationStatuses: {
    trusted: "元数据可信",
    revoked: "元数据密钥已撤销",
    unknown_key: "未知元数据签名者",
    invalid: "元数据无效",
  },
  directoryDiscoveryStatuses: {
    valid: "托管目录已接受",
    invalid: "托管目录已拒绝",
  },
  subscriptionStatuses: {
    active: "已启用",
    paused: "已暂停",
  },
  subscriptionRefreshStatuses: {
    promoted: "已提升轮换版本",
    unchanged: "目录未变化",
    rollback_rejected: "已拒绝回滚",
    rejected: "已拒绝刷新",
    failed: "刷新失败",
  },
  quorumStatuses: {
    agreed: "法定来源已达成一致",
    insufficient_sources: "法定来源数量不足",
    split: "法定来源存在分歧",
    policy_failed: "法定策略失败",
  },
  checkpointRegistryQuorumStatuses: {
    agreed: "检查点法定来源已达成一致",
    insufficient_sources: "检查点法定来源数量不足",
    split: "检查点注册表存在分歧",
    policy_failed: "检查点法定策略失败",
    stale: "检查点注册表已过期",
  },
} as const;
