export const labTrustBaselineCopyZh = {
  baselineWorkbench: "基线激活",
  baselineWorkbenchBody:
    "激活验证器集合前，对照当前最后可信目录源检查签名的法定基线。",
  baselineWorkbenchEmpty: "尚未导入或提升法定基线。",
  latestBaseline: "最新法定基线",
  baselineSourcesAligned: "个来源一致",
  verifyBaseline: "检查基线",
  verifyingBaseline: "正在检查……",
  importBaseline: "导入基线归档",
  importingBaseline: "正在导入……",
  signBaselineActivation: "签名激活决定",
  signingBaselineActivation: "正在签名……",
  applyBaselineActivation: "应用激活决定",
  applyingBaselineActivation: "正在应用……",
  refreshActivationSelectionDrift: "审计漂移",
  refreshingActivationSelectionDrift: "正在审计……",
  reviewActivationSelectionRotation: "检查轮换",
  reviewingActivationSelectionRotation: "正在检查……",
  proposeActivationSelectionRotation: "提议轮换",
  proposingActivationSelectionRotation: "正在提议……",
  signActivationSelectionRotationProposal: "签名提议",
  signingActivationSelectionRotationProposal: "正在签名提议……",
  preflightActivationSelectionRotationProposal: "预检提议",
  preflightingActivationSelectionRotationProposal: "正在预检……",
  exportActivationSelectionCheckpoint: "导出检查点",
  exportingActivationSelectionCheckpoint: "正在导出检查点……",
  signActivationSelectionCheckpoint: "签名检查点",
  signingActivationSelectionCheckpoint: "正在签名检查点……",
  activationSelectionCheckpointSource: "托管检查点 URL",
  activationSelectionCheckpointSourcePlaceholder:
    "https://trust.example.com/activation-selection-checkpoint.json",
  checkpointSubscriptionLabel: "检查点订阅标签",
  checkpointSubscriptionLabelPlaceholder: "激活检查点注册表",
  expectedActivationSelectionCheckpoint: "预期检查点 SHA-256",
  expectedActivationSelectionCheckpointPlaceholder: "可选检查点固定值",
  discoverActivationSelectionCheckpoint: "发现检查点",
  discoveringActivationSelectionCheckpoint: "正在发现检查点……",
  subscribeActivationSelectionCheckpoint: "订阅检查点",
  subscribingActivationSelectionCheckpoint: "正在订阅检查点……",
  checkpointSubscriptions: "检查点订阅",
  evaluateCheckpointRegistryQuorum: "评估检查点法定来源",
  evaluatingCheckpointRegistryQuorum: "正在评估检查点法定来源……",
  promoteCheckpointRegistryQuorumBaseline: "提升检查点法定基线",
  promotingCheckpointRegistryQuorumBaseline: "正在提升检查点法定基线……",
  checkpointRegistryQuorumBaseline: "检查点法定基线",
  verifyCheckpointRegistryQuorumBaseline: "验证检查点基线",
  verifyingCheckpointRegistryQuorumBaseline: "正在检查检查点基线……",
  importCheckpointRegistryQuorumBaseline: "导入检查点基线",
  importingCheckpointRegistryQuorumBaseline: "正在导入检查点基线……",
  checkpointRegistryQuorumBaselineImported: "检查点基线已导入",
  checkpointRegistryQuorumBaselineAlreadyImported: "检查点基线已归档",
  refreshCheckpointSubscription: "刷新检查点",
  refreshingCheckpointSubscription: "正在刷新检查点……",
  updatingCheckpointSubscription: "正在更新检查点……",
  verifyActivationSelectionCheckpoint: "验证检查点",
  verifyingActivationSelectionCheckpoint: "正在检查检查点……",
  activeBaselineActivation: "活动验证器选择",
  activeBaselineActivationBody: "CAS 绑定的批准已生效",
  activationSelectionDriftAudit: "选择漂移审计",
  activationSelectionRotationReview: "轮换检查",
  activationSelectionRotationProposal: "轮换提议",
  signedActivationSelectionRotationProposal: "已签名轮换提议",
  activationSelectionRotationProposalPreflight: "提议预检",
  activationSelectionCheckpoint: "选择检查点",
  signedActivationSelectionCheckpoint: "已签名检查点",
  activationSelectionCheckpointEntries: "个选择条目",
  exportBaselineActivationHistory: "导出激活历史",
  exportingBaselineActivationHistory: "正在导出历史……",
  verifyBaselineActivationHistory: "验证激活历史",
  verifyingBaselineActivationHistory: "正在检查历史……",
  baselineActivationHistory: "激活历史",
  baselineActivationHistoryApproved: "个已批准决定",
  baselineActivationHistoryBaselines: "个基线",
  baselineUnknownSource: "归档来源",
  baselineSourceStatuses: {
    aligned: "与当前最后可信目录一致",
    directory_drift: "目录哈希漂移",
    anchor_set_drift: "信任锚集合漂移",
    no_last_good: "没有最后可信目录",
    missing_subscription: "没有活动订阅",
  },
  baselineVerificationStatuses: {
    trusted: "基线可信",
    revoked: "基线密钥已撤销",
    unknown_key: "未知基线签名者",
    invalid: "基线无效",
  },
  baselinePolicyStatuses: {
    accepted: "激活策略已接受",
    rejected: "激活策略已拒绝",
  },
  baselineActivationDecisionStatuses: {
    approved: "激活已批准",
    rejected: "激活已拒绝",
  },
  activationSelectionDriftStatuses: {
    missing_selection: "没有活动验证器选择",
    aligned: "选择与当前法定结果一致",
    directory_drift: "检测到目录哈希漂移",
    anchor_set_drift: "检测到信任锚集合漂移",
    quorum_unavailable: "当前法定结果不可用",
  },
  activationSelectionRotationStatuses: {
    eligible: "候选项可以替换活动选择",
    already_active: "候选项已处于活动状态",
    blocked: "候选项未通过轮换门禁",
    stale_selection: "选择 CAS 前置条件失败",
    missing_decision: "缺少激活决定",
  },
  activationSelectionRotationProposalStatuses: {
    proposed: "轮换提议已就绪",
    already_active: "候选项已处于活动状态",
    blocked: "提议未通过门禁",
    stale_selection: "选择 CAS 前置条件失败",
    missing_decision: "缺少激活决定",
    missing_checkpoint_registry_baseline: "缺少检查点法定基线",
  },
  activationSelectionRotationProposalPreflightStatuses: {
    accepted: "签名提议仍然有效",
    rejected: "签名提议已拒绝",
    not_required: "无需提议",
  },
  activationSelectionCheckpointVerificationStatuses: {
    valid: "检查点与本地状态一致",
    divergent: "检查点与本地状态存在差异",
    invalid: "检查点无效",
  },
  activationSelectionCheckpointDiscoveryStatuses: {
    valid: "托管检查点已接受",
    invalid: "托管检查点已拒绝",
  },
  baselineActivationHistoryVerificationStatuses: {
    valid: "历史与本地状态一致",
    divergent: "历史与本地状态存在差异",
    invalid: "历史无效",
  },
  safety:
    "私钥只在签名时读取。订阅 URL 会保留在本地工作区快照中以便刷新；Ledger 事件只公开 URL 指纹与证据哈希。",
  errors: {
    tooLarge: "可信回执文件不得超过 10 MiB。",
    directoryTooLarge: "回执信任锚目录文件不得超过 2 MiB。",
  },
} as const;
