export const labCoreCopyZh = {
  eyebrow: "运行实验室",
  title: "比较证据",
  count: "次已结算运行",
  empty: "至少完成两次运行后才能进行比较。",
  baseline: "基线",
  candidate: "候选项",
  selectRun: "选择运行",
  compare: "比较",
  evaluate: "评估",
  comparing: "正在比较……",
  evaluating: "正在评估……",
  export: "导出回放",
  metricDelta: "候选差异",
  eventDelta: "事件差异",
  output: "最终输出",
  changed: "已变化",
  unchanged: "未变化",
  duration: "耗时",
  events: "事件",
  tokens: "Token",
  tools: "工具调用",
  contextEnvelopes: "上下文信封",
  embeddedContextEnvelopes: "嵌入信封",
  contextBindings: "上下文绑定",
  contextMisses: "上下文缺失",
  contextCoverage: "上下文覆盖",
  contextCoverageClean: "完整",
  contextCoveragePartial: "部分",
  contextCoverageMissing: "缺失",
  contextCoverageRegressed: "已退化",
  contextCoverageHealthy: "候选模型响应已全部绑定到上下文信封。",
  contextCoverageDelta: "差异",
  contextCoverageDiagnostics: "诊断",
  harnessFairness: "Harness 对照",
  harnessComparable: "可公平比较",
  harnessNotComparable: "不可公平比较",
  harnessInsufficientEvidence: "证据不足",
  harnessFairnessHealthy: "Provider、模型、任务、环境和运行预算均已匹配。",
  repeatedCalls: "重复调用",
  noNewInformation: "无新信息调用",
  interventions: "人工介入",
  firstRead: "首次读取",
  firstWrite: "首次修改",
  firstVerify: "首次验证",
  promptTokenShare: "Prompt Token 占比",
  toolTokenShare: "工具 Schema Token 占比",
  harnessReceipt: "Harness 回执",
  harnessResolution: "Harness 解析",
  harnessResolutionLeft: "左侧",
  harnessResolutionRight: "右侧",
  traceSummaryCoverage: "轨迹摘要覆盖",
  traceSummaryClean: "完整",
  traceSummaryGenericPresent: "存在通用回退",
  traceSummaryRegressed: "已退化",
  traceSummaryHealthy: "候选轨迹摘要未使用通用原始载荷回退。",
  traceSummaryDiagnostics: "摘要诊断",
  traceSummaryGeneric: "通用摘要",
  traceSummaryGenericDelta: "通用摘要差异",
  traceSummaryDedicatedDelta: "专用摘要差异",
  traceSummaryDelta: "摘要差异",
  traceSummaryReceipt: "摘要回执",
  traceSummaryVerification: "摘要验证",
  traceSummaryVerified: "已验证",
  traceSummaryInvalid: "无效",
  cost: "成本",
  noDelta: "事件类型没有差异。",
  configuration: "配置漂移",
  configurationChanged: "已变化",
  configurationUnchanged: "未变化",
  configurationUnavailableShort: "不可用",
  configurationUnavailable: "一次或两次运行早于配置指纹；无法判断漂移。",
  verdict: "独立结论",
  noVerdict: "尚未记录此运行对的评估。",
  evidence: "评估器证据",
  rubric: "量表评分",
  left: "左侧",
  right: "右侧",
  hashes: "证据哈希",
  governance: "治理",
  demoNotice:
    "演示模型只会记录无结论结果。请选择已配置的在线模型进行独立评分。",
  safety:
    "评估器接收不可变快照、不提供工具，并把 Ledger 证据视为不可信输入。结论会绑定两侧事件流哈希。",
  fixture: {
    eyebrow: "会话 Fixture",
    title: "可移植 Ledger",
    body: "将完整会话、智能体修订、运行、计划、评估、人工裁定、审查共识、质量门禁、子智能体和有序证据携带为一个回放 Fixture。",
    events: "个事件",
    contextEnvelopes: "个上下文信封",
    embeddedEnvelopes: "个嵌入信封",
    runs: "次运行",
    plans: "个计划",
    evaluations: "次评估",
    importedSource: "导入来源 SHA-256",
    sourceEvents: "个来源事件",
    localImportedCutoff: "本地截止点",
    importReceipt: "导入回执",
    export: "导出完整 Ledger",
    exporting: "正在绑定 Fixture……",
    verify: "验证 Fixture",
    verifying: "正在检查 Fixture……",
    import: "导入 Fixture",
    importing: "正在导入 Fixture……",
    noDiagnostics: "无诊断信息",
    safety:
      "内容哈希与事件流哈希都会验证；导入时仍在进行的工作会以未知结果关闭。",
    receipts: {
      exported: "Fixture 已导出",
      imported: "Fixture 已导入",
      verified: "Fixture 已验证",
      invalid: "Fixture 无效",
    },
  },
  replay: {
    eyebrow: "运行回放",
    title: "快照验证器",
    body: "在将单次运行的归档回放 JSON 用于证据检查或 CI 回归前，先针对活动会话边界进行验证。",
    verify: "验证回放 JSON",
    verifying: "正在检查回放……",
    verified: "回放已验证",
    invalid: "回放无效",
    subagents: "个子智能体",
  },
  verdicts: {
    left_better: "基线更好",
    right_better: "候选项更好",
    tie: "持平",
    inconclusive: "无结论",
  },
  statuses: {
    completed: "已完成",
    failed: "失败",
    cancelled: "已取消",
    interrupted: "已中断",
  },
  errors: {
    distinct: "请选择两次不同的已结算运行。",
    replayTooLarge: "运行回放快照不得超过 10 MiB。",
    replayInvalid: "请选择有效的 Napier 运行回放快照 JSON 文件。",
    fixtureTooLarge: "回放 Fixture 不得超过 10 MiB。",
    fixtureInvalid: "请选择有效的 Napier 回放 Fixture JSON 文件。",
  },
} as const;
