import { getLocale } from "./locale";

const en = {
  legend: "Model route",
  title: "Route control plane",
  kicker: "ROLE BINDING · ATTRIBUTED FALLBACK",
  enabled: "Route policy enabled",
  disabled: "Use the Agent default model",
  body: "Bind workload roles and paths to explicit models, endpoints, and credential pools. Every attempt is recorded without credential secrets.",
  safety:
    "Fallback stops after visible output or any known or unknown side effect.",
  invalid: "Resolve the highlighted Route policy error before saving.",
  errors: {
    schema: "The Route policy schema is unsupported.",
    capacity: "The Route policy exceeds its endpoint or pool capacity.",
    endpointId: "Endpoint profile IDs must be unique.",
    poolId: "Credential pool IDs must be unique.",
    poolProvider: "Only one credential pool is allowed per provider.",
    endpoint:
      "An endpoint URL, identifier, or header is invalid. Secret-bearing headers are forbidden.",
    pool: "A credential pool is invalid. Explicit pools require at least two active references from the same provider.",
    binding:
      "A binding references an unavailable model or mismatched endpoint/pool. Fallback targets must be unique.",
    retry: "Retry jitter must be 0–0.5 and maximum backoff 1–300 seconds.",
  },
  groups: {
    roles: "Model roles",
    paths: "Execution paths",
    subagentRoles: "Subagent roles",
  },
  groupHints: {
    roles: "Primary intent chooses a durable role binding.",
    paths: "Execution mode can override the effective role.",
    subagentRoles: "A delegated role can use its own frozen chain.",
  },
  labels: {
    default: "Default",
    fast: "Fast",
    reasoning: "Reasoning",
    vision: "Vision",
    subagent: "Subagent",
    interactive: "Interactive",
    recovery: "Recovery",
    automation: "Automation",
    workflow: "Workflow",
    experiment: "Experiment",
    researcher: "Researcher",
    reviewer: "Reviewer",
    general: "Generalist",
    coder: "Coder",
  },
  bind: "Bind",
  model: "Model",
  endpoint: "Endpoint",
  credentialPool: "Credential pool",
  providerDefault: "Provider default",
  activeProviderCredentials: "Active provider credentials",
  fallback: "Fallback chain",
  addFallback: "Add fallback",
  removeFallback: "Remove fallback",
  endpoints: "Endpoint profiles",
  endpointHint:
    "HTTPS or loopback HTTP only. Query strings, embedded credentials, and secret-bearing headers are rejected.",
  addEndpoint: "Add endpoint",
  removeEndpoint: "Remove endpoint",
  endpointId: "Profile ID",
  provider: "Provider",
  kind: "Kind",
  direct: "Direct",
  gateway: "Gateway",
  baseUrl: "Base URL",
  servedModel: "Served model override",
  dialect: "Dialect",
  headers: "Non-secret headers",
  headersPlaceholder: "x-tenant: delivery",
  pools: "Credential pools",
  poolHint:
    "Round-robin skips persisted cooldowns. Empty membership uses every active reference for that provider.",
  addPool: "Add pool",
  removePool: "Remove pool",
  poolId: "Pool ID",
  strategy: "Strategy",
  roundRobin: "Round robin",
  members: "Active references",
  retry: "Retry envelope",
  jitter: "Jitter ratio",
  maxBackoff: "Maximum backoff (sec)",
};

const zh: typeof en = {
  legend: "模型路由",
  title: "路由控制面",
  kicker: "角色绑定 · 可归因回退",
  enabled: "启用路由策略",
  disabled: "使用智能体默认模型",
  body: "把工作角色和执行路径绑定到明确的模型、端点与凭证池；每次尝试都留痕，但不记录凭证秘密。",
  safety: "一旦产生可见输出，或出现已知/未知副作用，回退立即停止。",
  invalid: "请先修复下方路由策略错误，再保存配置。",
  errors: {
    schema: "路由策略版本不受支持。",
    capacity: "端点或凭证池数量超过上限。",
    endpointId: "端点 Profile ID 必须唯一。",
    poolId: "凭证池 ID 必须唯一。",
    poolProvider: "每个 Provider 只能配置一个凭证池。",
    endpoint:
      "端点 URL、标识或 Header 无效；禁止填写认证、Cookie、Key、Secret 或 Token Header。",
    pool: "凭证池无效；显式成员至少需要两个同 Provider 的 active reference。",
    binding:
      "绑定引用了不可用模型或 Provider 不匹配的端点/凭证池，且回退目标必须唯一。",
    retry: "Jitter 范围是 0–0.5，最大退避范围是 1–300 秒。",
  },
  groups: {
    roles: "模型角色",
    paths: "执行路径",
    subagentRoles: "子智能体角色",
  },
  groupHints: {
    roles: "主任务意图选择持久角色绑定。",
    paths: "执行模式可以覆盖有效角色。",
    subagentRoles: "委派角色可以使用独立的冻结回退链。",
  },
  labels: {
    default: "默认",
    fast: "快速",
    reasoning: "推理",
    vision: "视觉",
    subagent: "子智能体",
    interactive: "交互",
    recovery: "恢复",
    automation: "自动化",
    workflow: "工作流",
    experiment: "实验",
    researcher: "研究员",
    reviewer: "审查员",
    general: "通用智能体",
    coder: "开发者",
  },
  bind: "启用绑定",
  model: "模型",
  endpoint: "端点",
  credentialPool: "凭证池",
  providerDefault: "Provider 默认",
  activeProviderCredentials: "该 Provider 的全部 active 凭证",
  fallback: "回退链",
  addFallback: "添加回退",
  removeFallback: "移除回退",
  endpoints: "端点 Profile",
  endpointHint:
    "仅允许 HTTPS 或 loopback HTTP；拒绝查询参数、内嵌凭证和秘密 Header。",
  addEndpoint: "添加端点",
  removeEndpoint: "移除端点",
  endpointId: "Profile ID",
  provider: "Provider",
  kind: "类型",
  direct: "直连",
  gateway: "网关",
  baseUrl: "基础 URL",
  servedModel: "服务端模型覆盖",
  dialect: "协议方言",
  headers: "非秘密 Header",
  headersPlaceholder: "x-tenant: delivery",
  pools: "凭证池",
  poolHint:
    "轮询会跳过持久冷却项；成员留空时使用该 Provider 的全部 active reference。",
  addPool: "添加凭证池",
  removePool: "移除凭证池",
  poolId: "Pool ID",
  strategy: "策略",
  roundRobin: "轮询",
  members: "Active references",
  retry: "重试边界",
  jitter: "Jitter 比例",
  maxBackoff: "最大退避（秒）",
};

export const modelRouteCopy = getLocale() === "zh" ? zh : en;
