export const modelAdvisorReviewCopy = {
  eyebrow: "SECOND OPINION",
  title: "Independent turn reviews",
  empty: "No independent review receipt has been recorded for this Thread.",
  reviewer: "reviewer",
  score: "score",
  risk: "risk",
  issues: "issues",
  verification: "verification",
  verificationStates: {
    current: "current",
    stale: "stale",
    notCurrent: "not current",
    passed: "passed",
    notPassed: "not passed",
    missing: "missing",
  },
  diagnostics: "diagnostics",
  envelope: "envelope",
  receipt: "receipt",
  verdicts: {
    accept: "Accepted",
    revise: "Revision requested",
    block: "Blocked",
    inconclusive: "Inconclusive",
  },
} as const;
