import type { LocaleOverride } from "./locale";
import type { planCopyEn } from "./plan-copy";

export const planZh: LocaleOverride<typeof planCopyEn> = {
  eyebrow: "执行地图",
  title: "持久计划",
  count: "个计划",
  studioEyebrow: "工作室 · 高级功能",
  studioTitle: "工作流工作室",
  studioBody: "实验、可移植计划、模板与策略证据。",
  empty: "请让在线模型为多步骤工作创建计划；每次状态变化都会落入账本。",
  objective: "目标",
  progress: "进度",
  criticalPath: "关键路径",
  readyPath: "就绪",
  blockedPath: "受阻",
  phase: "阶段",
  parallelReady: "可并行就绪项",
  phaseHash: "阶段哈希",
  replan: "最近一次重规划",
  replanHistory: "重规划历史",
  replanSignal: "重规划信号",
  draft: "草稿",
  appliedChanges: "已应用变更",
  draftChanges: "草稿变更",
  recoveryProgress: "恢复进度",
  recoveryComplete: "恢复已完成",
  recoveryInProgress: "正在恢复",
  runRecoveryStep: "运行恢复步骤",
  recoveryNextActions: {
    complete: "替代工作已结算。",
    run_ready_step: "正常继续路径上已有恢复步骤就绪。",
    running: "恢复已经在运行。",
    blocked: "恢复被受阻步骤或缺失产物阻断。",
    verify_artifacts: "关闭前请验证已产出的恢复产物。",
    produce_artifacts: "验证前请先产出预期恢复产物。",
    waiting: "此恢复运行前，请先继续更早的就绪工作。",
    unavailable: "当前没有可用的恢复操作。",
  },
  recoveryStepsSettled: "个恢复步骤已结算",
  recoveryArtifactsVerified: "个恢复产物已验证",
  changes: "项变更",
  records: "条记录",
  expectedRevision: "预期修订版",
  supersededSteps: "已取代步骤",
  supersededArtifacts: "已取代产物",
  addedSteps: "新增步骤",
  addedArtifacts: "新增产物",
  dependencyUpdates: "依赖更新",
  addedStepsHash: "新增步骤哈希",
  addedArtifactsHash: "新增产物哈希",
  dependencyUpdatesHash: "依赖更新哈希",
  latestReplanImpact: "最近重规划影响",
  replanEntityRoles: {
    added: "最近重规划新增",
    dependency_updated: "依赖已更新",
    superseded: "被最近重规划取代",
  },
  reviewDraft: "审查草稿",
  reviewingDraft: "正在审查",
  modelUnavailableHint: "使用模型审查操作前，请先在上下文页面配置此提供商。",
  applyDraft: "应用草稿",
  applyingDraft: "正在应用",
  modelReview: "模型审查",
  score: "评分",
  risk: "风险",
  envelope: "信封",
  receipt: "回执",
  hash: "哈希",
  response: "响应",
  reviewVerdicts: {
    approve: "通过",
    revise: "需修改",
    reject: "拒绝",
    inconclusive: "无法判断",
  },
  replanRisks: {
    low: "低",
    medium: "中",
    high: "高",
  },
  replanStrategies: {
    recover_blocked: "受阻恢复",
    scope_change: "范围变更",
    artifact_drift: "产物漂移",
  },
  next: "运行下一步",
  noReady: "当前没有可运行的就绪步骤。",
  none: "无",
  dependsOn: "依赖项",
  verification: "验证方式",
  evidence: "证据",
  blocker: "阻断项",
  digest: "SHA-256",
  artifacts: "产物清单",
  size: "大小",
  lineCount: "行数",
  source: "来源运行",
  expected: "预期",
  observed: "观测值",
  artifactActions: {
    produce: "标记为已产出",
    producing: "正在标记……",
    verify: "验证字节",
    verifying: "正在验证……",
    preview: "预览文本",
    previewing: "正在预览……",
    previewTitle: "文本预览",
    dataProfile: "检查数据",
    dataProfiling: "正在检查……",
    dataProfileTitle: "数据概况",
    downloadDataProfile: "下载概况",
    verifyDataProfile: "验证概况",
    verifyingDataProfile: "正在验证……",
    dataProfileVerifyInvalidJson: "数据概况 JSON 无效。",
    dataProfileVerificationStatuses: {
      valid: "概况已验证",
      drifted: "概况已漂移",
    },
    dataFormat: "格式",
    rows: "行",
    columns: "列",
    truncated: "已截断",
    observed: "观测值",
    columnSet: "列集合哈希",
    sample: "样本哈希",
    sampleRowsCaption: "有界样本行",
    noRows: "样本中没有数据行。",
    manifest: "查看清单",
    manifesting: "正在读取清单……",
    manifestTitle: "目录清单",
    downloadManifest: "下载清单",
    verifyManifest: "验证清单",
    verifyingManifest: "正在验证……",
    manifestVerifyInvalidJson: "目录清单 JSON 无效。",
    manifestVerificationStatuses: {
      valid: "清单已验证",
      drifted: "清单已漂移",
    },
    entries: "条目",
    files: "文件",
    directories: "目录",
    closePreview: "关闭预览",
    download: "下载文件",
    downloading: "正在下载……",
    verifyFile: "验证文件",
    verifyingFile: "正在验证……",
    fileVerificationStatuses: {
      valid: "文件已验证",
      drifted: "文件已漂移",
    },
    recheck: "重新检查字节",
    rechecking: "正在重新检查……",
    checkDrift: "检查漂移",
    checkingDrift: "正在检查漂移……",
    driftCheckTitle: "漂移检查",
    markMissing: "标记为缺失",
    markingMissing: "正在标记……",
    markDrifted: "标记为已漂移",
    markingDrifted: "正在标记漂移……",
    driftResults: {
      current: "工作区字节仍与已验证摘要一致。",
      drifted: "工作区字节已漂移；标记漂移后会阻断并触发重规划。",
      missing: "工作区产物缺失；标记漂移后会阻断并触发重规划。",
    },
    evidence: {
      produced: "操作者已在工作台中将产物标记为已产出。",
      verified: "工作台已根据工作区实际字节验证产物。",
      rechecked: "工作台已根据工作区实际字节重新检查产物。",
      drifted: "工作台确认已验证产物的字节已偏离工作区。",
      missing: "操作者已在工作台中将产物标记为缺失。",
    },
  },
  archive: {
    eyebrow: "计划归档",
    title: "工作流归档",
    body: "将当前持久计划、重规划账本、产物清单和计划范围证据事件导出为一份哈希绑定的工作流记录。",
    export: "导出归档",
    exporting: "正在绑定归档……",
    verify: "验证归档",
    verifying: "正在检查归档……",
    exported: "归档已导出",
    verified: "归档已验证",
    invalid: "归档无效",
    noDiagnostics: "没有诊断信息",
    events: "事件",
    steps: "步骤",
    artifacts: "产物",
    replans: "重规划",
    eventStream: "事件流",
    safety:
      "归档验证不落盘，并与当前线程和计划路径绑定。哈希覆盖计划投影与有序的计划证据事件。",
    errors: {
      tooLarge: "计划归档不得超过 10 MiB。",
      invalid: "请选择有效的 Napier 计划归档 JSON 文件。",
    },
  },
  blueprint: {
    eyebrow: "工作流蓝图",
    title: "可复用计划",
    body: "将已结算计划提炼为可复用 DAG：保留目标、步骤、依赖、产物声明和来源哈希，不携带运行时证据正文。",
    export: "导出蓝图",
    exporting: "正在绑定蓝图……",
    verify: "验证蓝图",
    verifying: "正在检查蓝图……",
    create: "创建计划",
    creating: "正在创建计划……",
    exported: "蓝图已导出",
    verified: "蓝图已验证",
    invalid: "蓝图无效",
    created: "计划已创建",
    noDiagnostics: "没有诊断信息",
    steps: "步骤",
    artifacts: "产物",
    safety:
      "蓝图验证不落盘。创建计划会重放常规计划创建关口，并且账本事件只记录蓝图和来源哈希。",
    library: {
      eyebrow: "蓝图库",
      title: "模板库",
      body: "将已验证的工作流蓝图保存为本地可复用模板，重放为持久计划，并在不信任原始传输的前提下审计当前交付结果。",
      refresh: "刷新模板库",
      refreshing: "正在读取模板库……",
      save: "保存已验证蓝图",
      saving: "正在保存模板……",
      select: "选择最佳模板",
      selecting: "正在选择……",
      calibrate: "校准",
      calibrating: "正在校准……",
      backtestPolicy: "回测策略",
      backtestingPolicy: "正在回测……",
      applyPolicyOverride: "应用最佳策略",
      applyingPolicyOverride: "正在应用策略……",
      reviewPolicyOverrideDrift: "审查覆盖漂移",
      reviewingPolicyOverrideDrift: "正在审查漂移……",
      retirePolicyOverride: "停用漂移覆盖",
      retiringPolicyOverride: "正在停用覆盖……",
      auditPolicyOverrideRetirements: "审计停用记录",
      auditingPolicyOverrideRetirements: "正在审计停用记录……",
      verifyPolicyOverrideRetirements: "验证停用记录",
      verifyingPolicyOverrideRetirements: "正在验证停用记录……",
      verifyPolicyOverrideRetirementProofBundle: "验证证明包",
      verifyingPolicyOverrideRetirementProofBundle: "正在验证证明包……",
      signPolicyOverrideRetirementProofBundle: "签名证明包",
      signingPolicyOverrideRetirementProofBundle: "正在签名证明包……",
      create: "从模板创建",
      creating: "正在创建计划……",
      preview: "预览",
      previewing: "正在预览……",
      history: "导出历史",
      loadingHistory: "正在导出……",
      verifyHistory: "验证历史",
      verifyingHistory: "正在验证……",
      outcomes: "导出结果",
      loadingOutcomes: "正在绑定结果……",
      verifyOutcomes: "验证结果",
      verifyingOutcomes: "正在验证结果……",
      promoteOutcomeBaseline: "提升为基线",
      promotingOutcomeBaseline: "正在提升……",
      promoteReviewedOutcomeBaseline: "提升已审查版本",
      promotingReviewedOutcomeBaseline: "正在提升已审查版本……",
      qualifyOutcomes: "校验结果",
      qualifyingOutcomes: "正在校验结果……",
      reviewOutcomes: "审查结果",
      reviewingOutcomes: "正在审查结果……",
      qualify: "校验",
      qualifying: "正在检查……",
      archive: "归档",
      archiving: "正在归档……",
      restore: "恢复",
      restoring: "正在恢复……",
      empty: "尚未保存可复用工作流模板。",
      noVerified: "请先导出或验证蓝图，再将其保存到模板库。",
      locked: "当前线程存在运行中或受阻计划时，不能从模板创建计划。",
      records: "个模板",
      replays: "次重放",
      threads: "个线程",
      plans: "个计划",
      completed: "已完成",
      blocked: "受阻",
      cancelled: "已取消",
      valid: "有效",
      invalid: "无效",
      active: "启用",
      archived: "已归档",
      candidates: "个候选项",
      families: "个系列",
      qualified: "已校验",
      rejected: "已拒绝",
      reviewed: "已审查",
      missing: "缺失",
      policyFailed: "策略失败",
      selected: "已选择",
      score: "评分",
      risk: "风险",
      input: "输入",
      response: "响应",
      review: "审查",
      source: "来源",
      shape: "结构",
      updated: "更新时间",
      expected: "预期",
      actual: "实际",
      declared: "声明值",
      observed: "观测值",
      eventSet: "事件集合",
      replayHistory: "重放历史",
      histories: "份历史",
      historySet: "历史集合",
      outcomeSet: "结果集合",
      outcomeBaseline: "结果基线",
      selectionSet: "选择集合",
      portfolioSet: "组合集合",
      policySet: "策略集合",
      overrideSet: "覆盖集合",
      driftReviewSet: "漂移审查集合",
      retirementSet: "停用集合",
      recommendationPolicy: "策略",
      overridePolicy: "覆盖策略",
      bestPolicy: "最佳策略",
      recommendation: "建议",
      highlighted: "重点项",
      recommendedRetire: "建议停用",
      aligned: "一致",
      policySource: "来源",
      override: "覆盖项",
      policies: "项策略",
      divergent: "项分歧",
      average: "平均值",
      topFamily: "最佳系列",
      completion: "完成度",
      current: "当前版本",
      retired: "已停用",
      remaining: "剩余",
      min: "最低值",
      latest: "最新值",
      signer: "签名方",
      receipt: "回执",
      artifact: "产物",
      signed: "已签名",
      eventAnchor: "重放事件",
      eventVerified: "重放事件已验证",
      eventInvalid: "重放事件无效",
      eventVerification: "验证结果",
      latestPreview: "最近预览",
      noDiagnostics: "没有诊断信息",
      statuses: {
        active: "启用",
        archived: "已归档",
      },
      qualificationStatuses: {
        qualified: "来源已校验",
        archived: "模板已归档",
        source_missing: "来源缺失",
        source_drift: "来源漂移",
        invalid: "模板无效",
      },
      previewStatuses: {
        ready: "计划预览已就绪",
        not_qualified: "预览已阻断",
        blocked: "存在未关闭计划",
      },
      verificationStatuses: {
        valid: "历史已验证",
        invalid: "历史无效",
      },
      outcomeVerificationStatuses: {
        valid: "结果已验证",
        invalid: "结果无效",
      },
      outcomeQualificationStatuses: {
        qualified: "结果基线已校验",
        missing_baseline: "结果基线缺失",
        policy_failed: "结果策略失败",
      },
      outcomeReviewVerdicts: {
        promote: "结果审查已提升",
        revise: "结果审查需要修改",
        reject: "结果审查已拒绝",
        inconclusive: "结果审查无法判断",
      },
      outcomeReviewRisks: {
        low: "低",
        medium: "中",
        high: "高",
      },
      outcomeStatuses: {
        active: "启用",
        completed: "已完成",
        blocked: "受阻",
        cancelled: "已取消",
        plan_missing: "计划缺失",
        identity_mismatch: "身份不匹配",
      },
      receipts: {
        saved: "模板已保存",
        reused: "模板已复用",
        archived: "模板已归档",
        restored: "模板已恢复",
        created: "计划已创建",
        history: "重放历史",
        outcomes: "重放结果",
        outcomeBaseline: "结果基线",
        selection: "模板选择",
        portfolioCalibrated: "组合校准",
        policyBacktested: "策略回测",
        policyOverrideApplied: "策略覆盖已应用",
        policyOverrideDriftReviewed: "策略覆盖漂移",
        policyOverrideRetired: "策略覆盖已停用",
        policyOverrideRetirements: "策略覆盖停用记录",
        policyOverrideRetirementsVerified: "策略覆盖停用记录已验证",
        policyOverrideRetirementProofBundle: "策略覆盖停用证明包",
        policyOverrideRetirementProofBundleSigned: "已签名的策略停用证明包",
      },
      outcomeBaselineCreated: "基线已提升",
      outcomeBaselineReused: "基线已经是当前版本",
      safety:
        "已保存模板只保留哈希来源证据。结果回执绑定当前计划投影，不暴露目标、路径、阻断项或证据正文。",
      errors: {
        tooLarge: "重放历史回执不得超过 2 MiB。",
        invalid: "请选择有效的 Napier 蓝图重放历史 JSON 文件。",
        outcomesTooLarge: "重放结果回执不得超过 2 MiB。",
        outcomesInvalid: "请选择有效的 Napier 蓝图重放结果 JSON 文件。",
        policyOverrideRetirementsTooLarge:
          "策略覆盖停用历史回执不得超过 2 MiB。",
        policyOverrideRetirementsInvalid:
          "请选择有效的 Napier 策略覆盖停用历史 JSON 文件。",
        policyOverrideProofBundleNoSigner:
          "签名此证明包前，请先添加可信且支持签名的回执锚点。",
      },
    },
    errors: {
      tooLarge: "计划蓝图不得超过 2 MiB。",
      invalid: "请选择有效的 Napier 计划蓝图 JSON 文件。",
    },
  },
  statuses: {
    active: "启用",
    completed: "已完成",
    blocked: "受阻",
    cancelled: "已取消",
    pending: "待处理",
    ready: "就绪",
    running: "运行中",
    partial: "部分完成",
    skipped: "已跳过",
    expected: "预期",
    candidate: "候选",
    produced: "已产出",
    verified: "已验证",
    missing: "缺失",
    superseded: "已取代",
  },
  safety:
    "步骤只有在具备明确证据时才会结算。文件验证会哈希工作区实际字节；被中断的运行中步骤会以未知结果进入受阻状态。",
};
