export const planCopy = {
  eyebrow: "EXECUTION MAP",
  title: "Durable plan",
  count: "plans",
  empty:
    "Ask a live model to create a plan for multi-step work. Every transition will settle in the ledger.",
  objective: "Objective",
  progress: "Progress",
  criticalPath: "Critical path",
  readyPath: "Ready",
  blockedPath: "Blocked",
  phase: "Phase",
  parallelReady: "Parallel ready",
  phaseHash: "Phase hash",
  replan: "Latest replan",
  replanSignal: "Replan signal",
  draft: "Draft",
  appliedChanges: "Applied changes",
  draftChanges: "Draft changes",
  changes: "changes",
  expectedRevision: "Expected revision",
  supersededSteps: "Superseded steps",
  supersededArtifacts: "Superseded artifacts",
  addedSteps: "Added steps",
  addedArtifacts: "Added artifacts",
  dependencyUpdates: "Dependency updates",
  addedStepsHash: "Added steps hash",
  addedArtifactsHash: "Added artifacts hash",
  dependencyUpdatesHash: "Dependency updates hash",
  reviewDraft: "Review draft",
  reviewingDraft: "Reviewing",
  modelUnavailableHint:
    "Configure this provider in Context before using model review actions.",
  applyDraft: "Apply draft",
  applyingDraft: "Applying",
  modelReview: "Model review",
  score: "Score",
  risk: "Risk",
  envelope: "Envelope",
  receipt: "Receipt",
  hash: "Hash",
  response: "Response",
  reviewVerdicts: {
    approve: "Approve",
    revise: "Revise",
    reject: "Reject",
    inconclusive: "Inconclusive",
  },
  replanRisks: {
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  replanStrategies: {
    recover_blocked: "Blocked recovery",
    scope_change: "Scope change",
    artifact_drift: "Artifact drift",
  },
  next: "Run next step",
  noReady: "No step is currently ready to run.",
  none: "None",
  dependsOn: "Depends on",
  verification: "Verification",
  evidence: "Evidence",
  blocker: "Blocker",
  artifacts: "Artifact manifest",
  digest: "SHA-256",
  size: "Size",
  lineCount: "Lines",
  source: "Source run",
  expected: "Expected",
  observed: "Observed",
  artifactActions: {
    produce: "Mark produced",
    producing: "Marking...",
    verify: "Verify bytes",
    verifying: "Verifying...",
    preview: "Preview text",
    previewing: "Previewing...",
    previewTitle: "Text preview",
    closePreview: "Close preview",
    download: "Download file",
    downloading: "Downloading...",
    recheck: "Recheck bytes",
    rechecking: "Rechecking...",
    checkDrift: "Check drift",
    checkingDrift: "Checking drift...",
    driftCheckTitle: "Drift check",
    markMissing: "Mark missing",
    markingMissing: "Marking...",
    markDrifted: "Mark drifted",
    markingDrifted: "Marking drift...",
    driftResults: {
      current: "Workspace bytes still match the verified digest.",
      drifted: "Workspace bytes drifted. Mark drifted to block and replan.",
      missing:
        "Workspace artifact is missing. Mark drifted to block and replan.",
    },
    evidence: {
      produced: "Operator marked the artifact as produced from Workbench.",
      verified: "Workbench verified the artifact bytes from the workspace.",
      rechecked: "Workbench rechecked the artifact bytes from the workspace.",
      drifted:
        "Workbench confirmed the verified artifact bytes drifted from the workspace.",
      missing: "Operator marked the artifact as missing from Workbench.",
    },
  },
  archive: {
    eyebrow: "PLAN ARCHIVE",
    title: "Workflow archive",
    body: "Export the current durable plan, replan ledger, artifact manifest, and plan-scoped evidence events as one hash-bound workflow record.",
    export: "Export archive",
    exporting: "Binding archive...",
    verify: "Verify archive",
    verifying: "Checking archive...",
    exported: "Archive exported",
    verified: "Archive verified",
    invalid: "Archive invalid",
    noDiagnostics: "No diagnostics",
    events: "events",
    steps: "steps",
    artifacts: "artifacts",
    replans: "replans",
    eventStream: "Event stream",
    safety:
      "Archive verification is no-store and path-bound to the active Thread and Plan. Hashes cover the plan projection and ordered plan evidence events.",
    errors: {
      tooLarge: "Plan archives must be 10 MiB or smaller.",
      invalid: "Choose a valid Napier Plan archive JSON file.",
    },
  },
  blueprint: {
    eyebrow: "WORKFLOW BLUEPRINT",
    title: "Reusable plan",
    body: "Distill a settled plan into a reusable DAG: objective, steps, dependencies, artifact declarations, and source hashes without runtime evidence prose.",
    export: "Export blueprint",
    exporting: "Binding blueprint...",
    verify: "Verify blueprint",
    verifying: "Checking blueprint...",
    create: "Create plan",
    creating: "Creating plan...",
    exported: "Blueprint exported",
    verified: "Blueprint verified",
    invalid: "Blueprint invalid",
    created: "Plan created",
    noDiagnostics: "No diagnostics",
    steps: "steps",
    artifacts: "artifacts",
    safety:
      "Blueprint verification is no-store. Creating a plan replays the normal Plan creation gate and records only blueprint/source hashes in Ledger events.",
    library: {
      eyebrow: "BLUEPRINT LIBRARY",
      title: "Template shelf",
      body: "Keep verified workflow blueprints as local reusable templates, replay them into durable Plans, and audit current delivery outcomes without trusting the original transport.",
      refresh: "Refresh library",
      refreshing: "Reading library...",
      save: "Save verified",
      saving: "Saving template...",
      select: "Select best",
      selecting: "Selecting...",
      calibrate: "Calibrate",
      calibrating: "Calibrating...",
      backtestPolicy: "Backtest policies",
      backtestingPolicy: "Backtesting...",
      applyPolicyOverride: "Apply top policy",
      applyingPolicyOverride: "Applying policy...",
      reviewPolicyOverrideDrift: "Review override drift",
      reviewingPolicyOverrideDrift: "Reviewing drift...",
      retirePolicyOverride: "Retire drifted override",
      retiringPolicyOverride: "Retiring override...",
      auditPolicyOverrideRetirements: "Audit retirements",
      auditingPolicyOverrideRetirements: "Auditing retirements...",
      verifyPolicyOverrideRetirements: "Verify retirements",
      verifyingPolicyOverrideRetirements: "Verifying retirements...",
      verifyPolicyOverrideRetirementProofBundle: "Verify bundle",
      verifyingPolicyOverrideRetirementProofBundle: "Verifying bundle...",
      signPolicyOverrideRetirementProofBundle: "Sign bundle",
      signingPolicyOverrideRetirementProofBundle: "Signing bundle...",
      create: "Create from template",
      creating: "Creating plan...",
      preview: "Preview",
      previewing: "Previewing...",
      history: "Export history",
      loadingHistory: "Exporting...",
      verifyHistory: "Verify history",
      verifyingHistory: "Verifying...",
      outcomes: "Export outcomes",
      loadingOutcomes: "Binding outcomes...",
      verifyOutcomes: "Verify outcomes",
      verifyingOutcomes: "Verifying outcomes...",
      promoteOutcomeBaseline: "Promote baseline",
      promotingOutcomeBaseline: "Promoting...",
      promoteReviewedOutcomeBaseline: "Promote reviewed",
      promotingReviewedOutcomeBaseline: "Promoting reviewed...",
      qualifyOutcomes: "Qualify outcomes",
      qualifyingOutcomes: "Qualifying outcomes...",
      reviewOutcomes: "Review outcomes",
      reviewingOutcomes: "Reviewing outcomes...",
      qualify: "Qualify",
      qualifying: "Checking...",
      archive: "Archive",
      archiving: "Archiving...",
      restore: "Restore",
      restoring: "Restoring...",
      empty: "No reusable workflow templates have been saved yet.",
      noVerified:
        "Export or verify a blueprint first, then save it into the library.",
      locked:
        "Creating from a template is locked while this Thread has an active or blocked Plan.",
      records: "templates",
      replays: "replays",
      threads: "threads",
      plans: "plans",
      completed: "completed",
      blocked: "blocked",
      cancelled: "cancelled",
      valid: "valid",
      invalid: "invalid",
      active: "active",
      archived: "archived",
      candidates: "candidates",
      families: "families",
      qualified: "qualified",
      rejected: "rejected",
      reviewed: "reviewed",
      missing: "missing",
      policyFailed: "policy failed",
      selected: "Selected",
      score: "Score",
      risk: "Risk",
      input: "Input",
      response: "Response",
      review: "Review",
      source: "Source",
      shape: "Shape",
      updated: "Updated",
      expected: "Expected",
      actual: "Actual",
      declared: "Declared",
      observed: "Observed",
      eventSet: "Event set",
      replayHistory: "Replay history",
      histories: "histories",
      historySet: "History set",
      outcomeSet: "Outcome set",
      outcomeBaseline: "Outcome baseline",
      selectionSet: "Selection set",
      portfolioSet: "Portfolio set",
      policySet: "Policy set",
      overrideSet: "Override set",
      driftReviewSet: "Drift review set",
      retirementSet: "Retirement set",
      recommendationPolicy: "Policy",
      overridePolicy: "Override policy",
      bestPolicy: "Best policy",
      recommendation: "Recommendation",
      highlighted: "Highlighted",
      recommendedRetire: "Retire recommended",
      aligned: "Aligned",
      policySource: "Source",
      override: "Override",
      policies: "policies",
      divergent: "divergent",
      average: "Average",
      topFamily: "Top family",
      completion: "Completion",
      current: "Current",
      retired: "Retired",
      remaining: "Remaining",
      min: "Min",
      latest: "Latest",
      signer: "Signer",
      receipt: "Receipt",
      artifact: "Artifact",
      signed: "Signed",
      eventAnchor: "Replay event",
      eventVerified: "Replay event verified",
      eventInvalid: "Replay event invalid",
      eventVerification: "Verification",
      latestPreview: "Latest preview",
      noDiagnostics: "No diagnostics",
      statuses: {
        active: "Active",
        archived: "Archived",
      },
      qualificationStatuses: {
        qualified: "Source qualified",
        archived: "Template archived",
        source_missing: "Source missing",
        source_drift: "Source drift",
        invalid: "Template invalid",
      },
      previewStatuses: {
        ready: "Plan preview ready",
        not_qualified: "Preview blocked",
        blocked: "Open plan exists",
      },
      verificationStatuses: {
        valid: "History verified",
        invalid: "History invalid",
      },
      outcomeVerificationStatuses: {
        valid: "Outcomes verified",
        invalid: "Outcomes invalid",
      },
      outcomeQualificationStatuses: {
        qualified: "Outcome baseline qualified",
        missing_baseline: "Outcome baseline missing",
        policy_failed: "Outcome policy failed",
      },
      outcomeReviewVerdicts: {
        promote: "Outcome review promoted",
        revise: "Outcome review needs revision",
        reject: "Outcome review rejected",
        inconclusive: "Outcome review inconclusive",
      },
      outcomeReviewRisks: {
        low: "Low",
        medium: "Medium",
        high: "High",
      },
      outcomeStatuses: {
        active: "Active",
        completed: "Completed",
        blocked: "Blocked",
        cancelled: "Cancelled",
        plan_missing: "Plan missing",
        identity_mismatch: "Identity mismatch",
      },
      receipts: {
        saved: "Template saved",
        reused: "Template reused",
        archived: "Template archived",
        restored: "Template restored",
        created: "Plan created",
        history: "Replay history",
        outcomes: "Replay outcomes",
        outcomeBaseline: "Outcome baseline",
        selection: "Template selection",
        portfolioCalibrated: "Portfolio calibration",
        policyBacktested: "Policy backtest",
        policyOverrideApplied: "Policy override applied",
        policyOverrideDriftReviewed: "Policy override drift",
        policyOverrideRetired: "Policy override retired",
        policyOverrideRetirements: "Policy override retirements",
        policyOverrideRetirementsVerified:
          "Policy override retirements verified",
        policyOverrideRetirementProofBundle:
          "Policy override retirement proof bundle",
        policyOverrideRetirementProofBundleSigned:
          "Signed policy retirement proof bundle",
      },
      outcomeBaselineCreated: "Baseline promoted",
      outcomeBaselineReused: "Baseline already current",
      safety:
        "Saved templates retain hash-only source evidence. Outcome receipts bind current Plan projections without exposing objective, path, blocker, or evidence prose.",
      errors: {
        tooLarge: "Replay history receipts must be 2 MiB or smaller.",
        invalid: "Choose a valid Napier blueprint replay history JSON file.",
        outcomesTooLarge: "Replay outcome receipts must be 2 MiB or smaller.",
        outcomesInvalid:
          "Choose a valid Napier blueprint replay outcomes JSON file.",
        policyOverrideRetirementsTooLarge:
          "Policy override retirement history receipts must be 2 MiB or smaller.",
        policyOverrideRetirementsInvalid:
          "Choose a valid Napier policy override retirement history JSON file.",
        policyOverrideProofBundleNoSigner:
          "Add a trusted signing-capable receipt anchor before signing this proof bundle.",
      },
    },
    errors: {
      tooLarge: "Plan blueprints must be 2 MiB or smaller.",
      invalid: "Choose a valid Napier Plan blueprint JSON file.",
    },
  },
  statuses: {
    active: "Active",
    completed: "Completed",
    blocked: "Blocked",
    cancelled: "Cancelled",
    pending: "Pending",
    ready: "Ready",
    running: "Running",
    skipped: "Skipped",
    expected: "Expected",
    produced: "Produced",
    verified: "Verified",
    missing: "Missing",
    superseded: "Superseded",
  },
  safety:
    "Steps settle only with explicit evidence. File verification hashes actual workspace bytes; interrupted running steps become blocked with an unknown outcome.",
} as const;
