export const runEvidenceComparisonCopy = {
  harnessFairness: "Harness comparison",
  harnessComparable: "Comparable",
  harnessNotComparable: "Not comparable",
  harnessInsufficientEvidence: "Insufficient evidence",
  harnessFairnessHealthy:
    "Provider, model, task, environment, and Run budget are matched.",
  repeatedCalls: "Repeated calls",
  noNewInformation: "No-new-information calls",
  interventions: "Human interventions",
  firstRead: "First read",
  firstWrite: "First write",
  firstVerify: "First verify",
  promptTokenShare: "Prompt token share",
  toolTokenShare: "Tool schema token share",
  harnessReceipt: "Harness receipt",
  harnessResolution: "Harness resolution",
  harnessResolutionLeft: "Left",
  harnessResolutionRight: "Right",
  traceSummaryCoverage: "Trace summary coverage",
  traceSummaryClean: "Clean",
  traceSummaryGenericPresent: "Generic fallback",
  traceSummaryRegressed: "Regressed",
  traceSummaryHealthy:
    "Candidate trace summaries avoid the generic raw-payload fallback.",
  traceSummaryDiagnostics: "Summary diagnostics",
  traceSummaryGeneric: "Generic",
  traceSummaryGenericDelta: "Generic delta",
  traceSummaryDedicatedDelta: "Dedicated delta",
  traceSummaryDelta: "Summary delta",
  traceSummaryReceipt: "Summary receipt",
  traceSummaryVerification: "Summary verification",
  traceSummaryVerified: "Verified",
  traceSummaryInvalid: "Invalid",
} as const;
