import { deepMergeCopy, getLocale } from "./locale";

const en = {
  tab: "Subagents",
  eyebrow: "LIVE DELEGATION CONTROL",
  title: "Subagent Hub",
  body: "Inspect delegated work, follow durable evidence, and intervene without leaving the Thread.",
  summary: {
    active: "Active",
    terminal: "Terminal",
    orphaned: "Orphaned",
    events: "Event watermark",
  },
  taskList: "Delegated tasks",
  taskCount: "projected",
  omitted: "older tasks omitted",
  noTasksTitle: "No delegated work yet",
  noTasksBody:
    "Subagents appear here when the active Run delegates research, review, general work, or scoped coding.",
  invalidTitle: "Subagent projection rejected",
  invalidBody:
    "The Thread returned a Hub projection that did not satisfy the versioned client contract. Refresh before taking action.",
  selectTask: "Select a delegated task to inspect its live state.",
  roles: {
    researcher: "Research",
    reviewer: "Review",
    general: "General",
    coder: "Code",
  },
  statuses: {
    queued: "Queued",
    starting: "Starting",
    running: "Running",
    waiting_input: "Waiting for input",
    reviewing: "Reviewing",
    completed: "Completed",
    failed: "Failed",
    cancelled: "Cancelled",
    timed_out: "Timed out",
    orphaned: "Orphaned",
  },
  model: "Model",
  run: "Parent Run",
  revision: "Revision",
  steps: "Steps",
  turns: "Turns",
  tokens: "tokens",
  mailbox: "Mailbox",
  pending: "pending",
  lineage: "Lineage",
  parent: "Revived from",
  children: "Revived tasks",
  control: "Live control",
  steering: "Steer",
  input: "Input",
  messagePlaceholder: "Add a constraint, correction, or requested evidence…",
  send: "Send to Subagent",
  sending: "Sending…",
  cancel: "Cancel task",
  cancelReason: "Required cancellation reason",
  confirmCancel: "Confirm cancellation",
  cancelling: "Cancelling…",
  revive: "Revive as new task",
  reviving: "Reviving…",
  actionFailed: "Control action failed",
  unavailable: {
    execution_unavailable:
      "This execution is not attached to the current process.",
    task_not_active: "This task is no longer active.",
    task_not_terminal: "Only a terminal task can be revived.",
    parent_run_not_running: "No active parent Run can revive this task.",
    delegation_budget_exhausted:
      "The active Run has exhausted its delegation budget.",
    role_disabled: "This Subagent role is disabled for the active Run.",
    coder_write_scope_unavailable:
      "The coder write scope is unavailable, so revival is blocked.",
  },
  transcript: "Live transcript",
  transcriptEmpty: "No durable transcript entries yet.",
  redacted: "Content retained by hash only",
  outcome: "Outcome",
  outcomeEmpty: "No structured outcome has been accepted yet.",
  evidence: "evidence",
  unknown: "unknown",
  blocker: "blockers",
  warning: "warnings",
  typedOutput: "Typed output",
  worktree: "Worktree",
  changedFiles: "changed files",
  writeScope: "write scope",
  apply: "Apply",
  postcondition: "Postcondition",
  durable: "durable",
  openHub: "Open supervision view",
};

const zh = {
  tab: "子智能体",
  eyebrow: "实时委派控制",
  title: "子智能体中心",
  body: "集中查看委派进展、持久证据与执行结果，并在不离开当前会话的情况下进行干预。",
  summary: {
    active: "运行中",
    terminal: "已结束",
    orphaned: "已失联",
    events: "事件水位",
  },
  taskList: "委派任务",
  taskCount: "项已投影",
  omitted: "项较早任务未展示",
  noTasksTitle: "尚无委派任务",
  noTasksBody:
    "当前运行委派研究、复核、通用任务或受限代码工作后，子智能体会显示在这里。",
  invalidTitle: "子智能体投影已拒绝",
  invalidBody:
    "会话返回的数据不符合版本化客户端契约。刷新数据后再执行控制操作。",
  selectTask: "选择一个委派任务，查看它的实时状态。",
  roles: {
    researcher: "研究",
    reviewer: "复核",
    general: "通用",
    coder: "编码",
  },
  statuses: {
    queued: "排队中",
    starting: "启动中",
    running: "运行中",
    waiting_input: "等待输入",
    reviewing: "复核中",
    completed: "已完成",
    failed: "失败",
    cancelled: "已取消",
    timed_out: "已超时",
    orphaned: "已失联",
  },
  model: "模型",
  run: "父运行",
  revision: "修订",
  steps: "步骤",
  turns: "轮次",
  tokens: "令牌",
  mailbox: "信箱",
  pending: "待送达",
  lineage: "任务谱系",
  parent: "复活自",
  children: "后续复活任务",
  control: "实时控制",
  steering: "引导",
  input: "输入",
  messagePlaceholder: "补充约束、纠正方向或要求提供证据……",
  send: "发送给子智能体",
  sending: "正在发送……",
  cancel: "取消任务",
  cancelReason: "必须填写取消原因",
  confirmCancel: "确认取消",
  cancelling: "正在取消……",
  revive: "复活为新任务",
  reviving: "正在复活……",
  actionFailed: "控制操作失败",
  unavailable: {
    execution_unavailable: "该执行未连接到当前进程。",
    task_not_active: "该任务已不再运行。",
    task_not_terminal: "只有已结束的任务可以复活。",
    parent_run_not_running: "没有可复活该任务的活动父运行。",
    delegation_budget_exhausted: "活动运行的委派预算已用尽。",
    role_disabled: "活动运行未启用该子智能体角色。",
    coder_write_scope_unavailable: "编码任务缺少写入范围，无法安全复活。",
  },
  transcript: "实时记录",
  transcriptEmpty: "暂时没有持久化记录。",
  redacted: "正文仅以哈希留存",
  outcome: "执行结果",
  outcomeEmpty: "尚未接收结构化执行结果。",
  evidence: "条证据",
  unknown: "项未知",
  blocker: "项阻断",
  warning: "项警告",
  typedOutput: "类型化输出",
  worktree: "工作树",
  changedFiles: "个变更文件",
  writeScope: "项写入范围",
  apply: "应用状态",
  postcondition: "后置条件",
  durable: "已持久化",
  openHub: "打开监督视图",
};

export const subagentHubCopy = deepMergeCopy(
  en,
  getLocale() === "zh" ? zh : {},
);
