import { deepMergeCopy, getLocale, type LocaleOverride } from "./locale";

export const taskSurfaceCopyEn = {
  plan: {
    current: "Current",
    previous: "Previous",
    label: "Plan",
    settled: "settled",
    next: "Next",
    blocker: "Blocker",
    artifacts: "Artifacts",
    verified: "verified",
    produced: "produced",
    missing: "missing",
    phase: "Phase",
    settledPhase: "Settled",
    evidenceRecorded: "Evidence recorded",
    allSettled: "All planned steps settled",
    waiting: "Plan is waiting for the next transition",
    progress: {
      eyebrow: "Live plan",
      ariaLabel: "Live plan progress",
      stepPrefix: "Step ",
      stepSuffix: "",
    },
    statuses: {
      active: "Active",
      completed: "Completed",
      blocked: "Blocked",
      cancelled: "Cancelled",
      pending: "Pending",
      ready: "Ready",
      running: "Running",
      partial: "Partial",
      skipped: "Skipped",
    },
  },
  approval: {
    label: "Approval",
    mode: "Mode",
    multiple: "Multiple choices",
    single: "Single choice",
    selected: "Selected",
    none: "None",
    customAnswer: "Custom answer",
    recordedHidden: "Recorded · content hidden",
    reason: "Reason",
    statuses: {
      pending: "Pending",
      answered: "Answered",
      continued: "Continued",
      cancelled: "Cancelled",
    },
    guidance: {
      pending: "Operator input is required before the Run can continue.",
      answered:
        "Answer recorded. Continue the Run from the active approval panel.",
      continued: "The answer was accepted and execution continued.",
      cancelled: "The approval was cancelled; no continuation was started.",
    },
    cancellationReasons: {
      operator_cancelled: "Cancelled by the operator",
      workflow_timed_out: "Workflow timed out",
      run_completed_without_wait: "Run completed without waiting",
      run_failed: "Run failed",
      run_cancelled: "Run cancelled",
    },
  },
  completion: {
    eyebrow: "Completed",
    title: "Task result",
    items: "results",
    outputCount: "outputs",
    outputs: "Task outputs",
    completedLabel: "Completed steps",
    outputsLabel: "Outputs",
    open: "Open",
    output: "Outputs",
    showDetails: "Show details",
    hideDetails: "Hide details",
  },
} as const;

export const taskSurfaceZh: LocaleOverride<typeof taskSurfaceCopyEn> = {
  plan: {
    current: "当前",
    previous: "先前",
    label: "计划",
    settled: "已结算",
    next: "下一步",
    blocker: "阻断项",
    artifacts: "产物",
    verified: "已验证",
    produced: "已产出",
    missing: "缺失",
    phase: "阶段",
    settledPhase: "已结算",
    evidenceRecorded: "证据已记录",
    allSettled: "所有计划步骤均已结算",
    waiting: "计划正在等待下一次状态变化",
    progress: {
      eyebrow: "实时计划",
      ariaLabel: "实时计划进度",
      stepPrefix: "第 ",
      stepSuffix: " 步",
    },
    statuses: {
      active: "进行中",
      completed: "已完成",
      blocked: "受阻",
      cancelled: "已取消",
      pending: "待处理",
      ready: "就绪",
      running: "运行中",
      partial: "部分完成",
      skipped: "已跳过",
    },
  },
  approval: {
    label: "审批",
    mode: "选择模式",
    multiple: "可多选",
    single: "单选",
    selected: "已选择",
    none: "无",
    customAnswer: "自定义回答",
    recordedHidden: "已记录 · 内容已隐藏",
    reason: "原因",
    statuses: {
      pending: "待处理",
      answered: "已回答",
      continued: "已继续",
      cancelled: "已取消",
    },
    guidance: {
      pending: "继续运行前需要操作者输入。",
      answered: "回答已记录；请从当前审批面板继续运行。",
      continued: "回答已接受，执行已继续。",
      cancelled: "审批已取消，未启动后续运行。",
    },
    cancellationReasons: {
      operator_cancelled: "操作者已取消",
      workflow_timed_out: "工作流已超时",
      run_completed_without_wait: "运行未等待审批即已完成",
      run_failed: "运行失败",
      run_cancelled: "运行已取消",
    },
  },
  completion: {
    eyebrow: "已完成",
    title: "任务结果",
    items: "项结果",
    outputCount: "个产物",
    outputs: "任务输出",
    completedLabel: "完成事项",
    outputsLabel: "产物",
    open: "打开",
    output: "输出",
    showDetails: "展开结果",
    hideDetails: "收起结果",
  },
};

export const taskSurfaceCopy = deepMergeCopy(
  taskSurfaceCopyEn,
  getLocale() === "zh" ? taskSurfaceZh : {},
);
