import type { LocaleOverride } from "./locale";
import type { workspaceProcessCopyEn } from "./workspace-process-copy";

export const workspaceProcessCopyZh: LocaleOverride<
  typeof workspaceProcessCopyEn
> = {
  eyebrow: "SANDBOX 会话",
  title: "工作区进程",
  description:
    "查看受限的 Node 与 Shell 工作、绑定预览的写入，以及只投影到临时 127.0.0.1 端口且禁止出站网络的 OCI 服务。",
  refresh: "刷新",
  cancel: "取消进程",
  cancelling: "正在取消……",
  sendInput: "发送一行",
  sendingInput: "正在发送……",
  closeInput: "关闭标准输入",
  closingInput: "正在关闭……",
  inputLabel: "进程输入",
  inputPlaceholder: "发送给此 Sandbox 进程的 UTF-8 输入",
  inputSafety: "输入文本会直接发送到活动进程且不会写入 Ledger。请勿发送密钥。",
  ptyInputSafety:
    "终端输入仅对当前会话有效；控制字节会按原样发送，PTY 不支持管道关闭语义。",
  inputReceipt: "输入回执",
  stdin: "标准输入",
  showOutput: "显示输出",
  hideOutput: "隐藏输出",
  showDelta: "检查工作区差异",
  hideDelta: "隐藏工作区差异",
  noSessions: "此会话尚未启动 Process Session。",
  outputUnavailable:
    "Runtime 重启后无法获取输出文本；Ledger 哈希与结算证据仍会保留。",
  noOutput: "此游标位置尚未观测到输出。",
  liveOutput: "实时输出",
  workspaceDelta: "工作区窗口",
  deltaHashes: "之前 / 之后 / 路径",
  deltaUnavailable: "Runtime 重启后无法获取相对路径；持久化摘要仍会保留。",
  noDelta: "此执行窗口中未观测到文件变化。",
  indeterminateDelta: "快照上限或快照不可用导致无法完成比较。",
  deltaAttribution:
    "变化可能来自其他本地进程；此视图不会把变化归因到具体写入者。",
  scopedDeltaAttribution:
    "所有观测到的变化都位于已批准的进程写入范围内。接受结果前请检查准确的本地路径。",
  outsideScopeDelta:
    "至少一项变化超出已批准的进程写入范围。归因未知；继续前请检查工作区。",
  deltaTruncated: "这里只显示前 256 个路径；计数和路径集哈希覆盖全部观测差异。",
  beforeHash: "之前",
  afterHash: "之后",
  beforeSize: "之前的字节数",
  afterSize: "之后的字节数",
  deltaFile: "文件",
  deltaDirectory: "目录",
  deltaSymlink: "符号链接",
  reviewRollback: "检查回滚",
  reviewingRollback: "正在检查恢复条件……",
  rollbackTitle: "恢复已批准的写入范围",
  rollbackBody:
    "这会用执行前的私有快照替换每个已批准范围。结算后的任何工作区变化都会阻止该操作。",
  rollbackOutsideScope:
    "进程窗口包含已批准范围之外的变化；此操作只恢复已批准范围。",
  rollbackScopeCount: "范围",
  rollbackEntryCount: "快照条目",
  rollbackBytes: "快照字节数",
  confirmRollback: "恢复范围",
  applyingRollback: "正在恢复……",
  cancelRollback: "保留当前工作区",
  rollbackRestored: "已恢复批准范围",
  rollbackReverted: "回滚失败，已恢复当前工作区",
  rollbackIndeterminate: "回滚结果不确定；继续前请检查工作区。",
  rollbackEvidence: "回滚证据",
  rollbackError: "回滚被拒绝或结果未知。重试前请刷新会话并检查工作区。",
  failureRecovery: "失败恢复",
  failureRecoveryRestore: "异常退出后恢复已批准范围",
  compensationPending: "等待进程结算",
  compensationNotNeeded: "无需处理",
  compensationRestored: "已自动恢复批准范围",
  compensationReverted: "自动恢复已撤销，可由操作人员检查",
  compensationIndeterminate: "自动恢复结果不确定；请检查工作区",
  compensationUnavailable: "无法安全自动恢复；可能需要操作人员检查",
  commandHash: "命令",
  outputHashes: "标准输出 / 标准错误",
  started: "已开始",
  settled: "已结算",
  duration: "耗时",
  limits: "限制",
  localService: "本地服务",
  scope: "范围",
  output: "输出",
  error: "无法加载 Process Session。",
  inputError: "进程输入被拒绝或结果未知。重试前请刷新会话。",
};
