import { deepMergeCopy, getLocale, type LocaleOverride } from "./locale";

const en = {
  railLabel: "Workspace evidence",
  eyebrow: "Evidence ledger",
  title: "Workspace",
  local: "Local",
  currentWork: "Current work",
  next: "Up next",
  progress: "Plan progress",
  completed: "completed",
  run: "Runs",
  event: "Events",
  artifact: "Outputs",
  subagent: "Agents",
  location: "Location",
  files: "Workspace files",
  refreshFiles: "Refresh workspace files",
  loadingFiles: "Loading files…",
  emptyFolder: "Empty folder",
  fileTreeError: "Could not read this folder",
  retryFiles: "Try again",
  loadMoreFiles: "Load more",
  loadingMoreFiles: "Loading more…",
  runtimeData: "Napier data",
  evidence: "Evidence",
  noEvidence: "Outputs and verification evidence will collect here.",
  openOutput: "Open output",
  previewFile: "Preview file",
  backToFiles: "Back to files",
  previewUnavailable: "This file type can be downloaded but not previewed.",
  hideRail: "Hide workspace",
  showRail: "Show workspace",
  browserPreview: "Browser session",
  hideBrowser: "Hide browser session",
} as const;

const zh: LocaleOverride<typeof en> = {
  railLabel: "工作区与证据",
  eyebrow: "证据台账",
  title: "工作区",
  local: "本地",
  currentWork: "当前工作",
  next: "下一步",
  progress: "计划进度",
  completed: "已完成",
  run: "运行",
  event: "事件",
  artifact: "产物",
  subagent: "智能体",
  location: "工作目录",
  files: "工作区文件",
  refreshFiles: "刷新工作区文件",
  loadingFiles: "正在读取文件…",
  emptyFolder: "空文件夹",
  fileTreeError: "无法读取此文件夹",
  retryFiles: "重试",
  loadMoreFiles: "加载更多",
  loadingMoreFiles: "正在加载更多…",
  runtimeData: "Napier 数据",
  evidence: "结果与证据",
  noEvidence: "任务产物与验证证据会汇集到这里。",
  openOutput: "打开产物",
  previewFile: "预览文件",
  backToFiles: "返回文件",
  previewUnavailable: "此文件类型暂不支持预览，可以下载后查看。",
  hideRail: "收起工作区",
  showRail: "显示工作区",
  browserPreview: "浏览器会话",
  hideBrowser: "收起浏览器会话",
};

export const workspaceEvidenceCopy = deepMergeCopy(
  en,
  getLocale() === "zh" ? zh : {},
);
