export const AGENT_TOOL_NAMES = [
  "list_files",
  "read_file",
  "search_files",
  "list_symbols",
  "inspect_data",
  "data_frame",
  "sqlite_query",
  "git_inspect",
  "git_stage_preview",
  "git_stage_apply",
  "git_commit_preview",
  "git_commit_apply",
  "git_branch_create_preview",
  "git_branch_create_apply",
  "git_branch_switch_preview",
  "git_branch_switch_apply",
  "git_review_preview",
  "git_review_apply",
  "inspect_code",
  "read_symbol",
  "ast_query",
  "ast_edit_preview",
  "lsp_diagnostics",
  "lsp_symbols",
  "lsp_definition",
  "lsp_references",
  "lsp_rename",
  "lsp_rename_apply",
  "lsp_code_actions",
  "lsp_code_action_apply",
  "apply_patch",
  "workspace_file_preview",
  "workspace_file_apply",
  "run_command",
  "javascript_kernel",
  "python_kernel",
  "node_debugger",
  "workspace_process",
  "browser",
  "research_source",
  "verify_workspace",
] as const;

export type AgentToolName = (typeof AGENT_TOOL_NAMES)[number];
