export type ContextProjectionComponentState = "absent" | "included" | "omitted";

export interface ContextProjectionReceiptV1 {
  kind: "napier.context-projection";
  schemaVersion: 1;
  status: "within_budget" | "projected" | "unavailable";
  provider: string;
  model: string;
  modelAttempt: number;
  recoveryAttempt: 0 | 1;
  durableMessageSource: "durable_run_context";
  durableMessageCount: number;
  durableMessageSetSha256: string;
  prePruningMessageCount: number;
  prePruningMessageSetSha256: string;
  postPruningMessageCount: number;
  postPruningMessageSetSha256: string;
  preparedMessageCount: number;
  preparedMessageSetSha256: string;
  activeMessageCount: number;
  activeMessageSetSha256: string;
  toolCount: number;
  toolDefinitionSetSha256: string;
  systemPromptBytes: number;
  systemPromptSha256: string;
  promptSourceCount: number;
  includedPromptSourceCount: number;
  omittedPromptSourceCount: number;
  promptSourceSetSha256: string;
  skillCatalog: ContextProjectionComponentState;
  memory: ContextProjectionComponentState;
  compactionCheckpoint: ContextProjectionComponentState;
  toolResultPruning: "none" | "applied";
  prunedToolResultCount: number;
  prunedToolResultBytes: number;
  tokenProjection: "none" | "oldest_complete_units_removed";
  removedMessageCount: number;
  removedUnitCount: number;
  cacheRetention: "none" | "short" | "long" | "provider_default";
  cacheRetentionSource: "caller" | "adapter" | "provider_default";
  adapterContentSha256: string;
  contentClass: "text" | "structured" | "multimodal";
  meterProviderId: string;
  estimateMethod: string;
  activeEstimatedInputTokens: number;
  outputReserveTokens: number;
  reasoningReserveTokens: number;
  safetyReserveTokens: number;
  activeEstimatedTotalTokens: number;
  contextWindowTokens: number;
  pruningReceiptSha256: string;
  tokenPressureReceiptSha256: string;
  contentSha256: string;
}
