type DomainEventCategory =
  | "artifact"
  | "goal"
  | "plan"
  | "memory"
  | "subagent"
  | "extension"
  | "credential"
  | "evaluation"
  | "automation"
  | "channel"
  | "system";
type DomainEventVisibility = "user" | "debug" | "hidden";

function defineEventGroup<
  const TActiveTypes extends readonly string[],
  const TRunAnyTypes extends readonly string[],
  const TTerminalTransitionTypes extends readonly string[],
  const TCategory extends DomainEventCategory,
  const TVisibility extends DomainEventVisibility,
>(definition: {
  activeRunTypes: TActiveTypes;
  runAnyTypes: TRunAnyTypes;
  terminalTransitionTypes: TTerminalTransitionTypes;
  category: TCategory;
  defaultVisibility: TVisibility;
  allowedVisibilities?: readonly DomainEventVisibility[];
  owner: string;
  projectionOwner: string;
}) {
  return {
    ...definition,
    types: [
      ...definition.activeRunTypes,
      ...definition.runAnyTypes,
      ...definition.terminalTransitionTypes,
    ] as readonly [
      ...TActiveTypes,
      ...TRunAnyTypes,
      ...TTerminalTransitionTypes,
    ],
    allowedVisibilities: definition.allowedVisibilities ?? [
      definition.defaultVisibility,
    ],
    schemaVersion: 1 as const,
  };
}

export const RUN_EVENT_DOMAIN_DEFINITION_GROUPS_V1 = [
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "artifact.data_profile_verified",
      "artifact.data_profiled",
      "artifact.diff_previewed",
      "artifact.directory_manifest_verified",
      "artifact.directory_manifested",
      "artifact.drift_checked",
      "artifact.exported",
      "artifact.file_verified",
      "artifact.previewed",
      "verification.completed",
      "workspace.inspected",
    ],
    terminalTransitionTypes: [],
    category: "artifact",
    defaultVisibility: "user",
    owner: "artifact-runtime",
    projectionOwner: "artifact-index",
  }),
  defineEventGroup({
    activeRunTypes: ["goal.continuation.started"],
    runAnyTypes: ["goal.cleared", "goal.evaluated", "goal.set"],
    terminalTransitionTypes: [],
    category: "goal",
    defaultVisibility: "user",
    owner: "goal-runtime",
    projectionOwner: "task-summary",
  }),
  defineEventGroup({
    activeRunTypes: ["goal.evaluation.started"],
    runAnyTypes: ["goal.evaluation.failed"],
    terminalTransitionTypes: [],
    category: "goal",
    defaultVisibility: "debug",
    owner: "goal-runtime",
    projectionOwner: "task-summary",
  }),
  defineEventGroup({
    activeRunTypes: ["goal.continuation.prompt"],
    runAnyTypes: [],
    terminalTransitionTypes: [],
    category: "goal",
    defaultVisibility: "hidden",
    owner: "goal-runtime",
    projectionOwner: "conversation-feed",
  }),
  defineEventGroup({
    // Coordinator/Plan state owns the synthetic runctl events in this group.
    // Loop/map child starts stay fenced to their concrete Agent Runs.
    activeRunTypes: [
      "workflow.loop.iteration.started",
      "workflow.map.item.started",
    ],
    runAnyTypes: [
      "agent.milestone.recorded",
      "plan.artifact.candidate",
      "plan.artifact.missing",
      "plan.artifact.produced",
      "plan.artifact.expected",
      "plan.artifact.superseded",
      "plan.artifact.verified",
      "plan.blueprint.reused",
      "plan.blueprint.saved",
      "plan.created",
      "plan.replanned",
      "plan.step.blocked",
      "plan.step.completed",
      "plan.step.partial",
      "plan.step.reopened",
      "plan.step.skipped",
      "plan.step.started",
      "workflow.artifacts.failed",
      "workflow.artifacts.settled",
      "workflow.approval.requested",
      "workflow.blocked",
      "workflow.breakpoint.continued",
      "workflow.breakpoint.reached",
      "workflow.cancelled",
      "workflow.completed",
      "workflow.deterministic.completed",
      "workflow.experiment.compared",
      "workflow.experiment.failed",
      "workflow.experiment.started",
      "workflow.javascript.completed",
      "workflow.loop.checkpoint.reused",
      "workflow.loop.completed",
      "workflow.loop.iteration.completed",
      "workflow.loop.iteration.failed",
      "workflow.map.completed",
      "workflow.map.item.completed",
      "workflow.map.item.failed",
      "workflow.node.completed",
      "workflow.node.failed",
      "workflow.node.reused",
      "workflow.node.simulated",
      "workflow.node.skipped",
      "workflow.node.started",
      "workflow.paused",
      "workflow.python.completed",
      "workflow.reduce.completed",
      "workflow.started",
      "workflow.waiting",
    ],
    terminalTransitionTypes: [],
    category: "plan",
    defaultVisibility: "user",
    owner: "workflow-runtime",
    projectionOwner: "task-summary",
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "workflow.node.input_replacement.requested",
      "workflow.node.simulation.requested",
    ],
    terminalTransitionTypes: [],
    category: "plan",
    defaultVisibility: "hidden",
    owner: "workflow-runtime",
    projectionOwner: "trace-index",
  }),
  defineEventGroup({
    activeRunTypes: ["workflow.node.prompt"],
    runAnyTypes: [],
    terminalTransitionTypes: [],
    category: "plan",
    defaultVisibility: "hidden",
    owner: "workflow-runtime",
    projectionOwner: "conversation-feed",
  }),
  defineEventGroup({
    activeRunTypes: ["context.memory"],
    runAnyTypes: [],
    terminalTransitionTypes: [],
    category: "memory",
    defaultVisibility: "debug",
    owner: "memory-runtime",
    projectionOwner: "trace-index",
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "memory.approved",
      "memory.archived",
      "memory.proposed",
      "memory.rejected",
      "memory.refreshed",
      "memory.restored",
      "memory.stale",
    ],
    terminalTransitionTypes: [],
    category: "memory",
    defaultVisibility: "user",
    owner: "memory-runtime",
    projectionOwner: "task-summary",
  }),
  defineEventGroup({
    activeRunTypes: ["memory.extraction.started"],
    runAnyTypes: [
      "memory.extraction.completed",
      "memory.extraction.failed",
      "memory.extraction.skipped",
    ],
    terminalTransitionTypes: [],
    category: "memory",
    defaultVisibility: "debug",
    owner: "memory-runtime",
    projectionOwner: "trace-index",
  }),
  defineEventGroup({
    activeRunTypes: [
      "subagent.cancel.requested",
      "subagent.message.delivered",
      "subagent.outcome.repair.requested",
      "subagent.output.repair.requested",
      "subagent.queued",
      "subagent.started",
    ],
    runAnyTypes: [
      "subagent.cancelled",
      "subagent.completed",
      "subagent.failed",
      "subagent.message.accepted",
      "subagent.orphaned",
      "subagent.outcome.accepted",
      "subagent.outcome.rejected",
      "subagent.outcome.repair.outcome",
      "subagent.output.accepted",
      "subagent.output.repair.outcome",
      "subagent.step",
      "subagent.timed_out",
    ],
    terminalTransitionTypes: [],
    category: "subagent",
    defaultVisibility: "user",
    allowedVisibilities: ["user", "debug"],
    owner: "subagent-supervisor",
    projectionOwner: "subagent-roster",
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "credential.reference.checked",
      "credential.reference.created",
      "credential.reference.disabled",
      "credential.reference.enabled",
      "credential.reference.keychain_created",
    ],
    terminalTransitionTypes: [],
    category: "credential",
    defaultVisibility: "user",
    owner: "credential-runtime",
    projectionOwner: "task-summary",
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "evaluation.adjudication.reviewed",
      "evaluation.casebook.case.curated",
      "evaluation.casebook.case.refreshed",
      "evaluation.casebook.case.removed",
      "evaluation.casebook.created",
      "evaluation.casebook.qualification.completed",
      "evaluation.casebook.qualification_baseline.promoted",
      "evaluation.casebook.updated",
      "evaluation.completed",
      "evaluation.consensus.resolved",
      "evaluation.controlled-harness.evidence.recorded",
      "evaluation.release-product.trial.adopted",
      "evaluation.release-product.trial.recorded",
      "evaluation.reviewer_ballot.recorded",
      "evaluation.suite.completed",
      "evaluation.suite.created",
      "evaluation.suite.updated",
      "receipt.signed",
      "receipt.trust_anchor.created",
      "receipt.trust_anchor.revoked",
      "receipt.trust_checkpoint_subscription.created",
      "receipt.trust_checkpoint_subscription.refreshed",
      "receipt.trust_checkpoint_subscription.updated",
      "receipt.trust_directory_quorum_activation_selection.applied",
      "receipt.trust_directory_quorum_activation_selection.policy_applied",
      "receipt.trust_directory_subscription.created",
      "receipt.trust_directory_subscription.refreshed",
      "receipt.trust_directory_subscription.updated",
      "receipt.trust_rotation_proposal_approval_apply.applied",
      "receipt.trust_rotation_proposal_approval_apply.failed",
      "receipt.trust_rotation_proposal_approval_apply.queued",
      "receipt.trust_rotation_proposal_approval_policy_apply.applied",
      "receipt.trust_rotation_proposal_approval_policy_apply.failed",
      "receipt.trust_rotation_proposal_approval_policy_apply.queued",
      "receipt.trust_rotation_proposal_subscription.created",
      "receipt.trust_rotation_proposal_subscription.refreshed",
      "receipt.trust_rotation_proposal_subscription.updated",
      "receipt_trust.checkpoint_registry_quorum_baseline.imported",
      "receipt_trust.checkpoint_registry_quorum_baseline.promoted",
      "receipt_trust.directory_quorum_activation_decision.signed",
      "receipt_trust.directory_quorum_promotion_baseline.imported",
      "receipt_trust.directory_quorum_promotion_baseline.promoted",
      "receipt_trust.rotation_approval_policy_baseline.imported",
      "receipt_trust.rotation_approval_policy_baseline.promoted",
    ],
    terminalTransitionTypes: [],
    category: "evaluation",
    defaultVisibility: "user",
    owner: "evaluation-runtime",
    projectionOwner: "validation-matrix",
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "benchmark.browser.confirmed_form.evaluated",
      "benchmark.evaluated",
      "benchmark.goal.no-progress.evaluated",
      "benchmark.open_web_research.evaluated",
      "benchmark.process.recovery.evaluated",
      "benchmark.research.evaluated",
      "benchmark.ux.evaluated",
      "benchmark.workflow.evaluated",
    ],
    terminalTransitionTypes: [],
    category: "evaluation",
    defaultVisibility: "user",
    owner: "benchmark-kit",
    projectionOwner: "validation-matrix",
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "benchmark.goal.model-responses.observed",
      "benchmark.workflow.model-responses.observed",
    ],
    terminalTransitionTypes: [],
    category: "evaluation",
    defaultVisibility: "debug",
    owner: "benchmark-kit",
    projectionOwner: "validation-matrix",
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "run.recovery.auto.abandoned",
      "run.recovery.auto.claimed",
      "run.recovery.auto.completed",
      "run.recovery.auto.failed",
      "run.recovery.auto.interrupted",
      "run.recovery.auto.skipped",
      "run.recovery.auto.started",
      "schedule.claimed",
      "schedule.completed",
      "schedule.created",
      "schedule.deduplicated",
      "schedule.failed",
      "schedule.skipped",
      "schedule.updated",
    ],
    terminalTransitionTypes: [],
    category: "automation",
    defaultVisibility: "user",
    owner: "automation-runtime",
    projectionOwner: "task-summary",
    // Schedule and automatic-recovery claims have their own durable CAS tokens.
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "channel.dead_letters.retry_applied",
      "channel.dead_letters.exported",
      "channel.created",
      "channel.delivery.accepted",
      "channel.delivery.completed",
      "channel.delivery.deduplicated",
      "channel.delivery.failed",
      "channel.delivery.retry.exhausted",
      "channel.delivery.retry.requested",
      "channel.delivery.retry.scheduled",
      "channel.delivery.started",
      "channel.disabled",
      "channel.enabled",
      "channel.retry_policy.updated",
      "channel.signature_policy.updated",
      "channel.token.rotated",
    ],
    terminalTransitionTypes: [],
    category: "channel",
    defaultVisibility: "user",
    owner: "channel-runtime",
    projectionOwner: "task-summary",
    // Inbound-delivery state, rather than an Agent Run, fences these transitions.
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: [
      "extension.approved",
      "extension.connected",
      "extension.disabled",
      "extension.disconnected",
      "extension.enabled",
      "extension.package.imported",
      "extension.package.signed",
      "extension.package.updated",
      "extension.packages.channel_index.signed",
      "extension.packages.deployed",
      "extension.packages.lockfile.exported",
      "extension.packages.rollout.applied",
      "extension.packages.rollout.published",
      "extension.proposed",
      "extension.publisher.created",
      "extension.publisher.revoked",
      "extension.rejected",
      "extension.tool.approved",
      "extension.tool.rejected",
      "inspector.package.qualified",
      "inspector.package.signed",
      "prompt.package.qualified",
      "prompt.package.signed",
      "skill.content.installed",
      "skill.content.noop",
      "skill.content.replaced",
      "skill.package.installation_matched",
      "skill.package.installed",
      "skill.package.qualified",
      "skill.package.signed",
    ],
    terminalTransitionTypes: [],
    category: "extension",
    defaultVisibility: "user",
    owner: "extension-runtime",
    projectionOwner: "trace-index",
  }),
  defineEventGroup({
    activeRunTypes: [
      "operator.decision.requested",
      "run.environment.negotiated",
    ],
    runAnyTypes: [
      "agent.rolled_back",
      "agent.updated",
      "operator.decision.answered",
      "operator.decision.cancelled",
      "operator.decision.continued",
      "skill.lifecycle",
      "trace.otlp.exported",
    ],
    terminalTransitionTypes: [],
    category: "system",
    defaultVisibility: "user",
    owner: "runtime-system",
    projectionOwner: "trace-index",
    // Answered/continued are terminal-origin audit facts, not new authority.
  }),
  defineEventGroup({
    activeRunTypes: [],
    runAnyTypes: ["benchmark.workflow.runtime.restarted"],
    terminalTransitionTypes: [],
    category: "system",
    defaultVisibility: "user",
    owner: "benchmark-kit",
    projectionOwner: "trace-index",
  }),
  defineEventGroup({
    activeRunTypes: ["model.advisor.correction.requested"],
    runAnyTypes: [
      "context.prompt_variables",
      "context.skills",
      "context.tool_loop_guard",
      "model.advisor.blocked",
      "model.advisor.correction.outcome",
      "model.advisor.independent.reviewed",
      "model.advisor.notice",
      "model.tool_loop.detected",
      "system.note",
    ],
    terminalTransitionTypes: [],
    category: "system",
    defaultVisibility: "debug",
    owner: "runtime-system",
    projectionOwner: "trace-index",
  }),
] as const;
